<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/prototype/weekOfYear/basic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
for ($i = 29; $i <= 31; ++$i) {
$plainDate = new \Temporal\Spec\PlainDate(1975, 12, $i);
Assert::sameValue($plainDate->weekOfYear, 1, "{$plainDate} should be in week 1");
}
for ($i = 1; $i <= 4; ++$i) {
$plainDate = new \Temporal\Spec\PlainDate(1976, 1, $i);
Assert::sameValue($plainDate->weekOfYear, 1, "{$plainDate} should be in week 1");
}
for ($i = 5; $i <= 11; ++$i) {
$plainDate = new \Temporal\Spec\PlainDate(1976, 1, $i);
Assert::sameValue($plainDate->weekOfYear, 2, "{$plainDate} should be in week 2");
}
for ($i = 20; $i <= 26; ++$i) {
$plainDate = new \Temporal\Spec\PlainDate(1976, 12, $i);
Assert::sameValue($plainDate->weekOfYear, 52, "{$plainDate} should be in week 52");
}
for ($i = 27; $i <= 31; ++$i) {
$plainDate = new \Temporal\Spec\PlainDate(1976, 12, $i);
Assert::sameValue($plainDate->weekOfYear, 53, "{$plainDate} should be in week 53");
}
for ($i = 1; $i <= 2; ++$i) {
$plainDate = new \Temporal\Spec\PlainDate(1977, 1, $i);
Assert::sameValue($plainDate->weekOfYear, 53, "{$plainDate} should be in week 53");
}
