<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainTime/prototype/toLocaleString/options-conflict.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$conflictingOptions = [['hour', 'numeric'], ['minute', 'numeric'], ['second', 'numeric'], ['dayPeriod', 'short'], ['fractionalSecondDigits', 3]];
$time = new \Temporal\Spec\PlainTime(12, 34, 56, 987, 654, 321);
Assert::sameValue(is_string($time->toLocaleString('en', ['timeStyle' => 'short'])), true, '');
Assert::throws(\TypeError::class, function () use (&$time) { $time->toLocaleString('en', ['dateStyle' => 'short']); }, 'dateStyle conflicts with PlainTime');
foreach ($conflictingOptions as $__entry__) {
[$option, $value] = array_pad($__entry__, 2, null);
Assert::throws(\TypeError::class, function () use (&$time, &$option, &$value) { $time->toLocaleString('en', [$option => $value, 'timeStyle' => 'short']); }, "time.toLocaleString(\"en\", { {$option}: \"{$value}\",  timeStyle: \"short\" }) throws TypeError");
$time->toLocaleString('en', [$option => $value]);
$time->toLocaleString('en', [$option => $value]);
}
