<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainYearMonth/prototype/add/leap-year-japanese.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$calendar = 'japanese';
$options = ['overflow' => 'reject'];
$years1 = new \Temporal\Spec\Duration(1);
$years1n = new \Temporal\Spec\Duration(-1);
$years4 = new \Temporal\Spec\Duration(4);
$years4n = new \Temporal\Spec\Duration(-4);
$date202002 = \Temporal\Spec\PlainYearMonth::from(['year' => 2020, 'monthCode' => 'M02', 'calendar' => $calendar], $options);
TemporalHelpers::assertPlainYearMonth($date202002->add($years1, $options), 2021, 2, 'M02', 'add 1y to Feb', 'reiwa', 3);
TemporalHelpers::assertPlainYearMonth($date202002->add($years4, $options), 2024, 2, 'M02', 'add 4y to Feb', 'reiwa', 6);
TemporalHelpers::assertPlainYearMonth($date202002->add($years1n, $options), 2019, 2, 'M02', 'subtract 1y from Feb', 'heisei', 31);
TemporalHelpers::assertPlainYearMonth($date202002->add($years4n, $options), 2016, 2, 'M02', 'subtract 4y from Feb', 'heisei', 28);
$months1 = new \Temporal\Spec\Duration(0, 1);
$months1n = new \Temporal\Spec\Duration(0, -1);
$months5 = new \Temporal\Spec\Duration(0, 5);
$months11n = new \Temporal\Spec\Duration(0, -11);
$years1months2 = new \Temporal\Spec\Duration(1, 2);
$years1months2n = new \Temporal\Spec\Duration(-1, -2);
$date20200131 = \Temporal\Spec\PlainYearMonth::from(['year' => 2020, 'monthCode' => 'M01', 'calendar' => $calendar], $options);
$date20200331 = \Temporal\Spec\PlainYearMonth::from(['year' => 2020, 'monthCode' => 'M03', 'calendar' => $calendar], $options);
TemporalHelpers::assertPlainYearMonth($date20200131->add($months1, $options), 2020, 2, 'M02', 'add 1mo to Jan in leap year', 'reiwa', 2);
TemporalHelpers::assertPlainYearMonth(\Temporal\Spec\PlainYearMonth::from(['year' => 2021, 'monthCode' => 'M09', 'calendar' => $calendar], $options)->add($months5), 2022, 2, 'M02', 'add 5mo with result in the next year', 'reiwa', 4);
TemporalHelpers::assertPlainYearMonth(\Temporal\Spec\PlainYearMonth::from(['year' => 2019, 'monthCode' => 'M09', 'calendar' => $calendar], $options)->add($months5), 2020, 2, 'M02', 'add 5mo with result in the next leap year', 'reiwa', 2);
TemporalHelpers::assertPlainYearMonth(\Temporal\Spec\PlainYearMonth::from(['year' => 2021, 'monthCode' => 'M12', 'calendar' => $calendar], $options)->add($years1months2), 2023, 2, 'M02', 'add 1y 2mo with result in the next year', 'reiwa', 5);
TemporalHelpers::assertPlainYearMonth(\Temporal\Spec\PlainYearMonth::from(['year' => 2022, 'monthCode' => 'M12', 'calendar' => $calendar], $options)->add($years1months2), 2024, 2, 'M02', 'add 1y 2mo with result in the next leap year', 'reiwa', 6);
TemporalHelpers::assertPlainYearMonth($date20200331->add($months1n, $options), 2020, 2, 'M02', 'subtract 1mo from Mar in leap year', 'reiwa', 2);
TemporalHelpers::assertPlainYearMonth($date20200131->add($months11n), 2019, 2, 'M02', 'subtract 11mo with result in the previous year', 'heisei', 31);
TemporalHelpers::assertPlainYearMonth(\Temporal\Spec\PlainYearMonth::from(['year' => 2021, 'monthCode' => 'M01', 'calendar' => $calendar], $options)->add($months11n), 2020, 2, 'M02', 'add 11mo with result in the previous leap year', 'reiwa', 2);
TemporalHelpers::assertPlainYearMonth(\Temporal\Spec\PlainYearMonth::from(['year' => 2022, 'monthCode' => 'M04', 'calendar' => $calendar], $options)->add($years1months2n), 2021, 2, 'M02', 'add 1y 2mo with result in the previous year', 'reiwa', 3);
TemporalHelpers::assertPlainYearMonth(\Temporal\Spec\PlainYearMonth::from(['year' => 2021, 'monthCode' => 'M04', 'calendar' => $calendar], $options)->add($years1months2n), 2020, 2, 'M02', 'add 1y 2mo with result in the previous leap year', 'reiwa', 2);
