<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainMonthDay/prototype/toString/calendarname-wrong-type.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$monthday = new \Temporal\Spec\PlainMonthDay(5, 2, 'gregory');
TemporalHelpers::checkStringOptionWrongType('calendarName', 'auto', fn($calendarName) => $monthday->toString(['calendarName' => $calendarName]), fn($result, $descr) => Assert::sameValue($result, '1972-05-02[u-ca=gregory]', $descr));
