<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/since/argument-propertybag-calendar-string.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$instance = new \Temporal\Spec\PlainYearMonth(2019, 6);
$calendar = 'iso8601';
$arg = ['year' => 2019, 'monthCode' => 'M06', 'calendar' => $calendar];
$result = $instance->since($arg);
TemporalHelpers::assertDuration($result, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "Calendar created from string \"{$calendar}\"");
