<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/since/options-invalid.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
$feb20 = new \Temporal\Spec\PlainYearMonth(2020, 2);
$feb21 = new \Temporal\Spec\PlainYearMonth(2021, 2);
foreach ([null, 1, 'hello', true, \Temporal\Tests\Test262\JsSymbol::singleton(), 1] as $badOption) {
if ($badOption === null) { continue; }
Assert::throws(\TypeError::class, function () use (&$feb21, &$feb20, &$badOption) { return $feb21->since($feb20, $badOption); }, "" . (\Temporal\Tests\Test262\Js::toString($badOption)) . " throws TypeError");
}
