<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/since/throws-if-rounded-date-outside-valid-iso-range.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$from = new \Temporal\PlainYearMonth(1970, 1);
$to = new \Temporal\PlainYearMonth(1971, 1);
$options = ['roundingIncrement' => 100_000_000];
Assert::throws(\InvalidArgumentException::class, fn() => $from->since($to, $options), '');
