<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/prototype/add/balance-negative-time-units.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$time = new \Temporal\Spec\PlainTime(1, 1, 1, 1, 1, 1);
$result1 = $time->add(new \Temporal\Spec\Duration(0, 0, 0, 0, 0, 0, 0, 0, 0, -2));
TemporalHelpers::assertPlainTime($result1, 1, 1, 1, 1, 0, 999, 'nanoseconds balance');
$result2 = $time->add(new \Temporal\Spec\Duration(0, 0, 0, 0, 0, 0, 0, 0, -2));
TemporalHelpers::assertPlainTime($result2, 1, 1, 1, 0, 999, 1, 'microseconds balance');
$result3 = $time->add(new \Temporal\Spec\Duration(0, 0, 0, 0, 0, 0, 0, -2));
TemporalHelpers::assertPlainTime($result3, 1, 1, 0, 999, 1, 1, 'milliseconds balance');
$result4 = $time->add(new \Temporal\Spec\Duration(0, 0, 0, 0, 0, 0, -2));
TemporalHelpers::assertPlainTime($result4, 1, 0, 59, 1, 1, 1, 'seconds balance');
$result5 = $time->add(new \Temporal\Spec\Duration(0, 0, 0, 0, 0, -2));
TemporalHelpers::assertPlainTime($result5, 0, 59, 1, 1, 1, 1, 'minutes balance');
$result6 = $time->add(new \Temporal\Spec\Duration(0, 0, 0, 0, -2));
TemporalHelpers::assertPlainTime($result6, 23, 1, 1, 1, 1, 1, 'hours mod 24');
