<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/large-bigint.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
Assert::throws(\RangeException::class, fn() => \Temporal\Spec\Instant::fromEpochParts(340282366920938463463374607431, 768211456), '2n ** 128n');
Assert::throws(\RangeException::class, fn() => \Temporal\Spec\Instant::fromEpochParts(-340282366920938463463374607432, 231788544), '-(2n ** 128n)');
