<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/ZonedDateTime/prototype/toString/calendarname-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$tests = [[[], '1970-01-01T01:01:01.987654321+00:00[UTC]', 'built-in ISO'], [['gregory'], '1970-01-01T01:01:01.987654321+00:00[UTC][u-ca=gregory]', 'built-in Gregorian']];
foreach ($tests as $__entry__) {
[$args, $expected, $description] = array_pad($__entry__, 3, null);
$datetime = new \Temporal\Spec\ZonedDateTime(3_661_987_654_321, 'UTC', ...$args);
$result = $datetime->toString([]);
Assert::sameValue($result, $expected, "default calendarName option is auto with {$description} calendar");
}
