<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/ZonedDateTime/prototype/toString/options-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$datetime1 = new \Temporal\Spec\ZonedDateTime(957_270_896_987_650_000, 'UTC');
$datetime2 = new \Temporal\Spec\ZonedDateTime(957_270_896_987_650_000, 'UTC', 'gregory');
foreach ([[$datetime1, '2000-05-02T12:34:56.98765+00:00[UTC]'], [$datetime2, '2000-05-02T12:34:56.98765+00:00[UTC][u-ca=gregory]']] as $__entry__) {
[$datetime, $expected] = array_pad($__entry__, 2, null);
$explicit = $datetime->toString();
Assert::sameValue($explicit, $expected, 'default show options are auto, precision is auto, and no rounding');
$propertyImplicit = $datetime->toString(new \stdClass());
Assert::sameValue($propertyImplicit, $expected, 'default show options are auto, precision is auto, and no rounding');
$implicit = $datetime->toString();
Assert::sameValue($implicit, $expected, 'default show options are auto, precision is auto, and no rounding');
}
