<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/prototype/with/argument-not-object.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
$instance = new \Temporal\Spec\PlainTime(12, 34, 56, 987, 654, 321);
Assert::throws(\TypeError::class, function () use (&$instance) { return $instance->with(); }, 'undefined');
Assert::throws(\TypeError::class, function () use (&$instance) { return $instance->with(null); }, 'null');
Assert::throws(\TypeError::class, function () use (&$instance) { return $instance->with(true); }, 'true');
Assert::throws(\TypeError::class, function () use (&$instance) { return $instance->with(\Temporal\Tests\Test262\JsSymbol::singleton()); }, 'symbol');
Assert::throws(\TypeError::class, function () use (&$instance) { return $instance->with(1); }, '1');
Assert::throws(\TypeError::class, function () use (&$instance) { return $instance->with(1); }, '1n');
$strings = ['', '18:05:42.577', '2019-05-17T18:05:42.577', '2019-05-17T18:05:42.577Z', '2019-05-17', '42'];
foreach ($strings as $s) {
Assert::throws(\TypeError::class, function () use (&$instance, &$s) { return $instance->with($s); }, $s);
}
