<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/prototype/with/order-of-operations.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$instance = new \Temporal\Spec\PlainTime(12, 34, 56, 987, 654, 321);
$expectedOpsForPrimitiveOptions = ['get fields.calendar', 'get fields.timeZone', 'get fields.hour', 'get fields.hour.valueOf', 'call fields.hour.valueOf', 'get fields.microsecond', 'get fields.microsecond.valueOf', 'call fields.microsecond.valueOf', 'get fields.millisecond', 'get fields.millisecond.valueOf', 'call fields.millisecond.valueOf', 'get fields.minute', 'get fields.minute.valueOf', 'call fields.minute.valueOf', 'get fields.nanosecond', 'get fields.nanosecond.valueOf', 'call fields.nanosecond.valueOf', 'get fields.second', 'get fields.second.valueOf', 'call fields.second.valueOf'];
$expected = array_merge($expectedOpsForPrimitiveOptions, ['get options.overflow', 'get options.overflow.toString', 'call options.overflow.toString']);
$actual = [];
$fields = TemporalHelpers::propertyBagObserver($actual, ['hour' => 1.7, 'minute' => 1.7, 'second' => 1.7, 'millisecond' => 1.7, 'microsecond' => 1.7, 'nanosecond' => 1.7], 'fields');
$options = TemporalHelpers::propertyBagObserver($actual, ['overflow' => 'constrain'], 'options');
$result = $instance->with($fields, $options);
// JS-only (observer call-order check, tracker is empty in PHP): assert.compareArray(actual, expected, "order of operations");
// JS-only (observer tracker reset (no-op in PHP)): actual.splice(0);
// JS-only (JS rejects non-object options via ToObject; PHP accepts null as "absent"): assert.throws(TypeError, () => instance.with(fields, null));
// JS-only (observer call-order check, tracker is empty in PHP): assert.compareArray(actual, expectedOpsForPrimitiveOptions, "argument fields are read before TypeError is thrown for primitive options");
// JS-only (observer tracker reset (no-op in PHP)): actual.splice(0);
\PHPUnit\Framework\Assert::assertTrue(true, 'Script completed without throwing');
