<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/prototype/with/plaintimelike-invalid.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$plainTime = new \Temporal\Spec\PlainTime(12, 34, 56, 987, 654, 321);
Assert::incomplete('untranslatable: Symbol()');
