<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/from/argument-string-trailing-junk.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$arg = '15:23:30.100junk';
Assert::throws(\InvalidArgumentException::class, fn() => \Temporal\PlainTime::from($arg), '');
