<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/from/argument-string-multiple-calendar.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$invalidStrings = ['00:00[u-ca=iso8601][!u-ca=iso8601]', '00:00[!u-ca=iso8601][u-ca=iso8601]', '00:00[UTC][u-ca=iso8601][!u-ca=iso8601]', '00:00[u-ca=iso8601][foo=bar][!u-ca=iso8601]', '1970-01-01T00:00[u-ca=iso8601][!u-ca=iso8601]', '1970-01-01T00:00[!u-ca=iso8601][u-ca=iso8601]', '1970-01-01T00:00[UTC][u-ca=iso8601][!u-ca=iso8601]', '1970-01-01T00:00[u-ca=iso8601][foo=bar][!u-ca=iso8601]'];
foreach ($invalidStrings as $arg) {
Assert::throws(\InvalidArgumentException::class, fn() => \Temporal\Spec\PlainTime::from($arg), "reject more than one calendar annotation if any critical: {$arg}");
}
