<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/from/overflow-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$validValues = [new \Temporal\PlainTime(12), '12:00'];
foreach ($validValues as $value) {
$explicit = \Temporal\PlainTime::from($value, []);
TemporalHelpers::assertPlainTime($explicit, 12, 0, 0, 0, 0, 0, 'overflow is ignored');
$implicit = \Temporal\PlainTime::from($value, new \stdClass());
TemporalHelpers::assertPlainTime($implicit, 12, 0, 0, 0, 0, 0, 'overflow is ignored');
$lambda = \Temporal\PlainTime::from($value, function () {  });
TemporalHelpers::assertPlainTime($lambda, 12, 0, 0, 0, 0, 0, 'overflow is ignored');
}
$propertyBag = ['hour' => 26];
$explicit = \Temporal\PlainTime::from($propertyBag, []);
TemporalHelpers::assertPlainTime($explicit, 23, 0, 0, 0, 0, 0, 'default overflow is constrain');
$implicit = \Temporal\PlainTime::from($propertyBag, new \stdClass());
TemporalHelpers::assertPlainTime($implicit, 23, 0, 0, 0, 0, 0, 'default overflow is constrain');
$lambda = \Temporal\PlainTime::from($propertyBag, function () {  });
TemporalHelpers::assertPlainTime($lambda, 23, 0, 0, 0, 0, 0, 'default overflow is constrain');
