<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/inLeapYear/basic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
Assert::sameValue(new \Temporal\PlainYearMonth(1976, 11)->inLeapYear, true, 'leap year');
Assert::sameValue(new \Temporal\PlainYearMonth(1977, 11)->inLeapYear, false, 'non-leap year');
