<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/toLocaleString/return-string.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$pym = new \Temporal\Spec\PlainYearMonth(1, 1);
Assert::sameValue(is_string($pym->toLocaleString(null, ['calendar' => 'iso8601'])), true, '');
