<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/prototype/round/roundingincrement-wrong-type.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$time = new \Temporal\Spec\PlainTime(12, 34, 56, 987, 654, 321);
TemporalHelpers::checkRoundingIncrementOptionWrongType(fn($roundingIncrement) => $time->round(['smallestUnit' => 'second', 'roundingIncrement' => $roundingIncrement]), fn($result, $descr) => TemporalHelpers::assertPlainTime($result, 12, 34, 57, 0, 0, 0, $descr), fn($result, $descr) => TemporalHelpers::assertPlainTime($result, 12, 34, 56, 0, 0, 0, $descr));
