<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/prototype/round/smallestunit-string-shorthand.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$instance = new \Temporal\PlainTime(12, 34, 56, 789, 999, 999);
$validUnits = ['hour', 'minute', 'second', 'millisecond', 'microsecond', 'nanosecond'];
foreach ($validUnits as $smallestUnit) {
$full = $instance->round(['smallestUnit' => $smallestUnit]);
$shorthand = $instance->round($smallestUnit);
TemporalHelpers::assertPlainTimesEqual($shorthand, $full, "\"{$smallestUnit}\" as first argument to round is equivalent to options bag");
}
