<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainYearMonth/prototype/subtract/basic-dangi.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$calendar = 'dangi';
$options = ['overflow' => 'reject'];
$years1 = new \Temporal\Spec\Duration(-1);
$years1n = new \Temporal\Spec\Duration(1);
$years5 = new \Temporal\Spec\Duration(-5);
$years5n = new \Temporal\Spec\Duration(5);
$date201802 = \Temporal\Spec\PlainYearMonth::from(['year' => 2018, 'monthCode' => 'M02', 'calendar' => $calendar], $options);
$date202302 = \Temporal\Spec\PlainYearMonth::from(['year' => 2023, 'monthCode' => 'M02', 'calendar' => $calendar], $options);
TemporalHelpers::assertPlainYearMonth($date201802->subtract($years1), 2019, 2, 'M02', 'Adding 1 year to day 1 of a month', null, null, null);
TemporalHelpers::assertPlainYearMonth($date202302->subtract($years1), 2024, 2, 'M02', 'Adding 1 year to day 29 of a month', null, null, null);
TemporalHelpers::assertPlainYearMonth($date201802->subtract($years5), 2023, 2, 'M02', 'Adding 5 years to day 1 of a month', null, null, null);
TemporalHelpers::assertPlainYearMonth($date202302->subtract($years5), 2028, 2, 'M02', 'Adding 5 years to day 29 of a month', null, null, null);
TemporalHelpers::assertPlainYearMonth($date201802->subtract($years1n), 2017, 2, 'M02', 'Subtracting 1 year from day 1 of a month', null, null, null);
TemporalHelpers::assertPlainYearMonth($date202302->subtract($years1n), 2022, 2, 'M02', 'Subtracting 1 year from day 29 of a month', null, null, null);
TemporalHelpers::assertPlainYearMonth($date201802->subtract($years5n), 2013, 2, 'M02', 'Subtracting 5 years from day 1 of a month', null, null, null);
TemporalHelpers::assertPlainYearMonth($date202302->subtract($years5n), 2018, 2, 'M02', 'Subtracting 5 years from day 29 of a month', null, null, null);
$months1 = new \Temporal\Spec\Duration(0, -1);
$months1n = new \Temporal\Spec\Duration(0, 1);
$months4 = new \Temporal\Spec\Duration(0, -4);
$months4n = new \Temporal\Spec\Duration(0, 4);
$months6 = new \Temporal\Spec\Duration(0, -6);
$months6n = new \Temporal\Spec\Duration(0, 6);
$date201901 = \Temporal\Spec\PlainYearMonth::from(['year' => 2019, 'monthCode' => 'M01', 'calendar' => $calendar], $options);
$date201906 = \Temporal\Spec\PlainYearMonth::from(['year' => 2019, 'monthCode' => 'M06', 'calendar' => $calendar], $options);
$date201911 = \Temporal\Spec\PlainYearMonth::from(['year' => 2019, 'monthCode' => 'M11', 'calendar' => $calendar], $options);
$date201912 = \Temporal\Spec\PlainYearMonth::from(['year' => 2019, 'monthCode' => 'M12', 'calendar' => $calendar], $options);
$date200012 = \Temporal\Spec\PlainYearMonth::from(['year' => 2000, 'monthCode' => 'M12', 'calendar' => $calendar], $options);
TemporalHelpers::assertPlainYearMonth($date201911->subtract($months1), 2019, 12, 'M12', 'Adding 1 month, with result in same year', null, null, null);
TemporalHelpers::assertPlainYearMonth($date201912->subtract($months1), 2020, 1, 'M01', 'Adding 1 month, with result in next year', null, null, null);
TemporalHelpers::assertPlainYearMonth($date201906->subtract($months4), 2019, 10, 'M10', 'Adding 4 months, with result in same year', null, null, null);
TemporalHelpers::assertPlainYearMonth($date201912->subtract($months4), 2020, 4, 'M04', 'Adding 4 months, with result in next year', null, null, null);
TemporalHelpers::assertPlainYearMonth($date201911->subtract($months1n), 2019, 10, 'M10', 'Subtracting 1 month, with result in same year', null, null, null);
TemporalHelpers::assertPlainYearMonth($date201901->subtract($months1n), 2018, 12, 'M12', 'Subtracting 1 month, with result in previous year', null, null, null);
TemporalHelpers::assertPlainYearMonth($date201906->subtract($months4n), 2019, 2, 'M02', 'Subtracting 4 months, with result in same year', null, null, null);
TemporalHelpers::assertPlainYearMonth($date201901->subtract($months4n), 2018, 9, 'M09', 'Subtracting 4 months, with result in previous year', null, null, null);
TemporalHelpers::assertPlainYearMonth($date200012->subtract($months6), 2001, 6, 'M05', 'Adding 6 months, with result in next year (leap year)', null, null, null);
TemporalHelpers::assertPlainYearMonth($date200012->subtract($months6n), 2000, 6, 'M06', 'Subtracting 6 months, with result in same year', null, null, null);
