<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainYearMonth/prototype/subtract/leap-year-gregory.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$calendar = 'gregory';
$options = ['overflow' => 'reject'];
$years1 = new \Temporal\Spec\Duration(-1);
$years1n = new \Temporal\Spec\Duration(1);
$years4 = new \Temporal\Spec\Duration(-4);
$years4n = new \Temporal\Spec\Duration(4);
$date202002 = \Temporal\Spec\PlainYearMonth::from(['year' => 2020, 'monthCode' => 'M02', 'calendar' => $calendar], $options);
TemporalHelpers::assertPlainYearMonth($date202002->subtract($years1, $options), 2021, 2, 'M02', 'add 1y to leap day', 'ce', 2021);
TemporalHelpers::assertPlainYearMonth($date202002->subtract($years4, $options), 2024, 2, 'M02', 'add 4y to leap day', 'ce', 2024);
TemporalHelpers::assertPlainYearMonth($date202002->subtract($years1n, $options), 2019, 2, 'M02', 'subtract 1y from leap day', 'ce', 2019);
TemporalHelpers::assertPlainYearMonth($date202002->subtract($years4n, $options), 2016, 2, 'M02', 'subtract 4y from leap day', 'ce', 2016);
$months1 = new \Temporal\Spec\Duration(0, -1);
$months1n = new \Temporal\Spec\Duration(0, 1);
$months5 = new \Temporal\Spec\Duration(0, -5);
$months11n = new \Temporal\Spec\Duration(0, 11);
$years1months2 = new \Temporal\Spec\Duration(-1, -2);
$years1months2n = new \Temporal\Spec\Duration(1, 2);
$date202001 = \Temporal\Spec\PlainYearMonth::from(['year' => 2020, 'monthCode' => 'M01', 'calendar' => $calendar], $options);
$date202003 = \Temporal\Spec\PlainYearMonth::from(['year' => 2020, 'monthCode' => 'M03', 'calendar' => $calendar], $options);
TemporalHelpers::assertPlainYearMonth($date202001->subtract($months1, $options), 2020, 2, 'M02', 'add 1mo to in leap year', 'ce', 2020);
TemporalHelpers::assertPlainYearMonth(\Temporal\Spec\PlainYearMonth::from(['year' => 2021, 'monthCode' => 'M09', 'calendar' => $calendar], $options)->subtract($months5), 2022, 2, 'M02', 'add 5mo with result in the next year', 'ce', 2022);
TemporalHelpers::assertPlainYearMonth(\Temporal\Spec\PlainYearMonth::from(['year' => 2019, 'monthCode' => 'M09', 'calendar' => $calendar], $options)->subtract($months5), 2020, 2, 'M02', 'add 5mo with result in the next leap year', 'ce', 2020);
TemporalHelpers::assertPlainYearMonth(\Temporal\Spec\PlainYearMonth::from(['year' => 2021, 'monthCode' => 'M12', 'calendar' => $calendar], $options)->subtract($years1months2), 2023, 2, 'M02', 'add 1y 2mo with result in the next year', 'ce', 2023);
TemporalHelpers::assertPlainYearMonth(\Temporal\Spec\PlainYearMonth::from(['year' => 2022, 'monthCode' => 'M12', 'calendar' => $calendar], $options)->subtract($years1months2), 2024, 2, 'M02', 'add 1y 2mo with result in the next leap year', 'ce', 2024);
TemporalHelpers::assertPlainYearMonth($date202003->subtract($months1n, $options), 2020, 2, 'M02', 'subtract 1mo from Mar in leap year', 'ce', 2020);
TemporalHelpers::assertPlainYearMonth($date202001->subtract($months11n), 2019, 2, 'M02', 'subtract 11mo with result in the previous year', 'ce', 2019);
TemporalHelpers::assertPlainYearMonth(\Temporal\Spec\PlainYearMonth::from(['year' => 2021, 'monthCode' => 'M01', 'calendar' => $calendar], $options)->subtract($months11n), 2020, 2, 'M02', 'add 11mo with result in the previous leap year', 'ce', 2020);
TemporalHelpers::assertPlainYearMonth(\Temporal\Spec\PlainYearMonth::from(['year' => 2022, 'monthCode' => 'M04', 'calendar' => $calendar], $options)->subtract($years1months2n), 2021, 2, 'M02', 'add 1y 2mo with result in the previous year', 'ce', 2021);
TemporalHelpers::assertPlainYearMonth(\Temporal\Spec\PlainYearMonth::from(['year' => 2021, 'monthCode' => 'M04', 'calendar' => $calendar], $options)->subtract($years1months2n), 2020, 2, 'M02', 'add 1y 2mo with result in the previous leap year', 'ce', 2020);
