<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/subtract/overflow-wrong-type.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$datetime = new \Temporal\Spec\PlainDateTime(2000, 5, 2, 12);
$duration = new \Temporal\Spec\Duration(3, 3, 0, 3, 3);
TemporalHelpers::checkStringOptionWrongType('overflow', 'constrain', fn($overflow) => $datetime->subtract($duration, ['overflow' => $overflow]), fn($result, $descr) => TemporalHelpers::assertPlainDateTime($result, 1997, 1, 'M01', 30, 9, 0, 0, 0, 0, 0, $descr));
