<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/prototype/equals/argument-object-tostring.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instance = new \Temporal\Instant(0);
$arg = new \stdClass();
Assert::throws(\InvalidArgumentException::class, fn() => $instance->equals($arg), '[object Object] is not a valid ISO string');
Assert::incomplete('untranslatable expression: FunctionExpression');
