<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainMonthDay/calendar-invalid.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
use Temporal\Tests\Test262\TemporalHelpers;
$expected = ['get month.valueOf', 'call month.valueOf', 'get day.valueOf', 'call day.valueOf'];
$actual = [];
$args = [TemporalHelpers::toPrimitiveObserver($actual, 2, 'month'), TemporalHelpers::toPrimitiveObserver($actual, 1, 'day'), 'local', TemporalHelpers::toPrimitiveObserver($actual, 1, 'year')];
// JS-only (spread of statically too-short array; PHP throws ArgumentCountError): assert.throws(RangeError, () => new Temporal.PlainMonthDay(...args));
// JS-only (observer call-order check, tracker is empty in PHP): assert.compareArray(actual, expected, "order of operations");
\PHPUnit\Framework\Assert::assertTrue(true, 'Script completed without throwing');
