<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainMonthDay/calendar-case-insensitive.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$arg = 'iSo8601';
$result = new \Temporal\Spec\PlainMonthDay(12, 15, $arg, 1972);
Assert::sameValue($result->calendarId, 'iso8601', 'Calendar is case-insensitive');
$arg = 'İSO8601';
Assert::throws(\InvalidArgumentException::class, fn() => new \Temporal\Spec\PlainMonthDay(12, 15, $arg, 1972), 'calendar ID is capital dotted I is not lowercased');
