<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainMonthDay/calendar-invalid-iso-string.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$invalidStrings = [['', 'empty string'], ['1997-12-04[u-ca=iso8601]', 'ISO string with calendar annotation'], ['notacal', 'Unknown calendar'], ['11111111', 'compact ISO date used as calendar name'], ['1111-11-11', 'extended ISO date used as calendar name']];
foreach ($invalidStrings as [$arg, $description]) {
Assert::throws(\InvalidArgumentException::class, fn() => new \Temporal\PlainMonthDay(12, 15, $arg, 1972), "{$description} is not a valid calendar ID");
}
