<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainMonthDay/negative-infinity-throws-rangeerror.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
Assert::throws(\InvalidArgumentException::class, fn() => new \Temporal\Spec\PlainMonthDay(-INF, 1), '');
Assert::throws(\InvalidArgumentException::class, fn() => new \Temporal\Spec\PlainMonthDay(1, -INF), '');
Assert::throws(\InvalidArgumentException::class, fn() => new \Temporal\Spec\PlainMonthDay(1, 1, 'iso8601', -INF), '');
Assert::incomplete('TemporalHelpers.toPrimitiveObserver() is not yet implemented');
