<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainYearMonth/prototype/toLocaleString/resolved-time-zone.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$month = new \Temporal\Spec\PlainYearMonth(2021, 8, 'gregory');
$result = $month->toLocaleString('en', ['timeZone' => 'Pacific/Apia']);
Assert::sameValue($result, '8/2021', '');
