<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/ZonedDateTime/etc-timezone.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
foreach ([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14] as $n) {
$tz = 'Etc/GMT-' . $n;
$instance = new \Temporal\Spec\ZonedDateTime(0, $tz);
Assert::sameValue($instance->timeZoneId, $tz, $tz . ' is a valid timezone');
}
$gmtMinus24TZ = 'Etc/GMT-24';
Assert::throws(\InvalidArgumentException::class, function () use ($gmtMinus24TZ) { new \Temporal\Spec\ZonedDateTime(0, $gmtMinus24TZ); }, $gmtMinus24TZ . ' is an invalid timezone');
foreach ([1, 2, 3, 4, 5, 6, 7, 8, 9] as $n) {
$tz = 'Etc/GMT-0' . $n;
Assert::throws(\InvalidArgumentException::class, function () use ($tz) { new \Temporal\Spec\ZonedDateTime(0, $tz); }, $tz . ' is an invalid timezone');
}
foreach ([0, 1, 2, 3, 4, 5, 6, 7, 8, 9] as $n) {
$tz = 'Etc/GMT+0' . $n;
Assert::throws(\InvalidArgumentException::class, function () use ($tz) { new \Temporal\Spec\ZonedDateTime(0, $tz); }, $tz . ' is an invalid timezone');
}
foreach ([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] as $n) {
$tz = 'Etc/GMT+' . $n;
$instance = new \Temporal\Spec\ZonedDateTime(0, $tz);
Assert::sameValue($instance->timeZoneId, $tz, $tz . ' is a valid timezone');
}
$gmtPlus24TZ = 'Etc/GMT+24';
Assert::throws(\InvalidArgumentException::class, function () use ($gmtPlus24TZ) { new \Temporal\Spec\ZonedDateTime(0, $gmtPlus24TZ); }, $gmtPlus24TZ . ' is an invalid timezone');
