<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/ZonedDateTime/iana-legacy-names.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$legacyNames = ['Etc/GMT0', 'GMT0', 'GMT-0', 'GMT+0', 'EST5EDT', 'CST6CDT', 'MST7MDT', 'PST8PDT'];
foreach ($legacyNames as $arg) {
$instance = new \Temporal\Spec\ZonedDateTime(0, $arg);
Assert::sameValue($instance->timeZoneId, $arg, "\"{$arg}\" does not match \"{$instance->timeZoneId}\" time zone identifier");
}
