<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/ZonedDateTime/supported-values-of.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
foreach (\DateTimeZone::listIdentifiers() as $id) {
$instance = new \Temporal\Spec\ZonedDateTime(0, $id);
Assert::sameValue($instance->timeZoneId, $id, '');
}
