<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/prototype/add/argument-string-invalid.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instance = new \Temporal\PlainDate(2000, 5, 2);
Assert::throws(\InvalidArgumentException::class, fn() => $instance->add('invalid duration string'), 'invalid duration string causes a RangeError');
