<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/prototype/add/basic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$date = new \Temporal\PlainDate(1976, 11, 18);
TemporalHelpers::assertPlainDate($date->add(['days' => 10]), 1976, 11, 'M11', 28, 'add 10 days');
TemporalHelpers::assertPlainDate($date->add(['days' => 30]), 1976, 12, 'M12', 18, 'add 30 days (cross month boundary)');
TemporalHelpers::assertPlainDate($date->add(['months' => 2]), 1977, 1, 'M01', 18, 'add 2 months');
TemporalHelpers::assertPlainDate($date->add(['years' => 3]), 1979, 11, 'M11', 18, 'add 3 years');
TemporalHelpers::assertPlainDate($date->add(['weeks' => 2]), 1976, 12, 'M12', 2, 'add 2 weeks (14 days)');
TemporalHelpers::assertPlainDate($date->add(['years' => 1, 'months' => 2, 'days' => 5]), 1978, 1, 'M01', 23, 'add 1 year, 2 months, 5 days');
