<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/prototype/since/argument-string-time-separators.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$tests = [['1976-11-18T12:34:56.987654321', 'uppercase T'], ['1976-11-18t12:34:56.987654321', 'lowercase T'], ['1976-11-18 12:34:56.987654321', 'space between date and time'], ['T12:34:56.987654321', 'time-only uppercase T'], ['t12:34:56.987654321', 'time-only lowercase T']];
$instance = new \Temporal\PlainTime(12, 34, 56, 987, 654, 321);
foreach ($tests as [$arg, $description]) {
$result = $instance->since($arg);
TemporalHelpers::assertDuration($result, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "variant time separators ({$description})");
}
