<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/prototype/since/options-invalid.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
$values = [null, true, 'hello', \Temporal\Tests\Test262\JsSymbol::singleton(), 1, 1];
$time = new \Temporal\Spec\PlainTime(15, 23, 30, 123, 456, 789);
$one = new \Temporal\Spec\PlainTime(16, 23, 30, 123, 456, 789);
Assert::incomplete('BigInt literal in wrong-type for-of data table; Number-vs-BigInt distinction not representable in PHP');
