<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/until/options-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$earlier = new \Temporal\Spec\ZonedDateTime(957_270_896_987_654_321, 'UTC');
$later = new \Temporal\Spec\ZonedDateTime(959_949_296_987_654_322, 'UTC');
$explicit = $earlier->until($later);
Assert::sameValue($explicit->years, 0, 'default largest unit is hours');
Assert::sameValue($explicit->months, 0, 'default largest unit is hours');
Assert::sameValue($explicit->weeks, 0, 'default largest unit is hours');
Assert::sameValue($explicit->days, 0, 'default largest unit is hours');
Assert::sameValue($explicit->hours, 744, 'default largest unit is hours');
Assert::sameValue($explicit->nanoseconds, 1, 'default smallest unit is nanoseconds and no rounding');
$implicit = $earlier->until($later);
Assert::sameValue($implicit->years, 0, 'default largest unit is hours');
Assert::sameValue($implicit->months, 0, 'default largest unit is hours');
Assert::sameValue($implicit->weeks, 0, 'default largest unit is hours');
Assert::sameValue($implicit->days, 0, 'default largest unit is hours');
Assert::sameValue($implicit->hours, 744, 'default largest unit is hours');
Assert::sameValue($implicit->nanoseconds, 1, 'default smallest unit is nanoseconds and no rounding');
$lambda = $earlier->until($later, function () {  });
Assert::sameValue($lambda->years, 0, 'default largest unit is hours');
Assert::sameValue($lambda->months, 0, 'default largest unit is hours');
Assert::sameValue($lambda->weeks, 0, 'default largest unit is hours');
Assert::sameValue($lambda->days, 0, 'default largest unit is hours');
Assert::sameValue($lambda->hours, 744, 'default largest unit is hours');
Assert::sameValue($lambda->nanoseconds, 1, 'default smallest unit is nanoseconds and no rounding');
