<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/until/roundingincrement-non-integer.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$earlier = new \Temporal\ZonedDateTime(1_000_000_000_000_000_000, 'UTC');
$later = new \Temporal\ZonedDateTime(1_000_000_000_000_000_005, 'UTC');
$result = $earlier->until($later, ['roundingIncrement' => 2.5, 'roundingMode' => 'trunc']);
TemporalHelpers::assertDuration($result, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 'roundingIncrement 2.5 truncates to 2');
