<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/prototype/since/days-in-year.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$plainDate1 = \Temporal\Spec\PlainDate::from('2019-01-01');
$plainDate2 = \Temporal\Spec\PlainDate::from('2020-01-01');
$plainDate3 = \Temporal\Spec\PlainDate::from('2021-01-01');
TemporalHelpers::assertDuration($plainDate2->since($plainDate1), 0, 0, 0, 365, 0, 0, 0, 0, 0, 0, 'From January 2019');
TemporalHelpers::assertDuration($plainDate3->since($plainDate2), 0, 0, 0, 366, 0, 0, 0, 0, 0, 0, 'From January 2020');
$plainDate4 = \Temporal\Spec\PlainDate::from('2019-06-01');
$plainDate5 = \Temporal\Spec\PlainDate::from('2020-06-01');
$plainDate6 = \Temporal\Spec\PlainDate::from('2021-06-01');
TemporalHelpers::assertDuration($plainDate5->since($plainDate4), 0, 0, 0, 366, 0, 0, 0, 0, 0, 0, 'From June 2019');
TemporalHelpers::assertDuration($plainDate6->since($plainDate5), 0, 0, 0, 365, 0, 0, 0, 0, 0, 0, 'From June 2020');
