<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/prototype/since/infinity-throws-rangeerror.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$instance = new \Temporal\Spec\PlainDate(2000, 5, 2);
$base = ['year' => 2000, 'month' => 5, 'day' => 2];
foreach ([INF, -INF] as $inf) {
foreach (['year', 'month', 'day'] as $prop) {
Assert::throws(\InvalidArgumentException::class, fn() => $instance->since(array_merge($base, [$prop => $inf])), "{$prop} property cannot be {$inf}");
$calls = [];
Assert::incomplete('TemporalHelpers.toPrimitiveObserver() is not yet implemented');
}
}
