<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/prototype/since/largestunit-default.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$feb20 = \Temporal\Spec\PlainDate::from('2020-02-01');
$feb21 = \Temporal\Spec\PlainDate::from('2021-02-01');
TemporalHelpers::assertDuration($feb21->since($feb20), 0, 0, 0, 366, 0, 0, 0, 0, 0, 0, 'no options');
TemporalHelpers::assertDuration($feb21->since($feb20), 0, 0, 0, 366, 0, 0, 0, 0, 0, 0, 'undefined options');
TemporalHelpers::assertDuration($feb21->since($feb20, new \stdClass()), 0, 0, 0, 366, 0, 0, 0, 0, 0, 0, 'no largestUnit');
TemporalHelpers::assertDuration($feb21->since($feb20, []), 0, 0, 0, 366, 0, 0, 0, 0, 0, 0, 'undefined largestUnit');
TemporalHelpers::assertDuration($feb21->since($feb20, ['largestUnit' => 'days']), 0, 0, 0, 366, 0, 0, 0, 0, 0, 0, 'days');
TemporalHelpers::assertDuration($feb21->since($feb20, ['largestUnit' => 'auto']), 0, 0, 0, 366, 0, 0, 0, 0, 0, 0, 'auto');
TemporalHelpers::assertDuration($feb21->since($feb20, function () {  }), 0, 0, 0, 366, 0, 0, 0, 0, 0, 0, 'no largestUnit (function)');
