<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/prototype/since/rounding-near-minimum-date.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
use Temporal\Tests\Test262\TemporalHelpers;
$d1 = new \Temporal\Spec\PlainDate(-271_821, 5, 19);
$d2 = new \Temporal\Spec\PlainDate(-271_821, 5, 18);
$result = $d1->since($d2, ['largestUnit' => 'year', 'smallestUnit' => 'day', 'roundingIncrement' => 2, 'roundingMode' => 'expand']);
TemporalHelpers::assertDuration($result, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 'expand rounding of 1 day to increment 2 near minimum date gives 2 days');
