<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/prototype/since/throws-if-rounded-date-outside-valid-iso-range.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$from = new \Temporal\Spec\PlainDate(1970, 1, 1);
$to = new \Temporal\Spec\PlainDate(1971, 1, 1);
$options = ['roundingIncrement' => 100_000_000, 'smallestUnit' => 'months'];
Assert::throws(\InvalidArgumentException::class, function () use (&$from, &$to, &$options) { return $from->since($to, $options); }, '');
