<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/prototype/toPlainDateTime/basic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$date = new \Temporal\PlainDate(2000, 5, 2);
$string = $date->toPlainDateTime('11:30:23');
TemporalHelpers::assertPlainDateTime($string, 2000, 5, 'M05', 2, 11, 30, 23, 0, 0, 0, 'string');
Assert::sameValue($string->calendar, $date->calendar, 'string calendar');
$optionBag = $date->toPlainDateTime(['hour' => 11, 'minute' => 30, 'second' => 23]);
TemporalHelpers::assertPlainDateTime($optionBag, 2000, 5, 'M05', 2, 11, 30, 23, 0, 0, 0, 'option bag');
Assert::sameValue($optionBag->calendar, $date->calendar, 'option bag calendar');
$plainTime = $date->toPlainDateTime(\Temporal\PlainTime::from('11:30:23'));
TemporalHelpers::assertPlainDateTime($plainTime, 2000, 5, 'M05', 2, 11, 30, 23, 0, 0, 0, 'PlainTime');
Assert::sameValue($plainTime->calendar, $date->calendar, 'PlainTime calendar');
$plainDateTime = $date->toPlainDateTime(\Temporal\PlainDateTime::from('1999-07-14T11:30:23'));
TemporalHelpers::assertPlainDateTime($plainDateTime, 2000, 5, 'M05', 2, 11, 30, 23, 0, 0, 0, 'PlainDateTime');
Assert::sameValue($plainDateTime->calendar, $date->calendar, 'PlainDateTime calendar');
Assert::incomplete('\\Temporal\\ZonedDateTime::from() is not yet implemented');
