<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/prototype/toPlainDateTime/time-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$date = new \Temporal\Spec\PlainDate(2000, 5, 2);
$explicit = $date->toPlainDateTime();
TemporalHelpers::assertPlainDateTime($explicit, 2000, 5, 'M05', 2, 0, 0, 0, 0, 0, 0, 'default time is midnight - explicit');
$implicit = $date->toPlainDateTime();
TemporalHelpers::assertPlainDateTime($implicit, 2000, 5, 'M05', 2, 0, 0, 0, 0, 0, 0, 'default time is midnight - implicit');
