<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/argument-convert.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
TemporalHelpers::assertPlainTime(new \Temporal\Spec\PlainTime(11.9, 12.8, 13.7, 14.6, 15.5, 1.999_999), 11, 12, 13, 14, 15, 1, 'positive fractional');
TemporalHelpers::assertPlainTime(new \Temporal\Spec\PlainTime(null, 1, 2, 3, 4, 5), 0, 1, 2, 3, 4, 5, 'null defaults to zero');
TemporalHelpers::assertPlainTime(new \Temporal\Spec\PlainTime(false, true), 0, 1, 0, 0, 0, 0, 'boolean defaults');
TemporalHelpers::assertPlainTime(new \Temporal\Spec\PlainTime(11, 24), 11, 24, 0, 0, 0, 0, 'undefined defaults to 0');
TemporalHelpers::assertPlainTime(new \Temporal\Spec\PlainTime('11.9', '12.8', '13.7', '14.6', '15.5', '1.999999'), 11, 12, 13, 14, 15, 1, 'fractional strings');
Assert::incomplete('untranslatable: Symbol()');
