<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/hour-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$explicit = new \Temporal\PlainTime(null);
TemporalHelpers::assertPlainTime($explicit, 0, 0, 0, 0, 0, 0, 'explicit');
$implicit = new \Temporal\PlainTime();
TemporalHelpers::assertPlainTime($implicit, 0, 0, 0, 0, 0, 0, 'implicit');
