<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/infinity-throws-rangeerror.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
Assert::throws(\InvalidArgumentException::class, fn() => new \Temporal\Spec\PlainTime(INF), '');
Assert::throws(\InvalidArgumentException::class, fn() => new \Temporal\Spec\PlainTime(0, INF), '');
Assert::throws(\InvalidArgumentException::class, fn() => new \Temporal\Spec\PlainTime(0, 0, INF), '');
Assert::throws(\InvalidArgumentException::class, fn() => new \Temporal\Spec\PlainTime(0, 0, 0, INF), '');
Assert::throws(\InvalidArgumentException::class, fn() => new \Temporal\Spec\PlainTime(0, 0, 0, 0, INF), '');
Assert::throws(\InvalidArgumentException::class, fn() => new \Temporal\Spec\PlainTime(0, 0, 0, 0, 0, INF), '');
Assert::incomplete('TemporalHelpers.toPrimitiveObserver() is not yet implemented');
