<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/since/roundingincrement-cleanly-divides.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$earlier = new \Temporal\Spec\PlainDateTime(2019, 1, 8, 8, 22, 36, 123, 456, 789);
$later = new \Temporal\Spec\PlainDateTime(2021, 9, 7, 12, 39, 40, 987, 654, 321);
foreach ([1, 2, 3, 4, 6, 8, 12] as $roundingIncrement) {
$options = ['smallestUnit' => 'hours', 'roundingIncrement' => $roundingIncrement];
Assert::assertTrue($later->since($earlier, $options) instanceof \Temporal\Spec\Duration, "valid hour increments divide into 24 (rounding increment = {$roundingIncrement}, smallest unit = hours)");
}
foreach (['minutes', 'seconds'] as $smallestUnit) {
foreach ([1, 2, 3, 4, 5, 6, 10, 12, 15, 20, 30] as $roundingIncrement) {
$options = ['smallestUnit' => $smallestUnit, 'roundingIncrement' => $roundingIncrement];
Assert::assertTrue($later->since($earlier, $options) instanceof \Temporal\Spec\Duration, "valid {$smallestUnit} increments divide into 60 (rounding increment = {$roundingIncrement})");
}
}
foreach (['milliseconds', 'microseconds', 'nanoseconds'] as $smallestUnit) {
foreach ([1, 2, 4, 5, 8, 10, 20, 25, 40, 50, 100, 125, 200, 250, 500] as $roundingIncrement) {
$options = ['smallestUnit' => $smallestUnit, 'roundingIncrement' => $roundingIncrement];
Assert::assertTrue($later->since($earlier, $options) instanceof \Temporal\Spec\Duration, "valid {$smallestUnit} increments divide into 1000 (rounding increment = {$roundingIncrement})");
}
}
