<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/daysInMonth/basic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$tests = [[1976, 2, 18, 15, 23, 30, 29], [1976, 11, 18, 15, 23, 30, 30], [1976, 12, 18, 15, 23, 30, 31], [1977, 2, 18, 15, 23, 30, 28], [1997, 1, 23, 5, 30, 13, 31], [1996, 2, 23, 5, 30, 13, 29], [2000, 2, 23, 5, 30, 13, 29], [1997, 2, 23, 5, 30, 13, 28], [1997, 3, 23, 5, 30, 13, 31], [1997, 4, 23, 5, 30, 13, 30], [1997, 5, 23, 5, 30, 13, 31], [1997, 6, 23, 5, 30, 13, 30], [1997, 7, 23, 5, 30, 13, 31], [1997, 8, 23, 5, 30, 13, 31], [1997, 9, 23, 5, 30, 13, 30], [1997, 10, 23, 5, 30, 13, 31], [1997, 11, 23, 5, 30, 13, 30], [1997, 12, 23, 5, 30, 13, 31]];
foreach ($tests as $__entry__) {
[$year, $month, $day, $hour, $minute, $second, $expected] = array_pad($__entry__, 7, null);
$plainDateTime = new \Temporal\Spec\PlainDateTime($year, $month, $day, $hour, $minute, $second, 123, 456, 789);
Assert::sameValue($plainDateTime->daysInMonth, $expected, "{$expected} days in the month of {$plainDateTime}");
}
