<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/day/basic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
Assert::sameValue(new \Temporal\Spec\PlainDateTime(2021, 7, 15, 5, 30, 13)->day, 15, '');
Assert::sameValue(\Temporal\Spec\PlainDateTime::from('2019-03-18T05:30:13')->day, 18, '');
