<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainMonthDay/from/calendarresolvefields-error-ordering-chinese.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
Assert::throws(\TypeError::class, fn() => \Temporal\Spec\PlainMonthDay::from((object) ['calendar' => 'chinese', 'monthCode' => 'M04', 'month' => 5, 'day' => 1]), 'Missing year throws TypeError before month/monthCode conflict throws RangeError');
Assert::throws(\TypeError::class, fn() => \Temporal\Spec\PlainMonthDay::from((object) ['calendar' => 'chinese', 'year' => 2020, 'day' => 32], (object) ['overflow' => 'reject']), 'Missing monthCode/month throws TypeError before out-of-range day throws RangeError');
Assert::throws(\TypeError::class, fn() => \Temporal\Spec\PlainMonthDay::from((object) ['calendar' => 'chinese', 'year' => 2020, 'monthCode' => 'M04', 'month' => 5]), 'Missing day throws TypeError before month/monthCode conflict throws RangeError');
Assert::throws(\TypeError::class, fn() => \Temporal\Spec\PlainMonthDay::from((object) ['calendar' => 'chinese', 'monthCode' => 'M04', 'month' => 5, 'day' => 1]), 'undefined year throws TypeError before month/monthCode conflict throws RangeError');
Assert::throws(\RangeException::class, fn() => \Temporal\Spec\PlainMonthDay::from((object) ['calendar' => 'chinese', 'year' => 2020, 'monthCode' => 'M04', 'month' => 5, 'day' => 1]), 'month/monthCode conflict throws RangeError when all required fields present');
Assert::throws(\RangeException::class, fn() => \Temporal\Spec\PlainMonthDay::from((object) ['calendar' => 'chinese', 'year' => 2020, 'monthCode' => 'M01', 'day' => 32], (object) ['overflow' => 'reject']), 'Out-of-range day throws RangeError when all required fields present');
$pmd = \Temporal\Spec\PlainMonthDay::from((object) ['calendar' => 'chinese', 'year' => 2004, 'monthCode' => 'M04', 'month' => 5, 'day' => 1]);
$pd = \Temporal\Spec\PlainDate::from((string) ($pmd));
Assert::sameValue($pmd->monthCode, 'M04', 'Temporal.PlainMonthDay monthCode');
Assert::sameValue($pd->monthCode, 'M04', 'Temporal.PlainDate monthCode');
Assert::sameValue($pd->month, 4, 'Temporal.PlainDate ordinal month');
