<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainMonthDay/from/chinese-month-codes.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$calendar = 'chinese';
$monthCodesWithYears = [['monthCode' => 'M01', 'referenceYear30' => 1970], ['monthCode' => 'M02', 'referenceYear30' => 1972], ['monthCode' => 'M03', 'referenceYear30' => 1966], ['monthCode' => 'M04', 'referenceYear30' => 1970], ['monthCode' => 'M05', 'referenceYear30' => 1972], ['monthCode' => 'M06', 'referenceYear30' => 1971], ['monthCode' => 'M07', 'referenceYear30' => 1972], ['monthCode' => 'M08', 'referenceYear30' => 1971], ['monthCode' => 'M09', 'referenceYear30' => 1972], ['monthCode' => 'M10', 'referenceYear30' => 1972], ['monthCode' => 'M11', 'referenceYear30' => 1970], ['monthCode' => 'M12', 'referenceYear30' => 1972]];
foreach ($monthCodesWithYears as $__obj__) {
$monthCode = $__obj__['monthCode'] ?? null;
$referenceYear30 = $__obj__['referenceYear30'] ?? null;
$pmd = \Temporal\Spec\PlainMonthDay::from(['calendar' => $calendar, 'monthCode' => $monthCode, 'day' => 1]);
TemporalHelpers::assertPlainMonthDay($pmd, $monthCode, 1, "{$monthCode}-01", 1972);
$pmd29 = \Temporal\Spec\PlainMonthDay::from(['calendar' => $calendar, 'monthCode' => $monthCode, 'day' => 29]);
TemporalHelpers::assertPlainMonthDay($pmd29, $monthCode, 29, "{$monthCode}-29", 1972);
$pmd30 = \Temporal\Spec\PlainMonthDay::from(['calendar' => $calendar, 'monthCode' => $monthCode, 'day' => 30]);
TemporalHelpers::assertPlainMonthDay($pmd30, $monthCode, 30, "{$monthCode}-30", $referenceYear30);
$constrained = \Temporal\Spec\PlainMonthDay::from(['calendar' => $calendar, 'monthCode' => $monthCode, 'day' => 31]);
TemporalHelpers::assertPlainMonthDay($constrained, $monthCode, 30, "{$monthCode}-31 constrained", $referenceYear30);
Assert::throws(\InvalidArgumentException::class, function () use ($calendar, $monthCode) { \Temporal\Spec\PlainMonthDay::from(['calendar' => $calendar, 'monthCode' => $monthCode, 'day' => 31], ['overflow' => 'reject']); }, "{$monthCode} with day 31 should throw with reject overflow");
}
