<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainMonthDay/from/chinese-dangi-constrain-rare-leap-months.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$monthCodesWithYears = [['monthCode' => 'M01L', 'referenceYear' => 1970], ['monthCode' => 'M02L', 'referenceYear' => 1972], ['monthCode' => 'M08L', 'referenceYear' => 1971], ['monthCode' => 'M09L', 'referenceYear' => 1972], ['monthCode' => 'M10L', 'referenceYear' => 1972], ['monthCode' => 'M11L', 'referenceYear' => 1970], ['monthCode' => 'M12L', 'referenceYear' => 1972]];
$daysToTest = [30, 31];
$calendars = ['chinese', 'dangi'];
foreach ($calendars as $calendar) {
foreach ($monthCodesWithYears as $__obj__) {
$monthCode = $__obj__['monthCode'] ?? null;
$referenceYear = $__obj__['referenceYear'] ?? null;
foreach ($daysToTest as $day) {
Assert::incomplete('untranslatable: Array.prototype.slice()');
}
}
}
