<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainMonthDay/from/dont-calculate-month-info-for-out-of-range-year.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$testData = [['buddhist', 'M02', 29, 'be'], ['chinese', 'M06L', 30], ['coptic', 'M13', 6, 'am'], ['dangi', 'M06L', 30], ['ethioaa', 'M13', 6, 'aa'], ['ethiopic', 'M13', 6, 'aa'], ['gregory', 'M02', 29, 'ce', 'bce'], ['hebrew', 'M05L', 29, 'am'], ['indian', 'M01', 31, 'shaka'], ['islamic-civil', 'M12', 30, 'ah', 'bh'], ['islamic-tbla', 'M12', 30, 'ah', 'bh'], ['islamic-umalqura', 'M12', 30, 'ah', 'bh'], ['japanese', 'M02', 29, 'reiwa', 'bce'], ['persian', 'M12', 30, 'ap'], ['roc', 'M02', 29, 'roc', 'broc']];
foreach ($testData as $__entry__) {
[$calendar, $monthCode, $day, $posEra, $negEra] = array_pad($__entry__, 5, 0);
Assert::throws(\InvalidArgumentException::class, function () use ($monthCode, $day, $calendar) { \Temporal\Spec\PlainMonthDay::from(['year' => -999_999, 'monthCode' => $monthCode, 'day' => $day, 'calendar' => $calendar]); }, "{$calendar} bails out when year is -999999");
Assert::throws(\InvalidArgumentException::class, function () use ($monthCode, $day, $calendar) { \Temporal\Spec\PlainMonthDay::from(['year' => 999_999, 'monthCode' => $monthCode, 'day' => $day, 'calendar' => $calendar]); }, "{$calendar} bails out when year is +999999");
if ($posEra) {
Assert::throws(\InvalidArgumentException::class, function () use ($posEra, $monthCode, $day, $calendar) { \Temporal\Spec\PlainMonthDay::from(['eraYear' => 999_999, 'era' => $posEra, 'monthCode' => $monthCode, 'day' => $day, 'calendar' => $calendar]); }, "{$calendar} bails out when era year is +999999 {$posEra}");
if ($negEra) {
Assert::throws(\InvalidArgumentException::class, function () use ($negEra, $monthCode, $day, $calendar) { \Temporal\Spec\PlainMonthDay::from(['eraYear' => 999_999, 'era' => $negEra, 'monthCode' => $monthCode, 'day' => $day, 'calendar' => $calendar]); }, "{$calendar} bails out when era year is +999999 {$negEra}");
} else {
Assert::throws(\InvalidArgumentException::class, function () use ($posEra, $monthCode, $day, $calendar) { \Temporal\Spec\PlainMonthDay::from(['eraYear' => -999_999, 'era' => $posEra, 'monthCode' => $monthCode, 'day' => $day, 'calendar' => $calendar]); }, "{$calendar} bails out when era year is -999999 {$posEra}");
}
}
}
