<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainMonthDay/from/islamic-tbla-month-codes.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$calendar = 'islamic-tbla';
$monthsWith30Days = [['M01'], ['M03'], ['M05'], ['M07'], ['M09'], ['M11'], ['M12', 1971]];
foreach ($monthsWith30Days as $__entry__) {
[$monthCode, $referenceYear30] = array_pad($__entry__, 2, null);
$referenceYear30 = $referenceYear30 ?? 1972;
$pmd = \Temporal\Spec\PlainMonthDay::from(['calendar' => $calendar, 'monthCode' => $monthCode, 'day' => 1]);
TemporalHelpers::assertPlainMonthDay($pmd, $monthCode, 1, "{$monthCode}-01");
$pmd30 = \Temporal\Spec\PlainMonthDay::from(['calendar' => $calendar, 'monthCode' => $monthCode, 'day' => 30]);
TemporalHelpers::assertPlainMonthDay($pmd30, $monthCode, 30, "{$monthCode}-30", $referenceYear30);
$constrained = \Temporal\Spec\PlainMonthDay::from(['calendar' => $calendar, 'monthCode' => $monthCode, 'day' => 31], ['overflow' => 'constrain']);
TemporalHelpers::assertPlainMonthDay($constrained, $monthCode, 30, "day 31 should be constrained to 30 for {$monthCode}", $referenceYear30);
Assert::throws(\InvalidArgumentException::class, function () use ($calendar, $monthCode) { \Temporal\Spec\PlainMonthDay::from(['calendar' => $calendar, 'monthCode' => $monthCode, 'day' => 31], ['overflow' => 'reject']); }, "{$monthCode} with day 31 should throw with reject overflow");
}
$monthsWith29Days = ['M02', 'M04', 'M06', 'M08', 'M10'];
foreach ($monthsWith29Days as $monthCode) {
$pmd = \Temporal\Spec\PlainMonthDay::from(['calendar' => $calendar, 'monthCode' => $monthCode, 'day' => 1]);
TemporalHelpers::assertPlainMonthDay($pmd, $monthCode, 1, "{$monthCode}-01");
$pmd29 = \Temporal\Spec\PlainMonthDay::from(['calendar' => $calendar, 'monthCode' => $monthCode, 'day' => 29]);
TemporalHelpers::assertPlainMonthDay($pmd29, $monthCode, 29, "{$monthCode}-29");
$constrained = \Temporal\Spec\PlainMonthDay::from(['calendar' => $calendar, 'monthCode' => $monthCode, 'day' => 30], ['overflow' => 'constrain']);
TemporalHelpers::assertPlainMonthDay($constrained, $monthCode, 29, "day 30 should be constrained to 29 for {$monthCode}");
Assert::throws(\InvalidArgumentException::class, function () use ($calendar, $monthCode) { \Temporal\Spec\PlainMonthDay::from(['calendar' => $calendar, 'monthCode' => $monthCode, 'day' => 30], ['overflow' => 'reject']); }, "{$monthCode} with day 30 should throw with reject overflow");
}
