<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/with/basic-year-month-day.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$cases = ['year2000' => \Temporal\ZonedDateTime::from(['year' => 2000, 'monthCode' => 'M01', 'day' => 1, 'hour' => 12, 'minute' => 34, 'timeZone' => 'UTC']), 'year1976' => \Temporal\ZonedDateTime::from(['year' => 1976, 'monthCode' => 'M11', 'day' => 18, 'hour' => 12, 'minute' => 34, 'timeZone' => 'UTC']), 'year1' => \Temporal\ZonedDateTime::from(['year' => 1, 'monthCode' => 'M01', 'day' => 1, 'hour' => 12, 'minute' => 34, 'timeZone' => 'UTC'])];
foreach ($cases as $name => $inCal) {
$afterWithDay = $inCal->with(['day' => 1]);
TemporalHelpers::assertPlainDateTime($afterWithDay->toPlainDateTime(), $inCal->year, $inCal->month, $inCal->monthCode, 1, 12, 34, 0, 0, 0, 0, "{$name} after setting day to 1");
$afterWithMonth = $afterWithDay->with(['month' => 1]);
TemporalHelpers::assertPlainDateTime($afterWithMonth->toPlainDateTime(), $inCal->year, 1, 'M01', 1, 12, 34, 0, 0, 0, 0, "{$name} after setting month to 1");
$afterWithYear = $afterWithMonth->with(['year' => 2220]);
TemporalHelpers::assertPlainDateTime($afterWithYear->toPlainDateTime(), 2220, 1, 'M01', 1, 12, 34, 0, 0, 0, 0, "{$name} after setting year to 2220");
$afterWithYear = $inCal->with(['year' => 2019]);
TemporalHelpers::assertPlainDateTime($afterWithYear->toPlainDateTime(), 2019, $inCal->month, $inCal->monthCode, $inCal->day, 12, 34, 0, 0, 0, 0, "{$name} after setting year to 2019");
$afterWithMonth = $afterWithYear->with(['month' => 5]);
TemporalHelpers::assertPlainDateTime($afterWithMonth->toPlainDateTime(), 2019, 5, 'M05', $inCal->day, 12, 34, 0, 0, 0, 0, "{$name} after setting month to 5");
$afterWithDay = $afterWithMonth->with(['day' => 17]);
TemporalHelpers::assertPlainDateTime($afterWithDay->toPlainDateTime(), 2019, 5, 'M05', 17, 12, 34, 0, 0, 0, 0, "{$name} after setting day to 17");
}
