<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/with/copy-properties-not-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$d1 = new \Temporal\Spec\ZonedDateTime(1_000_000_000_000_000_789, 'UTC');
$d2 = $d1->with(['day' => 1, 'hour' => 10]);
Assert::sameValue($d2->year, 2001, 'only the properties that are present and defined in the plain object are copied (year value)');
Assert::sameValue($d2->month, 9, 'only the properties that are present and defined in the plain object are copied (month value)');
Assert::sameValue($d2->day, 1, 'only the properties that are present and defined in the plain object are copied (day value)');
Assert::sameValue($d2->hour, 10, 'only the properties that are present and defined in the plain object are copied (hour value)');
Assert::sameValue($d2->minute, 46, 'only the properties that are present and defined in the plain object are copied (minute value)');
Assert::sameValue($d2->second, 40, 'only the properties that are present and defined in the plain object are copied (second value)');
Assert::sameValue($d2->millisecond, 0, 'only the properties that are present and defined in the plain object are copied (millisecond value)');
Assert::sameValue($d2->microsecond, 0, 'only the properties that are present and defined in the plain object are copied (microsecond value)');
Assert::sameValue($d2->nanosecond, 789, 'only the properties that are present and defined in the plain object are copied (nanosecond value)');
