<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/with/infinity-throws-rangeerror.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$instance = new \Temporal\Spec\ZonedDateTime(1_000_000_000_000_000_000, 'UTC');
foreach ([INF, -INF] as $inf) {
foreach (['year', 'month', 'day', 'hour', 'minute', 'second', 'millisecond', 'microsecond', 'nanosecond'] as $prop) {
foreach (['constrain', 'reject'] as $overflow) {
Assert::throws(\InvalidArgumentException::class, fn() => $instance->with([$prop => $inf], ['overflow' => $overflow]), "{$prop} property cannot be {$inf} (overflow {$overflow}");
$calls = [];
Assert::incomplete('TemporalHelpers.toPrimitiveObserver() is not yet implemented');
}
}
}
