<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/with/invalid-disambiguation.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$zdt = new \Temporal\Spec\ZonedDateTime(0, 'UTC');
foreach (['', 'EARLIER', 'balance'] as $disambiguation) {
Assert::throws(\InvalidArgumentException::class, function () use (&$zdt, &$disambiguation) { return $zdt->with(['day' => 5], ['disambiguation' => $disambiguation]); }, '');
}
