<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/with/offset-property-invalid-string.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
$instance = new \Temporal\Spec\ZonedDateTime(0, 'UTC');
$offsetOptions = ['use', 'prefer', 'ignore', 'reject'];
$badOffsets = ['00:00', '+0', '-000:00', 0, null, true, 1000];
foreach ($offsetOptions as $offsetOption) {
foreach ($badOffsets as $offset) {
if ($offset === null) { continue; }
Assert::throws((is_string($offset) ? \RangeException::class : \TypeError::class), function () use (&$instance, &$offset, &$offsetOption) { return $instance->with(JsUndefined::strip(['offset' => $offset]), JsUndefined::strip(['offset' => $offsetOption])); }, "\"{$offset} is not a valid offset string (with {$offsetOption} offset option)");
}
}
