<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/with/overflow-wrong-type.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
use Temporal\Tests\Test262\TemporalHelpers;
$datetime = new \Temporal\Spec\ZonedDateTime(1_000_000_000_987_654_321, 'UTC');
Assert::throws(\RangeException::class, function () use (&$datetime) { return $datetime->with((object) ['second' => 41], (object) ['overflow' => null]); }, 'null');
Assert::throws(\RangeException::class, function () use (&$datetime) { return $datetime->with((object) ['second' => 41], (object) ['overflow' => true]); }, 'true');
Assert::throws(\RangeException::class, function () use (&$datetime) { return $datetime->with((object) ['second' => 41], (object) ['overflow' => false]); }, 'false');
Assert::throws(\TypeError::class, function () use (&$datetime) { return $datetime->with((object) ['second' => 41], (object) JsUndefined::strip(['overflow' => \Temporal\Tests\Test262\JsSymbol::singleton()])); }, 'symbol');
Assert::throws(\RangeException::class, function () use (&$datetime) { return $datetime->with((object) ['second' => 41], (object) ['overflow' => 2]); }, 'number');
Assert::throws(\RangeException::class, function () use (&$datetime) { return $datetime->with((object) ['second' => 41], (object) ['overflow' => 2]); }, 'bigint');
Assert::throws(\RangeException::class, function () use (&$datetime) { return $datetime->with((object) ['second' => 41], (object) JsUndefined::strip(['overflow' => (object) []])); }, 'plain object');
$expected = ['get overflow.toString', 'call overflow.toString'];
$actual = [];
$observer = TemporalHelpers::toPrimitiveObserver($actual, 'constrain', 'overflow');
$result = $datetime->with((object) ['second' => 41], (object) JsUndefined::strip(['overflow' => $observer]));
Assert::sameValue($result->epochNanoseconds, 1_000_000_001_987_654_321, 'object with toString');
// JS-only (observer call-order check, tracker is empty in PHP): assert.compareArray(actual, expected, "order of operations");
