<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/prototype/withCalendar/calendar-invalid-iso-string.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instance = new \Temporal\Spec\PlainDate(1976, 11, 18, 'iso8601');
$invalidStrings = [['', 'empty string'], ['1997-12-04[u-ca=notacal]', 'Unknown calendar']];
foreach ($invalidStrings as $__entry__) {
[$arg, $description] = array_pad($__entry__, 2, null);
Assert::throws(\InvalidArgumentException::class, function () use (&$instance, &$arg) { return $instance->withCalendar($arg); }, "{$description} is not a valid calendar ID");
}
