<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/prototype/withCalendar/calendar-string.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instance = new \Temporal\PlainDate(1976, 11, 18, 'iso8601');
$arg = 'iso8601';
$result = $instance->withCalendar($arg);
Assert::sameValue($result->calendarId, 'iso8601', "Calendar created from string \"{$arg}\"");
