<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/prototype/withCalendar/subclassing-ignored.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
TemporalHelpers::checkSubclassingIgnored(\Temporal\Spec\PlainDate::class, [2000, 5, 2], 'withCalendar', ['iso8601'], function ($result) { TemporalHelpers::assertPlainDate($result, 2000, 5, 'M05', 2); Assert::sameValue($result->calendarId, 'iso8601', 'calendar result'); });
