<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/Duration/prototype/round/relativeto-dst-back-transition.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$origin = \Temporal\Spec\ZonedDateTime::from('2025-11-02T01:00:00-08:00[America/Vancouver]');
$dur = \Temporal\Spec\Duration::from(['hours' => 11, 'minutes' => 30]);
$roundedDur = $dur->round(['largestUnit' => 'days', 'smallestUnit' => 'days', 'relativeTo' => $origin, 'roundingMode' => 'halfExpand']);
TemporalHelpers::assertDuration($roundedDur, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'relativeTo in fall-back DST transition, second wallclock time, assumed 24 hour span when +1 day');
$origin = \Temporal\Spec\ZonedDateTime::from('2025-11-02T01:00:00-08:00[America/Vancouver]');
$dur = \Temporal\Spec\Duration::from(['hours' => -12, 'minutes' => -30]);
$roundedDur = $dur->round(['largestUnit' => 'days', 'smallestUnit' => 'days', 'relativeTo' => $origin, 'roundingMode' => 'halfExpand']);
TemporalHelpers::assertDuration($roundedDur, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 'relativeTo in fall-back DST transition, second wallclock time, assumed 25 hour span when -1 day');
TemporalHelpers::assertDuration(\Temporal\Spec\Duration::from(['minutes' => -59])->round(['smallestUnit' => 'days', 'relativeTo' => '2025-11-02T01:00:00-08:00[America/Vancouver]']), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'negative delta from relativeTo, positive wallclock delta');
TemporalHelpers::assertDuration(\Temporal\Spec\Duration::from(['minutes' => -59])->round(['smallestUnit' => 'days', 'relativeTo' => '2025-11-02T01:00:00-08:00[America/Vancouver]', 'roundingMode' => 'expand']), 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 'negative delta from relativeTo, positive wallclock delta, expanding');
TemporalHelpers::assertDuration(\Temporal\Spec\Duration::from(['minutes' => 59])->round(['smallestUnit' => 'days', 'relativeTo' => '2025-11-02T01:01:00-07:00[America/Vancouver]']), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'positive delta from relativeTo, negative wallclock delta');
TemporalHelpers::assertDuration(\Temporal\Spec\Duration::from(['minutes' => 59])->round(['smallestUnit' => 'days', 'relativeTo' => '2025-11-02T01:01:00-07:00[America/Vancouver]', 'roundingMode' => 'expand']), 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 'positive delta from relativeTo, negative wallclock delta, expanding');
