<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/Duration/prototype/round/rounding-increment-relativeto.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
use Temporal\Tests\Test262\TemporalHelpers;
$relativeTo = \Temporal\Spec\ZonedDateTime::from('2025-03-09T03:00:00-07:00[America/Vancouver]');
TemporalHelpers::assertDuration(new \Temporal\Spec\Duration(0, 1, 0, 30)->round(JsUndefined::strip(['smallestUnit' => 'months', 'roundingIncrement' => 2, 'relativeTo' => $relativeTo])), 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, "1m30d to 2m with relativeTo 2025-03-09T03:00:00-07:00[America/Vancouver]");
