<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/subtract/argument-not-object.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instance = new \Temporal\PlainYearMonth(2000, 5);
Assert::throws(\TypeError::class, fn() => $instance->subtract(), 'undefined');
Assert::throws(\TypeError::class, fn() => $instance->subtract(null), 'null');
Assert::throws(\TypeError::class, fn() => $instance->subtract(true), 'boolean');
Assert::throws(\InvalidArgumentException::class, fn() => $instance->subtract(''), 'empty string');
Assert::incomplete('untranslatable: Symbol()');
