<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/subtract/argument-string.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$instance = \Temporal\Spec\PlainYearMonth::from(['year' => 2000, 'month' => 5]);
$result = $instance->subtract('P3M');
TemporalHelpers::assertPlainYearMonth($result, 2000, 2, 'M02');
