<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/subtract/overflow-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$yearmonth = new \Temporal\Spec\PlainYearMonth(2000, 5);
$duration = new \Temporal\Spec\Duration(1, 1);
$explicit = $yearmonth->subtract($duration, []);
TemporalHelpers::assertPlainYearMonth($explicit, 1999, 4, 'M04', 'default overflow is constrain');
$implicit = $yearmonth->subtract($duration, new \stdClass());
TemporalHelpers::assertPlainYearMonth($implicit, 1999, 4, 'M04', 'default overflow is constrain');
$lambda = $yearmonth->subtract($duration, function () {  });
TemporalHelpers::assertPlainYearMonth($lambda, 1999, 4, 'M04', 'default overflow is constrain');
