<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/subtract/subclassing-ignored.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
TemporalHelpers::checkSubclassingIgnored(\Temporal\Spec\PlainYearMonth::class, [2000, 5], 'subtract', [['months' => 1]], fn($result) => TemporalHelpers::assertPlainYearMonth($result, 2000, 4, 'M04'));
