<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/ZonedDateTime/prototype/with/chinese-calendar-dates.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$calendar = 'chinese';
$cases = ['year2000' => ['year' => 1999, 'month' => 11, 'monthCode' => 'M11', 'day' => 25, 'timeZone' => 'UTC', 'calendar' => $calendar], 'year1900' => ['year' => 1899, 'month' => 12, 'monthCode' => 'M12', 'day' => 1, 'timeZone' => 'UTC', 'calendar' => $calendar], 'year2100' => ['year' => 2099, 'month' => 11, 'day' => 21, 'timeZone' => 'UTC', 'calendar' => $calendar]];
foreach ($cases as $name => $result) {
$inCal = \Temporal\Spec\ZonedDateTime::from($result);
$afterWithDay = $inCal->with(['day' => 1]);
TemporalHelpers::assertPlainDateTime($afterWithDay->toPlainDateTime(), $inCal->year, $inCal->month, $inCal->monthCode, 1, 0, 0, 0, 0, 0, 0, "{$name} (after setting day)");
$afterWithMonth = $afterWithDay->with(['month' => 1]);
TemporalHelpers::assertPlainDateTime($afterWithMonth->toPlainDateTime(), $inCal->year, 1, 'M01', 1, 0, 0, 0, 0, 0, 0, "{$name} (after setting month)");
$afterWithYear = $afterWithMonth->with(['year' => 2025]);
TemporalHelpers::assertPlainDateTime($afterWithYear->toPlainDateTime(), 2025, 1, 'M01', 1, 0, 0, 0, 0, 0, 0, "{$name} (after setting year)");
}
