<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/ZonedDateTime/prototype/with/leap-year-buddhist.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$calendar = 'buddhist';
$options = ['overflow' => 'reject'];
$leapDay = \Temporal\Spec\ZonedDateTime::from(['year' => 2559, 'monthCode' => 'M02', 'day' => 29, 'hour' => 12, 'minute' => 34, 'timeZone' => 'UTC', 'calendar' => $calendar], $options);
TemporalHelpers::assertPlainDateTime($leapDay->with(['year' => 2555], $options)->toPlainDateTime(), 2555, 2, 'M02', 29, 12, 34, 0, 0, 0, 0, 'day not constrained when moving to another leap year', 'be', 2555);
TemporalHelpers::assertPlainDateTime($leapDay->with(['year' => 2561])->toPlainDateTime(), 2561, 2, 'M02', 28, 12, 34, 0, 0, 0, 0, 'day constrained when moving to a common year', 'be', 2561);
Assert::throws(\InvalidArgumentException::class, function () use (&$leapDay, &$options) { $leapDay->with(['year' => 2561], $options); }, 'reject when moving to a common year');
