<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/ZonedDateTime/prototype/with/non-iso-calendar-fields.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instance = new \Temporal\Spec\ZonedDateTime(1_000_000_000_000_000_000, 'UTC', 'hebrew');
$resultYear = $instance->with(['year' => 5762]);
Assert::sameValue($resultYear->year, 5762, 'year is changed');
Assert::sameValue($resultYear->month, 12, 'month is not changed');
Assert::sameValue($resultYear->monthCode, 'M12', 'month code is not changed');
Assert::sameValue($resultYear->day, 21, 'day is not changed');
$resultMonth = $instance->with(['month' => 11]);
Assert::sameValue($resultMonth->year, 5761, 'year is not changed');
Assert::sameValue($resultMonth->month, 11, 'month is changed');
Assert::sameValue($resultMonth->monthCode, 'M11', 'month code is changed');
Assert::sameValue($resultMonth->day, 21, 'day is not changed');
$resultMonthCode = $instance->with(['monthCode' => 'M11']);
Assert::sameValue($resultMonthCode->year, 5761, 'year is not changed');
Assert::sameValue($resultMonthCode->month, 11, 'month is changed');
Assert::sameValue($resultMonthCode->monthCode, 'M11', 'month code is changed');
Assert::sameValue($resultMonthCode->day, 21, 'day is not changed');
$resultDay = $instance->with(['day' => 24]);
Assert::sameValue($resultDay->year, 5761, 'year is not changed');
Assert::sameValue($resultDay->month, 12, 'month is not changed');
Assert::sameValue($resultDay->monthCode, 'M12', 'month code is not changed');
Assert::sameValue($resultDay->day, 24, 'day is changed');
