<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/ZonedDateTime/prototype/subtract/era-boundary-islamic-umalqura.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$duration1 = new \Temporal\Spec\Duration(-1);
$duration1n = new \Temporal\Spec\Duration(1);
$calendar = 'islamic-umalqura';
$options = ['overflow' => 'reject'];
$date1 = \Temporal\Spec\ZonedDateTime::from(['era' => 'bh', 'eraYear' => 2, 'monthCode' => 'M06', 'day' => 15, 'hour' => 12, 'minute' => 34, 'timeZone' => 'UTC', 'calendar' => $calendar], $options);
TemporalHelpers::assertPlainDateTime($date1->subtract($duration1)->toPlainDateTime(), 0, 6, 'M06', 15, 12, 34, 0, 0, 0, 0, 'Adding 1 year to 2 BH lands in 1 BH (counts backwards)', 'bh', 1);
$date2 = \Temporal\Spec\ZonedDateTime::from(['era' => 'bh', 'eraYear' => 1, 'monthCode' => 'M06', 'day' => 15, 'hour' => 12, 'minute' => 34, 'timeZone' => 'UTC', 'calendar' => $calendar], $options);
TemporalHelpers::assertPlainDateTime($date2->subtract($duration1)->toPlainDateTime(), 1, 6, 'M06', 15, 12, 34, 0, 0, 0, 0, 'Adding 1 year to 1 BH lands in 1 AH (no year zero)', 'ah', 1);
$date3 = \Temporal\Spec\ZonedDateTime::from(['era' => 'ah', 'eraYear' => 1, 'monthCode' => 'M06', 'day' => 15, 'hour' => 12, 'minute' => 34, 'timeZone' => 'UTC', 'calendar' => $calendar], $options);
TemporalHelpers::assertPlainDateTime($date3->subtract($duration1)->toPlainDateTime(), 2, 6, 'M06', 15, 12, 34, 0, 0, 0, 0, 'Adding 1 year to 1 AH lands in 2 AH', 'ah', 2);
$date4 = \Temporal\Spec\ZonedDateTime::from(['era' => 'bh', 'eraYear' => 5, 'monthCode' => 'M03', 'day' => 1, 'hour' => 12, 'minute' => 34, 'timeZone' => 'UTC', 'calendar' => $calendar], $options);
TemporalHelpers::assertPlainDateTime($date4->subtract(new \Temporal\Spec\Duration(-10))->toPlainDateTime(), 6, 3, 'M03', 1, 12, 34, 0, 0, 0, 0, 'Adding 10 years to 5 BH lands in 6 AH (no year zero)', 'ah', 6);
$date5 = \Temporal\Spec\ZonedDateTime::from(['era' => 'ah', 'eraYear' => 2, 'monthCode' => 'M06', 'day' => 15, 'hour' => 12, 'minute' => 34, 'timeZone' => 'UTC', 'calendar' => $calendar], $options);
TemporalHelpers::assertPlainDateTime($date5->subtract($duration1n)->toPlainDateTime(), 1, 6, 'M06', 15, 12, 34, 0, 0, 0, 0, 'Subtracting 1 year from 2 AH lands in 1 AH', 'ah', 1);
TemporalHelpers::assertPlainDateTime($date3->subtract($duration1n)->toPlainDateTime(), 0, 6, 'M06', 15, 12, 34, 0, 0, 0, 0, 'Subtracting 1 year from 1 AH lands in 1 BH', 'bh', 1);
TemporalHelpers::assertPlainDateTime($date2->subtract($duration1n)->toPlainDateTime(), -1, 6, 'M06', 15, 12, 34, 0, 0, 0, 0, 'Subtracting 1 year from 1 BH lands in 2 BH', 'bh', 2);
$date6 = \Temporal\Spec\ZonedDateTime::from(['era' => 'ah', 'eraYear' => 5, 'monthCode' => 'M03', 'day' => 1, 'hour' => 12, 'minute' => 34, 'timeZone' => 'UTC', 'calendar' => $calendar], $options);
TemporalHelpers::assertPlainDateTime($date6->subtract(new \Temporal\Spec\Duration(10))->toPlainDateTime(), -5, 3, 'M03', 1, 12, 34, 0, 0, 0, 0, 'Subtracting 10 years from 5 AH lands in 6 BH', 'bh', 6);
