<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/prototype/toZonedDateTime/argument-string-with-utc-designator.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
$invalidStrings = ['2019-10-01T09:00:00Z', '2019-10-01T09:00:00Z[UTC]', '09:00:00Z[UTC]', '09:00:00Z'];
$instance = new \Temporal\Spec\PlainDate(2000, 5, 2);
foreach ($invalidStrings as $arg) {
Assert::throws(\InvalidArgumentException::class, function () use (&$instance, &$arg) { return $instance->toZonedDateTime((object) JsUndefined::strip(['plainTime' => $arg, 'timeZone' => 'UTC'])); }, 'String with UTC designator should not be valid as a PlainTime');
}
