<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/prototype/toZonedDateTime/argument-number.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instance = new \Temporal\Spec\PlainDate(2000, 5, 2);
$numbers = [1, -123_456.987_654_321, 1_234_567, 123_456.9_876_543_219];
foreach ($numbers as $arg) {
Assert::throws(\TypeError::class, function () use (&$instance, &$arg) { return $instance->toZonedDateTime(['plainTime' => $arg, 'timeZone' => 'UTC']); }, "A number ({$arg}) is not a valid ISO string for PlainTime");
}
