<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/prototype/toZonedDateTime/timezone-case-insensitive.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instance = new \Temporal\Spec\PlainDate(2000, 5, 2);
$timeZone = 'uTc';
$result = $instance->toZonedDateTime($timeZone);
Assert::sameValue($result->timeZoneId, 'UTC', "Time zone created from string \"{$timeZone}\"");
