<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/ZonedDateTime/prototype/equals/argument-object.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instance = new \Temporal\Spec\ZonedDateTime(0, 'UTC');
$namesIANA = ['Asia/Calcutta', 'Asia/Kolkata', 'ASIA/calcutta', 'Asia/KOLKATA'];
foreach ($namesIANA as $id1) {
foreach ($namesIANA as $id2) {
Assert::assertTrue($instance->withTimeZone($id1)->equals($instance->withTimeZone($id2)), "Receiver {$id1} should equal argument {$id2}");
}
}
$namesIANADifferentCanonical = ['Asia/Colombo', 'ASIA/colombo'];
foreach ($namesIANADifferentCanonical as $id1) {
foreach ($namesIANA as $id2) {
Assert::assertTrue(!$instance->withTimeZone($id1)->equals($instance->withTimeZone($id2)), "Receiver {$id1} should not equal argument {$id2}");
Assert::assertTrue(!$instance->withTimeZone($id2)->equals($instance->withTimeZone($id1)), "Receiver {$id2} should not equal argument {$id1}");
}
}
