<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainDate/prototype/until/intercalary-month-ethioaa.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$calendar = 'ethioaa';
$options = ['overflow' => 'reject'];
$commonM12 = \Temporal\Spec\PlainDate::from(['year' => 7514, 'monthCode' => 'M12', 'day' => 1, 'calendar' => $calendar], $options);
$commonLast = \Temporal\Spec\PlainDate::from(['year' => 7514, 'monthCode' => 'M13', 'day' => 5, 'calendar' => $calendar], $options);
$leapFirst = \Temporal\Spec\PlainDate::from(['year' => 7515, 'monthCode' => 'M01', 'day' => 1, 'calendar' => $calendar], $options);
$leapM12 = \Temporal\Spec\PlainDate::from(['year' => 7515, 'monthCode' => 'M12', 'day' => 1, 'calendar' => $calendar], $options);
$leapPenultimate = \Temporal\Spec\PlainDate::from(['year' => 7515, 'monthCode' => 'M13', 'day' => 5, 'calendar' => $calendar], $options);
$leapLast = \Temporal\Spec\PlainDate::from(['year' => 7515, 'monthCode' => 'M13', 'day' => 6, 'calendar' => $calendar], $options);
$common2First = \Temporal\Spec\PlainDate::from(['year' => 7516, 'monthCode' => 'M01', 'day' => 1, 'calendar' => $calendar], $options);
$common2Last = \Temporal\Spec\PlainDate::from(['year' => 7516, 'monthCode' => 'M13', 'day' => 5, 'calendar' => $calendar], $options);
$tests = [[$commonLast, $leapLast, 'last day of common year to last day of leap year', ['years', 1, 0, 0, 1], ['months', 0, 13, 0, 1], ['weeks', 0, 0, 52, 2], ['days', 0, 0, 0, 366]], [$commonLast, $leapPenultimate, 'last day of common year to penultimate day of leap year', ['years', 1, 0, 0, 0], ['months', 0, 13, 0, 0], ['weeks', 0, 0, 52, 1], ['days', 0, 0, 0, 365]], [$leapLast, $common2Last, 'last day of leap year to last day of common year', ['years', 0, 12, 0, 29], ['months', 0, 12, 0, 29], ['weeks', 0, 0, 52, 1], ['days', 0, 0, 0, 365]], [$commonM12, $leapFirst, '2mo passing through intercalary month in common year', ['years', 0, 2, 0, 0], ['months', 0, 2, 0, 0], ['weeks', 0, 0, 5, 0], ['days', 0, 0, 0, 35]], [$leapM12, $common2First, '2mo passing through intercalary month in leap year', ['years', 0, 2, 0, 0], ['months', 0, 2, 0, 0], ['weeks', 0, 0, 5, 1], ['days', 0, 0, 0, 36]], [$common2Last, $leapLast, 'backwards last day of common year to last day of leap year', ['years', 0, -12, 0, -5], ['months', 0, -12, 0, -5], ['weeks', 0, 0, -52, -1], ['days', 0, 0, 0, -365]], [$common2Last, $leapPenultimate, 'backwards last day of common year to penultimate day of leap year', ['years', -1, 0, 0, 0], ['months', 0, -13, 0, 0], ['weeks', 0, 0, -52, -2], ['days', 0, 0, 0, -366]], [$leapLast, $commonLast, 'backwards last day of leap year to last day of common year', ['years', -1, 0, 0, 0], ['months', 0, -13, 0, 0], ['weeks', 0, 0, -52, -2], ['days', 0, 0, 0, -366]], [$leapFirst, $commonM12, 'backwards 2mo passing through intercalary month in common year', ['years', 0, -2, 0, 0], ['months', 0, -2, 0, 0], ['weeks', 0, 0, -5, 0], ['days', 0, 0, 0, -35]], [$common2First, $leapM12, 'backwards 2mo passing through intercalary month in leap year', ['years', 0, -2, 0, 0], ['months', 0, -2, 0, 0], ['weeks', 0, 0, -5, -1], ['days', 0, 0, 0, -36]]];
foreach ($tests as $__entry_units__) {
[$one, $two, $descr] = array_pad($__entry_units__, 3, null);
$units = array_slice($__entry_units__, 3);
foreach ($units as $__entry__) {
[$largestUnit, $years, $months, $weeks, $days] = array_pad($__entry__, 5, null);
TemporalHelpers::assertDuration($one->until($two, ['largestUnit' => $largestUnit]), $years, $months, $weeks, $days, 0, 0, 0, 0, 0, 0, $descr + " (largest unit {$largestUnit})");
}
}
