<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/yearOfWeek/basic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$nsPerDay = 864 * (10 ** 11);
$zdt = new \Temporal\ZonedDateTime(0, 'UTC');
Assert::sameValue($zdt->yearOfWeek, 1970, '');
$zdt = new \Temporal\ZonedDateTime(-3 * $nsPerDay, 'UTC');
Assert::sameValue($zdt->yearOfWeek, 1970, '');
$zdt = new \Temporal\ZonedDateTime(-4 * $nsPerDay, 'UTC');
Assert::sameValue($zdt->yearOfWeek, 1969, '');
$zdt = new \Temporal\ZonedDateTime(367 * $nsPerDay, 'UTC');
Assert::sameValue($zdt->yearOfWeek, 1970, '');
$zdt = new \Temporal\ZonedDateTime(368 * $nsPerDay, 'UTC');
Assert::sameValue($zdt->yearOfWeek, 1971, '');
