<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/compare/argument-string-time-separators.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$plainTime = new \Temporal\Spec\PlainTime(12, 34, 56, 987, 654, 321);
$tests = [['1976-11-18T12:34:56.987654321', 'uppercase T'], ['1976-11-18t12:34:56.987654321', 'lowercase T'], ['1976-11-18 12:34:56.987654321', 'space between date and time'], ['T12:34:56.987654321', 'time-only uppercase T'], ['t12:34:56.987654321', 'time-only lowercase T']];
foreach ($tests as $__entry__) {
[$arg, $description] = array_pad($__entry__, 2, null);
Assert::sameValue(\Temporal\Spec\PlainTime::compare($arg, $plainTime), 0, "variant time separators ({$description}), first argument");
Assert::sameValue(\Temporal\Spec\PlainTime::compare($plainTime, $arg), 0, "variant time separators ({$description}), second argument");
}
