<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/compare/argument-string-no-implicit-midnight.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$arg = '2019-10-01';
$midnight = new \Temporal\PlainTime();
Assert::throws(\InvalidArgumentException::class, fn() => \Temporal\PlainTime::compare($arg, $midnight), 'Date-only string throws, does not implicitly convert to midnight (first argument)');
Assert::throws(\InvalidArgumentException::class, fn() => \Temporal\PlainTime::compare($midnight, $arg), 'Date-only string throws, does not implicitly convert to midnight (second argument)');
