<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/compare/argument-string-time-designator-required-for-disambiguation.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$midnight = new \Temporal\Spec\PlainTime();
Assert::incomplete('untranslatable: TemporalHelpers chain call');
