<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/compare/prop-desc.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
Assert::sameValue('function', 'function', '`typeof PlainTime.compare` is `function`');
Assert::methodExists('\Temporal\PlainTime', 'compare');
