<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainDate/prototype/daysInMonth/basic-chinese.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$calendar = 'chinese';
$options = ['overflow' => 'reject'];
$sampleYears = [1971 => [29, 30, 29, 29, 30, 29, 30, 29, 30, 30, 30, 29], 1972 => [29, 30, 29, 29, 30, 29, 30, 29, 30, 30, 29, 30]];
foreach ($sampleYears as $year => $daysInMonth) {
for ($month = 1; $month < count($daysInMonth); $month++) {
$date = \Temporal\Spec\PlainDate::from(['year' => $year, 'month' => $month, 'day' => 1, 'calendar' => $calendar]);
Assert::sameValue($date->daysInMonth, $daysInMonth[$month - 1], "{$date}");
}
}
