<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainMonthDay/future-calendar.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
use Temporal\Tests\Test262\TemporalHelpers;
foreach (TemporalHelpers::notYetSupportedCalendars() as $calendar) {
Assert::throws(\RangeException::class, function () use (&$calendar) { new \Temporal\Spec\PlainMonthDay(1, 1, $calendar, 1970); }, "{$calendar} is not yet supported");
}
