<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/prototype/equals/branding.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
Assert::incomplete('\\Temporal\\Spec\\PlainTime::equals used as a value');
