<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/prototype/subtract/argument-string-fractional-units-rounding-mode.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$epoch = new \Temporal\Spec\Instant(0);
Assert::sameValue($epoch->subtract('PT1.03125H')->epochNanoseconds, -3_712_500_000_000, 'positive fractional units rounded with correct rounding mode');
Assert::sameValue($epoch->subtract('-PT1.03125H')->epochNanoseconds, 3_712_500_000_000, 'negative fractional units rounded with correct rounding mode');
