<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/prototype/subtract/argument-invalid-property.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instance = new \Temporal\Spec\Instant(1_000_000_000_000_000_000);
Assert::throws(\TypeError::class, fn() => $instance->subtract(new \stdClass()), 'Throws TypeError if no property is present');
Assert::throws(\TypeError::class, fn() => $instance->subtract(['nonsense' => true]), 'Throws TypeError if no recognized property is present');
Assert::throws(\TypeError::class, fn() => $instance->subtract(['sign' => 1]), 'Sign property is not recognized');
