<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/prototype/subtract/subtract-large-subseconds.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$i1 = new \Temporal\Instant(1_582_966_647_747_612_578);
Assert::sameValue($i1->subtract(\Temporal\Duration::from(['nanoseconds' => 9_007_199_254_740_991]))->epochNanoseconds, 1_573_959_448_492_871_587, '');
Assert::sameValue($i1->subtract(\Temporal\Duration::from(['nanoseconds' => -9_007_199_254_740_991]))->epochNanoseconds, 1_591_973_847_002_353_569, '');
Assert::sameValue($i1->subtract(\Temporal\Duration::from(['microseconds' => 9_007_199_254_740_991]))->epochNanoseconds, -7_424_232_606_993_378_422, '');
// SKIP (int64 overflow): Assert::sameValue($i1->subtract(\Temporal\Duration::from(['microseconds' => -9_007_199_254_740_991]))->epochNanoseconds, 10590165902488603578, ...);
Assert::assertTrue(true);
Assert::throws(\InvalidArgumentException::class, fn() => $i1->subtract(\Temporal\Duration::from(['milliseconds' => 9_007_199_254_740_991])), '');
Assert::throws(\InvalidArgumentException::class, fn() => $i1->subtract(\Temporal\Duration::from(['milliseconds' => -9_007_199_254_740_991])), '');
Assert::throws(\InvalidArgumentException::class, fn() => $i1->subtract(\Temporal\Duration::from(['seconds' => 9_007_199_254_740_991])), '');
Assert::throws(\InvalidArgumentException::class, fn() => $i1->subtract(\Temporal\Duration::from(['seconds' => -9_007_199_254_740_991])), '');
$bigNumber = 9_007_199_254_740_990_976;
Assert::sameValue($i1->subtract(\Temporal\Duration::from(['nanoseconds' => $bigNumber]))->epochNanoseconds, -7_424_232_606_993_378_398, '');
// SKIP (int64 overflow): Assert::sameValue($i1->subtract(\Temporal\Duration::from(['nanoseconds' => -$bigNumber]))->epochNanoseconds, 10590165902488603554, ...);
Assert::assertTrue(true);
Assert::throws(\InvalidArgumentException::class, fn() => $i1->subtract(\Temporal\Duration::from(['microseconds' => $bigNumber])), '');
Assert::throws(\InvalidArgumentException::class, fn() => $i1->subtract(\Temporal\Duration::from(['microseconds' => -$bigNumber])), '');
Assert::throws(\InvalidArgumentException::class, fn() => $i1->subtract(\Temporal\Duration::from(['milliseconds' => $bigNumber])), '');
Assert::throws(\InvalidArgumentException::class, fn() => $i1->subtract(\Temporal\Duration::from(['milliseconds' => -$bigNumber])), '');
$i2 = new \Temporal\Instant(0);
Assert::sameValue($i2->subtract(\Temporal\Duration::from(['nanoseconds' => $bigNumber]))->epochNanoseconds, -9_007_199_254_740_990_976, '');
Assert::sameValue($i2->subtract(\Temporal\Duration::from(['nanoseconds' => -$bigNumber]))->epochNanoseconds, 9_007_199_254_740_990_976, '');
Assert::throws(\InvalidArgumentException::class, fn() => $i2->subtract(\Temporal\Duration::from(['microseconds' => $bigNumber])), '');
Assert::throws(\InvalidArgumentException::class, fn() => $i2->subtract(\Temporal\Duration::from(['microseconds' => -$bigNumber])), '');
Assert::throws(\InvalidArgumentException::class, fn() => $i2->subtract(\Temporal\Duration::from(['milliseconds' => $bigNumber])), '');
Assert::throws(\InvalidArgumentException::class, fn() => $i2->subtract(\Temporal\Duration::from(['milliseconds' => -$bigNumber])), '');
