<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/compare/basic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$td1pos = new \Temporal\Duration(0, 0, 0, 0, 5, 5, 5, 5, 5, 5);
$td2pos = new \Temporal\Duration(0, 0, 0, 0, 5, 4, 5, 5, 5, 5);
$td1neg = new \Temporal\Duration(0, 0, 0, 0, -5, -5, -5, -5, -5, -5);
$td2neg = new \Temporal\Duration(0, 0, 0, 0, -5, -4, -5, -5, -5, -5);
Assert::sameValue(\Temporal\Duration::compare($td1pos, $td1pos), 0, 'time units: equal');
Assert::sameValue(\Temporal\Duration::compare($td2pos, $td1pos), -1, 'time units: smaller/larger');
Assert::sameValue(\Temporal\Duration::compare($td1pos, $td2pos), 1, 'time units: larger/smaller');
Assert::sameValue(\Temporal\Duration::compare($td1neg, $td1neg), 0, 'time units: negative/negative equal');
Assert::sameValue(\Temporal\Duration::compare($td2neg, $td1neg), 1, 'time units: negative/negative smaller/larger');
Assert::sameValue(\Temporal\Duration::compare($td1neg, $td2neg), -1, 'time units: negative/negative larger/smaller');
Assert::sameValue(\Temporal\Duration::compare($td1neg, $td2pos), -1, 'time units: negative/positive');
Assert::sameValue(\Temporal\Duration::compare($td1pos, $td2neg), 1, 'time units: positive/negative');
$dd1pos = new \Temporal\Duration(5, 5, 5, 5, 5, 5, 5, 5, 5, 5);
$dd2pos = new \Temporal\Duration(5, 5, 5, 5, 5, 4, 5, 5, 5, 5);
$dd1neg = new \Temporal\Duration(-5, -5, -5, -5, -5, -5, -5, -5, -5, -5);
$dd2neg = new \Temporal\Duration(-5, -5, -5, -5, -5, -4, -5, -5, -5, -5);
Assert::incomplete('\\Temporal\\PlainDate::from() is not yet implemented');
