<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/compare/blank-duration.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$blank1 = new \Temporal\Duration();
$blank2 = new \Temporal\Duration();
$compare = [\Temporal\Duration::class, 'compare'];
$plainRelativeTo = new \Temporal\PlainDate(2025, 8, 22);
Assert::incomplete('\\Temporal\\ZonedDateTime is not yet implemented');
