<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/compare/blank-duration.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$blank1 = new \Temporal\Duration();
$blank2 = new \Temporal\Duration();
$compare = [\Temporal\Duration::class, 'compare'];
$plainRelativeTo = new \Temporal\PlainDate(2025, 8, 22);
$zonedRelativeTo = new \Temporal\ZonedDateTime(1, 'UTC');
Assert::sameValue($compare($blank1, $blank2), 0, 'zero durations compared without relativeTo');
Assert::sameValue($compare($blank1, $blank2, ['relativeTo' => $plainRelativeTo]), 0, 'zero durations compared with PlainDate relativeTo');
Assert::sameValue($compare($blank1, $blank2, ['relativeTo' => $zonedRelativeTo]), 0, 'zero durations compared with ZonedDateTime relativeTo');
