<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/compare/options-object.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
Assert::sameValue(\Temporal\Duration::compare(['hours' => 1], ['minutes' => 60], new \stdClass()), 0, 'options may be an empty plain object');
Assert::sameValue(\Temporal\Duration::compare(['hours' => 1], ['minutes' => 60], function () {  }), 0, 'options may be an empty function object');
