<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/compare/options-read-before-algorithmic-validation.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
use Temporal\Tests\Test262\TemporalHelpers;
$expected = ['get options.relativeTo'];
$actual = [];
$options = TemporalHelpers::propertyBagObserver($actual, [], 'options');
$d1 = new \Temporal\Spec\Duration(0, 0, 0, 1);
$d2 = new \Temporal\Spec\Duration(1);
Assert::throws(\RangeException::class, function () use (&$d1, &$d2, &$options) { \Temporal\Spec\Duration::compare($d1, $d2, $options); }, 'exception thrown when calendar units provided without relativeTo');
// JS-only (observer call-order check, tracker is empty in PHP): assert.compareArray(actual, expected, "all options should be read first");
