<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/compare/order-of-operations.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$expected = ['get one.days', 'get one.days.valueOf', 'call one.days.valueOf', 'get one.hours', 'get one.hours.valueOf', 'call one.hours.valueOf', 'get one.microseconds', 'get one.microseconds.valueOf', 'call one.microseconds.valueOf', 'get one.milliseconds', 'get one.milliseconds.valueOf', 'call one.milliseconds.valueOf', 'get one.minutes', 'get one.minutes.valueOf', 'call one.minutes.valueOf', 'get one.months', 'get one.months.valueOf', 'call one.months.valueOf', 'get one.nanoseconds', 'get one.nanoseconds.valueOf', 'call one.nanoseconds.valueOf', 'get one.seconds', 'get one.seconds.valueOf', 'call one.seconds.valueOf', 'get one.weeks', 'get one.weeks.valueOf', 'call one.weeks.valueOf', 'get one.years', 'get one.years.valueOf', 'call one.years.valueOf', 'get two.days', 'get two.days.valueOf', 'call two.days.valueOf', 'get two.hours', 'get two.hours.valueOf', 'call two.hours.valueOf', 'get two.microseconds', 'get two.microseconds.valueOf', 'call two.microseconds.valueOf', 'get two.milliseconds', 'get two.milliseconds.valueOf', 'call two.milliseconds.valueOf', 'get two.minutes', 'get two.minutes.valueOf', 'call two.minutes.valueOf', 'get two.months', 'get two.months.valueOf', 'call two.months.valueOf', 'get two.nanoseconds', 'get two.nanoseconds.valueOf', 'call two.nanoseconds.valueOf', 'get two.seconds', 'get two.seconds.valueOf', 'call two.seconds.valueOf', 'get two.weeks', 'get two.weeks.valueOf', 'call two.weeks.valueOf', 'get two.years', 'get two.years.valueOf', 'call two.years.valueOf', 'get options.relativeTo'];
$actual = [];
\Temporal\Duration::compare($createDurationPropertyBagObserver('one', 0, 0, 0, 7), $createDurationPropertyBagObserver('two', 0, 0, 0, 6), $createOptionsObserver(null));
Assert::compareArray($actual, $expected, 'order of operations');
$actual->splice(0);
Assert::incomplete('untranslatable: Array.prototype.concat()');
