<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/compare/relativeto-sub-minute-offset.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$duration1 = new \Temporal\Duration(0, 0, 0, 31);
$duration2 = new \Temporal\Duration(0, 1);
$action = fn($relativeTo) => \Temporal\Duration::compare($duration1, $duration2, ['relativeTo' => $relativeTo]);
$relativeTo = '1970-01-01T00:00-00:45:00[-00:45]';
$result = $action($relativeTo);
Assert::sameValue($result, 0, 'ISO string offset accepted with zero seconds (string)');
$relativeTo = ['year' => 1970, 'month' => 1, 'day' => 1, 'offset' => '+00:45:00.000000000', 'timeZone' => '+00:45'];
$result = $action($relativeTo);
Assert::sameValue($result, 0, 'ISO string offset accepted with zero seconds (property bag)');
$relativeTo = '1970-01-01T00:00+00:44:30.123456789[+00:45]';
Assert::throws(\InvalidArgumentException::class, fn() => $action($relativeTo), 'rounding is not accepted between ISO offset and time zone');
$relativeTo = '1970-01-01T00:00-00:44:59[-00:44:59]';
Assert::throws(\InvalidArgumentException::class, fn() => $action($relativeTo), 'sub-minute offset not accepted as time zone identifier');
