<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/compare/relativeto-argument-string-calendar-invalid-iso-string.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instance_1 = new \Temporal\Duration(1);
$instance_2 = new \Temporal\Duration(2);
$invalidStrings = [['', 'empty string'], ['1997-12-04[u-ca=notacal]', 'Unknown calendar']];
foreach ($invalidStrings as [$arg, $description]) {
Assert::incomplete('\\Temporal\\Duration::compare() is not yet implemented');
}
