<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/compare/relativeto-propertybag-timezone-string.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
foreach (['UTC', '+01:00'] as $timeZone) {
\Temporal\Duration::compare(new \Temporal\Duration(1), new \Temporal\Duration(), ['relativeTo' => ['year' => 2000, 'month' => 5, 'day' => 2, 'timeZone' => $timeZone]]);
}
