<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/compare/throws-when-target-zoned-date-time-outside-valid-limits.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;

$blank = new \Temporal\Duration(0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
$oneDay = new \Temporal\Duration(0, 0, 0, 1);
Assert::incomplete('\\Temporal\\ZonedDateTime is not yet implemented');
