<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/subtract/order-of-operations.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$expectedOpsForPrimitiveOptions = ['get duration.days', 'get duration.days.valueOf', 'call duration.days.valueOf', 'get duration.hours', 'get duration.hours.valueOf', 'call duration.hours.valueOf', 'get duration.microseconds', 'get duration.microseconds.valueOf', 'call duration.microseconds.valueOf', 'get duration.milliseconds', 'get duration.milliseconds.valueOf', 'call duration.milliseconds.valueOf', 'get duration.minutes', 'get duration.minutes.valueOf', 'call duration.minutes.valueOf', 'get duration.months', 'get duration.months.valueOf', 'call duration.months.valueOf', 'get duration.nanoseconds', 'get duration.nanoseconds.valueOf', 'call duration.nanoseconds.valueOf', 'get duration.seconds', 'get duration.seconds.valueOf', 'call duration.seconds.valueOf', 'get duration.weeks', 'get duration.weeks.valueOf', 'call duration.weeks.valueOf', 'get duration.years', 'get duration.years.valueOf', 'call duration.years.valueOf'];
$expected = array_merge($expectedOpsForPrimitiveOptions, ['get options.overflow', 'get options.overflow.toString', 'call options.overflow.toString']);
$actual = [];
$instance = new \Temporal\Spec\ZonedDateTime(0, 'UTC', 'iso8601');
$duration = TemporalHelpers::propertyBagObserver($actual, (object) ['years' => 1, 'months' => 1, 'weeks' => 1, 'days' => 1, 'hours' => 1, 'minutes' => 1, 'seconds' => 1, 'milliseconds' => 1, 'microseconds' => 1, 'nanoseconds' => 1], 'duration');
$options = TemporalHelpers::propertyBagObserver($actual, (object) ['overflow' => 'constrain'], 'options');
$instance->subtract($duration, $options);
// JS-only (observer call-order check, tracker is empty in PHP): assert.compareArray(actual, expected, "order of operations");
// JS-only (observer tracker reset (no-op in PHP)): actual.splice(0);
// JS-only (JS rejects non-object options via ToObject; PHP accepts null as "absent"): assert.throws(TypeError, () => instance.subtract(duration, null));
// JS-only (observer call-order check, tracker is empty in PHP): assert.compareArray(actual, expectedOpsForPrimitiveOptions, "duration fields are read before TypeError is thrown for primitive options");
// JS-only (observer tracker reset (no-op in PHP)): actual.splice(0);
\PHPUnit\Framework\Assert::assertTrue(true, 'Script completed without throwing');
