<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/subtract/overflow-wrong-type.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$datetime = new \Temporal\ZonedDateTime(1_000_000_000_987_654_321, 'UTC');
$duration = new \Temporal\Duration(0, 0, 0, 1);
TemporalHelpers::checkStringOptionWrongType('overflow', 'constrain', fn($overflow) => $datetime->subtract($duration, ['overflow' => $overflow]), fn($result, $descr) => Assert::sameValue($result->epochNanoseconds, 999_913_600_987_654_321, $descr));
