<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/compare/argument-propertybag-calendar-iso-string.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
foreach (['2020-01-01', '2020-01-01[u-ca=iso8601]', '2020-01-01T00:00:00.000000000', '2020-01-01T00:00:00.000000000[u-ca=iso8601]', '01-01', '01-01[u-ca=iso8601]', '2020-01', '2020-01[u-ca=iso8601]'] as $calendar) {
$arg = ['year' => 2019, 'monthCode' => 'M06', 'calendar' => $calendar];
$result1 = \Temporal\PlainYearMonth::compare($arg, new \Temporal\PlainYearMonth(2019, 6));
Assert::sameValue($result1, 0, "Calendar created from string \"{$calendar}\" (first argument)");
$result2 = \Temporal\PlainYearMonth::compare(new \Temporal\PlainYearMonth(2019, 6), $arg);
Assert::sameValue($result2, 0, "Calendar created from string \"{$calendar}\" (second argument)");
}
