<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/prototype/until/largestunit-smallestunit-mismatch.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$earlier = new \Temporal\PlainTime(12, 34, 56, 0, 0, 0);
$later = new \Temporal\PlainTime(13, 35, 57, 987, 654, 321);
$units = ['hours', 'minutes', 'seconds', 'milliseconds', 'microseconds', 'nanoseconds'];
for ($largestIdx = 1; $largestIdx < count($units); $largestIdx++) {
for ($smallestIdx = 0; $smallestIdx < $largestIdx; $smallestIdx++) {
$largestUnit = $units[$largestIdx];
$smallestUnit = $units[$smallestIdx];
Assert::throws(\InvalidArgumentException::class, fn() => $earlier->until($later, ['largestUnit' => $largestUnit, 'smallestUnit' => $smallestUnit]), '');
}
}
