<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/prototype/until/options-object.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$instance = new \Temporal\Spec\PlainTime();
$result1 = $instance->until(new \Temporal\Spec\PlainTime(12, 34, 56), new \stdClass());
TemporalHelpers::assertDuration($result1, 0, 0, 0, 0, 12, 34, 56, 0, 0, 0, 'options may be an empty plain object');
$result2 = $instance->until(new \Temporal\Spec\PlainTime(12, 34, 56), function () {  });
TemporalHelpers::assertDuration($result2, 0, 0, 0, 0, 12, 34, 56, 0, 0, 0, 'options may be a function object');
