<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/prototype/until/order-of-operations.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
use Temporal\Tests\Test262\TemporalHelpers;
$expectedOpsForPrimitiveOptions = ['get other.hour', 'get other.hour.valueOf', 'call other.hour.valueOf', 'get other.microsecond', 'get other.microsecond.valueOf', 'call other.microsecond.valueOf', 'get other.millisecond', 'get other.millisecond.valueOf', 'call other.millisecond.valueOf', 'get other.minute', 'get other.minute.valueOf', 'call other.minute.valueOf', 'get other.nanosecond', 'get other.nanosecond.valueOf', 'call other.nanosecond.valueOf', 'get other.second', 'get other.second.valueOf', 'call other.second.valueOf'];
$expected = array_merge($expectedOpsForPrimitiveOptions, ['get options.largestUnit', 'get options.largestUnit.toString', 'call options.largestUnit.toString', 'get options.roundingIncrement', 'get options.roundingIncrement.valueOf', 'call options.roundingIncrement.valueOf', 'get options.roundingMode', 'get options.roundingMode.toString', 'call options.roundingMode.toString', 'get options.smallestUnit', 'get options.smallestUnit.toString', 'call options.smallestUnit.toString']);
$actual = [];
$instance = new \Temporal\Spec\PlainTime(12, 34, 56, 987, 654, 321);
$other = TemporalHelpers::propertyBagObserver($actual, ['hour' => 1.7, 'minute' => 1.7, 'second' => 1.7, 'millisecond' => 1.7, 'microsecond' => 1.7, 'nanosecond' => 1.7, 'calendar' => 'iso8601'], 'other', ['calendar']);
$options = TemporalHelpers::propertyBagObserver($actual, ['roundingIncrement' => 1, 'roundingMode' => 'trunc', 'largestUnit' => 'hours', 'smallestUnit' => 'nanoseconds', 'additional' => true], 'options');
$result = $instance->until($other, $options);
// JS-only (observer call-order check, tracker is empty in PHP): assert.compareArray(actual, expected, "order of operations");
// JS-only (observer tracker reset (no-op in PHP)): actual.splice(0);
$identicalPropertyBag = TemporalHelpers::propertyBagObserver($actual, ['hour' => 12, 'minute' => 34, 'second' => 56, 'millisecond' => 987, 'microsecond' => 654, 'nanosecond' => 321], 'other');
$instance->until($identicalPropertyBag, $options);
// JS-only (observer call-order check, tracker is empty in PHP): assert.compareArray(actual, expected, "order of operations with identical times");
// JS-only (observer tracker reset (no-op in PHP)): actual.splice(0);
// JS-only (JS rejects non-object options via ToObject; PHP accepts null as "absent"): assert.throws(TypeError, () => instance.until(other, null));
// JS-only (observer call-order check, tracker is empty in PHP): assert.compareArray(actual, expectedOpsForPrimitiveOptions, "other time fields are read before TypeError is thrown for primitive options");
// JS-only (observer tracker reset (no-op in PHP)): actual.splice(0);
\PHPUnit\Framework\Assert::assertTrue(true, 'Script completed without throwing');
