<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/prototype/until/roundingmode-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$earlier = \Temporal\Spec\PlainTime::from('08:22:36.123456789');
$later = \Temporal\Spec\PlainTime::from('12:39:40.987654321');
TemporalHelpers::assertDuration($earlier->until($later, ['smallestUnit' => 'hours']), 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 'hours');
TemporalHelpers::assertDuration($earlier->until($later, ['smallestUnit' => 'hours']), 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 'hours');
TemporalHelpers::assertDuration($later->until($earlier, ['smallestUnit' => 'hours']), 0, 0, 0, 0, -4, 0, 0, 0, 0, 0, 'hours');
TemporalHelpers::assertDuration($later->until($earlier, ['smallestUnit' => 'hours']), 0, 0, 0, 0, -4, 0, 0, 0, 0, 0, 'hours');
TemporalHelpers::assertDuration($earlier->until($later, ['smallestUnit' => 'minutes']), 0, 0, 0, 0, 4, 17, 0, 0, 0, 0, 'minutes');
TemporalHelpers::assertDuration($earlier->until($later, ['smallestUnit' => 'minutes']), 0, 0, 0, 0, 4, 17, 0, 0, 0, 0, 'minutes');
TemporalHelpers::assertDuration($later->until($earlier, ['smallestUnit' => 'minutes']), 0, 0, 0, 0, -4, -17, 0, 0, 0, 0, 'minutes');
TemporalHelpers::assertDuration($later->until($earlier, ['smallestUnit' => 'minutes']), 0, 0, 0, 0, -4, -17, 0, 0, 0, 0, 'minutes');
TemporalHelpers::assertDuration($earlier->until($later, ['smallestUnit' => 'seconds']), 0, 0, 0, 0, 4, 17, 4, 0, 0, 0, 'seconds');
TemporalHelpers::assertDuration($earlier->until($later, ['smallestUnit' => 'seconds']), 0, 0, 0, 0, 4, 17, 4, 0, 0, 0, 'seconds');
TemporalHelpers::assertDuration($later->until($earlier, ['smallestUnit' => 'seconds']), 0, 0, 0, 0, -4, -17, -4, 0, 0, 0, 'seconds');
TemporalHelpers::assertDuration($later->until($earlier, ['smallestUnit' => 'seconds']), 0, 0, 0, 0, -4, -17, -4, 0, 0, 0, 'seconds');
TemporalHelpers::assertDuration($earlier->until($later, ['smallestUnit' => 'milliseconds']), 0, 0, 0, 0, 4, 17, 4, 864, 0, 0, 'milliseconds');
TemporalHelpers::assertDuration($earlier->until($later, ['smallestUnit' => 'milliseconds']), 0, 0, 0, 0, 4, 17, 4, 864, 0, 0, 'milliseconds');
TemporalHelpers::assertDuration($later->until($earlier, ['smallestUnit' => 'milliseconds']), 0, 0, 0, 0, -4, -17, -4, -864, 0, 0, 'milliseconds');
TemporalHelpers::assertDuration($later->until($earlier, ['smallestUnit' => 'milliseconds']), 0, 0, 0, 0, -4, -17, -4, -864, 0, 0, 'milliseconds');
TemporalHelpers::assertDuration($earlier->until($later, ['smallestUnit' => 'microseconds']), 0, 0, 0, 0, 4, 17, 4, 864, 197, 0, 'microseconds');
TemporalHelpers::assertDuration($earlier->until($later, ['smallestUnit' => 'microseconds']), 0, 0, 0, 0, 4, 17, 4, 864, 197, 0, 'microseconds');
TemporalHelpers::assertDuration($later->until($earlier, ['smallestUnit' => 'microseconds']), 0, 0, 0, 0, -4, -17, -4, -864, -197, 0, 'microseconds');
TemporalHelpers::assertDuration($later->until($earlier, ['smallestUnit' => 'microseconds']), 0, 0, 0, 0, -4, -17, -4, -864, -197, 0, 'microseconds');
TemporalHelpers::assertDuration($earlier->until($later, ['smallestUnit' => 'nanoseconds']), 0, 0, 0, 0, 4, 17, 4, 864, 197, 532, 'nanoseconds');
TemporalHelpers::assertDuration($earlier->until($later, ['smallestUnit' => 'nanoseconds']), 0, 0, 0, 0, 4, 17, 4, 864, 197, 532, 'nanoseconds');
TemporalHelpers::assertDuration($later->until($earlier, ['smallestUnit' => 'nanoseconds']), 0, 0, 0, 0, -4, -17, -4, -864, -197, -532, 'nanoseconds');
TemporalHelpers::assertDuration($later->until($earlier, ['smallestUnit' => 'nanoseconds']), 0, 0, 0, 0, -4, -17, -4, -864, -197, -532, 'nanoseconds');
