<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainYearMonth/prototype/daysInMonth/basic-japanese.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
$calendar = 'japanese';
$options = (object) ['overflow' => 'reject'];
$sampleYears = (object) JsUndefined::strip([1972 => [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31], 1973 => [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]]);
foreach ($sampleYears as $year => $daysInMonth) {
for ($month = 1; $month < (is_string($daysInMonth) ? strlen($daysInMonth) : count($daysInMonth)); $month++) {
$date = \Temporal\Spec\PlainYearMonth::from((object) JsUndefined::strip(['year' => $year, 'month' => $month, 'calendar' => $calendar]));
Assert::sameValue($date->daysInMonth, $daysInMonth[$month - 1], "{$date}");
}
}
