<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/prototype/add/argument-string-fractional-units-rounding-mode.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$epoch = new \Temporal\Instant(0);
Assert::incomplete('Instant::add() is not yet implemented');
