<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/withPlainTime/argument-object-insufficient-data.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$dt = new \Temporal\Spec\PlainDateTime(2015, 12, 7, 3, 24, 30, 0, 3, 500);
Assert::throws(\TypeError::class, fn() => $dt->withPlainTime(new \stdClass()), 'empty object not an acceptable argument');
TemporalHelpers::assertPlainDateTime($dt->withPlainTime(['hour' => 10]), 2015, 12, 'M12', 7, 10, 0, 0, 0, 0, 0, 'plain object (hour) works');
Assert::throws(\TypeError::class, fn() => $dt->withPlainTime(['hours' => 9]), 'plain object with a single unrecognized property fails');
TemporalHelpers::assertPlainDateTime($dt->withPlainTime(['hour' => 10, 'seconds' => 123]), 2015, 12, 'M12', 7, 10, 0, 0, 0, 0, 0, 'unrecognized properties are ignored if at least one recognized property is present');
