<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/withCalendar/calendar-case-insensitive.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instance = new \Temporal\Spec\ZonedDateTime(1_000_000_000_000_000_000, 'UTC', 'iso8601');
$arg = 'iSo8601';
$result = $instance->withCalendar($arg);
Assert::sameValue($result->calendarId, 'iso8601', 'Calendar is case-insensitive');
$arg = 'İSO8601';
Assert::throws(\InvalidArgumentException::class, fn() => $instance->withCalendar($arg), 'calendar ID is ASCII-lowercased, capital dotted I is not lowercased');
