<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/equals/argument-string-sub-minute-offset.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instance = new \Temporal\Spec\ZonedDateTime(0, 'UTC');
$str = '2021-08-19T17:30:45.123456789-12:12:59.9[-12:12:59.9]';
Assert::throws(\InvalidArgumentException::class, fn() => $instance->equals($str), "{$str} is not a valid ISO string");
