<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/equals/casts-argument.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instance = new \Temporal\ZonedDateTime(0, 'UTC', 'iso8601');
Assert::assertTrue($instance->equals('1970-01-01T00:00+00:00[UTC][u-ca=iso8601]'), '');
Assert::assertTrue($instance->equals(['year' => 1970, 'month' => 1, 'day' => 1, 'timeZone' => 'UTC', 'calendar' => 'iso8601']), '');
