<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/subtract/argument-propertybag-optional-properties.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$instance = new \Temporal\Spec\Duration();
$oneProperty = ['hours' => 1];
$allProperties = ['years' => 0, 'months' => 0, 'weeks' => 0, 'days' => 0, 'hours' => 1, 'minutes' => 0, 'seconds' => 0, 'milliseconds' => 0, 'microseconds' => 0, 'nanoseconds' => 0];
$resultWithout = $instance->subtract($oneProperty);
$resultWith = $instance->subtract($allProperties);
TemporalHelpers::assertDurationsEqual($resultWithout, $resultWith, 'results should be the same with and without optional properties');
