<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/subtract/argument-singular-properties.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instance = new \Temporal\Spec\Duration(0, 0, 0, 1, 2, 3, 4, 987, 654, 321);
foreach ([['year' => 1], ['month' => 2], ['week' => 3], ['day' => 4], ['hour' => 5], ['minute' => 6], ['second' => 7], ['millisecond' => 8], ['microsecond' => 9], ['nanosecond' => 10]] as $badObject) {
Assert::throws(\TypeError::class, fn() => $instance->subtract($badObject), 'Throw TypeError if temporalDurationLike is not valid');
}
