<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/subtract/order-of-operations.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$expected = ['get fields.days', 'get fields.days.valueOf', 'call fields.days.valueOf', 'get fields.hours', 'get fields.hours.valueOf', 'call fields.hours.valueOf', 'get fields.microseconds', 'get fields.microseconds.valueOf', 'call fields.microseconds.valueOf', 'get fields.milliseconds', 'get fields.milliseconds.valueOf', 'call fields.milliseconds.valueOf', 'get fields.minutes', 'get fields.minutes.valueOf', 'call fields.minutes.valueOf', 'get fields.months', 'get fields.months.valueOf', 'call fields.months.valueOf', 'get fields.nanoseconds', 'get fields.nanoseconds.valueOf', 'call fields.nanoseconds.valueOf', 'get fields.seconds', 'get fields.seconds.valueOf', 'call fields.seconds.valueOf', 'get fields.weeks', 'get fields.weeks.valueOf', 'call fields.weeks.valueOf', 'get fields.years', 'get fields.years.valueOf', 'call fields.years.valueOf'];
$actual = [];
$fields = TemporalHelpers::propertyBagObserver($actual, (object) ['years' => 0, 'months' => 0, 'weeks' => 0, 'days' => 1, 'hours' => 1, 'minutes' => 1, 'seconds' => 1, 'milliseconds' => 1, 'microseconds' => 1, 'nanoseconds' => 1], 'fields');
$instance = new \Temporal\Spec\Duration(0, 0, 0, 1, 1, 1, 1, 1, 1, 1);
$instance->subtract($fields);
// JS-only (observer call-order check, tracker is empty in PHP): assert.compareArray(actual, expected, "order of operations");
// JS-only (observer tracker reset (no-op in PHP)): actual.splice(0);
\PHPUnit\Framework\Assert::assertTrue(true, 'Script completed without throwing');
