<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/with/blank-duration.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$blank = new \Temporal\Spec\Duration();
foreach ([-1, 0, 1] as $val) {
$result = $blank->with((object) ['years' => $val]);
TemporalHelpers::assertDuration($result, $val, 0, 0, 0, 0, 0, 0, 0, 0, 0, "with years {$val}");
$result = $blank->with((object) ['months' => $val]);
TemporalHelpers::assertDuration($result, 0, $val, 0, 0, 0, 0, 0, 0, 0, 0, "with months {$val}");
$result = $blank->with((object) ['weeks' => $val]);
TemporalHelpers::assertDuration($result, 0, 0, $val, 0, 0, 0, 0, 0, 0, 0, "with weeks {$val}");
$result = $blank->with((object) ['days' => $val]);
TemporalHelpers::assertDuration($result, 0, 0, 0, $val, 0, 0, 0, 0, 0, 0, "with days {$val}");
$result = $blank->with((object) ['hours' => $val]);
TemporalHelpers::assertDuration($result, 0, 0, 0, 0, $val, 0, 0, 0, 0, 0, "with hours {$val}");
$result = $blank->with((object) ['minutes' => $val]);
TemporalHelpers::assertDuration($result, 0, 0, 0, 0, 0, $val, 0, 0, 0, 0, "with minutes {$val}");
$result = $blank->with((object) ['seconds' => $val]);
TemporalHelpers::assertDuration($result, 0, 0, 0, 0, 0, 0, $val, 0, 0, 0, "with seconds {$val}");
$result = $blank->with((object) ['milliseconds' => $val]);
TemporalHelpers::assertDuration($result, 0, 0, 0, 0, 0, 0, 0, $val, 0, 0, "with milliseconds {$val}");
$result = $blank->with((object) ['microseconds' => $val]);
TemporalHelpers::assertDuration($result, 0, 0, 0, 0, 0, 0, 0, 0, $val, 0, "with microseconds {$val}");
$result = $blank->with((object) ['nanoseconds' => $val]);
TemporalHelpers::assertDuration($result, 0, 0, 0, 0, 0, 0, 0, 0, 0, $val, "with nanoseconds {$val}");
}
