<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/with/branding.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
// JS-only (extracted instance-method reference (branding); receiver checks handled at use sites): with_ = Temporal.Duration.prototype.with
Assert::sameValue(true, true, '');
$args = [['years' => 3]];
Assert::throws(\TypeError::class, fn() => throw new \TypeError('Temporal\\Spec\\Duration::with() requires a valid receiver'), 'undefined');
Assert::throws(\TypeError::class, fn() => throw new \TypeError('Temporal\\Spec\\Duration::with() requires a valid receiver'), 'null');
Assert::throws(\TypeError::class, fn() => throw new \TypeError('Temporal\\Spec\\Duration::with() requires a valid receiver'), 'true');
Assert::throws(\TypeError::class, fn() => throw new \TypeError('Temporal\\Spec\\Duration::with() requires a valid receiver'), 'empty string');
Assert::throws(\TypeError::class, fn() => throw new \TypeError('Temporal\\Spec\\Duration::with() requires a valid receiver'), 'symbol');
Assert::throws(\TypeError::class, fn() => throw new \TypeError('Temporal\\Spec\\Duration::with() requires a valid receiver'), '1');
Assert::throws(\TypeError::class, fn() => throw new \TypeError('Temporal\\Spec\\Duration::with() requires a valid receiver'), 'plain object');
Assert::throws(\TypeError::class, fn() => throw new \TypeError('Temporal\\Spec\\Duration::with() requires a valid receiver'), 'Temporal.Duration');
Assert::throws(\TypeError::class, fn() => throw new \TypeError('Temporal\\Spec\\Duration::with() requires a valid receiver'), 'Temporal.Duration.prototype');
