<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/prototype/with/copy-properties-not-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$plainDate = new \Temporal\Spec\PlainDate(2006, 1, 24);
TemporalHelpers::assertPlainDate($plainDate->with(['day' => 1]), 2006, 1, 'M01', 1, 'only the properties that are present and defined in the plain object are copied');
