<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/microseconds/basic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instance = new \Temporal\Duration(1, 2, 3, 4, 5, 6, 7, 8, 9, 10);
Assert::sameValue($instance->microseconds, 9, '');
$negInstance = new \Temporal\Duration(-1, -2, -3, -4, -5, -6, -7, -8, -9, -10);
Assert::sameValue($negInstance->microseconds, -9, '');
