<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/toZonedDateTime/order-of-operations.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$expected = ['get options.disambiguation', 'get options.disambiguation.toString', 'call options.disambiguation.toString'];
$actual = [];
$instance = new \Temporal\Spec\PlainDateTime(2000, 5, 2, 12, 34, 56, 987, 654, 321, 'iso8601');
Assert::incomplete('TemporalHelpers.propertyBagObserver() is not yet implemented');
