<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/toPlainDate/argument-not-object.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
foreach ([null, JsUndefined::singleton(), true, 3.1_416, 'a string', \Temporal\Tests\Test262\JsSymbol::singleton(), 7] as $primitive) {
$plainYearMonth = new \Temporal\Spec\PlainYearMonth(2000, 5);
Assert::throws(\TypeError::class, function () use (&$plainYearMonth, &$primitive) { return $plainYearMonth->toPlainDate($primitive); }, '');
}
