<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainDate/prototype/with/basic-hebrew.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$calendar = 'hebrew';
$cases = ['year2000' => ['year' => 5760, 'eraYear' => 5760, 'era' => 'am', 'month' => 4, 'monthCode' => 'M04', 'day' => 23, 'calendar' => $calendar], 'year1' => ['year' => 3761, 'eraYear' => 3761, 'era' => 'am', 'month' => 4, 'monthCode' => 'M04', 'day' => 18, 'calendar' => $calendar]];
foreach ($cases as $name => $result) {
$inCal = \Temporal\Spec\PlainDate::from($result);
$afterWithDay = $inCal->with(['day' => 1]);
TemporalHelpers::assertPlainDate($afterWithDay, $inCal->year, $inCal->month, $inCal->monthCode, 1, "{$name} after setting day", $inCal->era, $inCal->eraYear);
$afterWithMonth = $afterWithDay->with(['month' => 1]);
TemporalHelpers::assertPlainDate($afterWithMonth, $inCal->year, 1, 'M01', 1, "{$name} after setting month", $inCal->era, $inCal->eraYear);
$afterWithYear = $afterWithMonth->with(['year' => 5860]);
TemporalHelpers::assertPlainDate($afterWithYear, 5860, 1, 'M01', 1, "{$name} after setting year", $inCal->era, 5860);
}
