<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainDate/prototype/with/basic-islamic-umalqura.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$calendar = 'islamic-umalqura';
$cases = ['year2000' => ['year' => 1420, 'eraYear' => 1420, 'era' => 'ah', 'month' => 9, 'monthCode' => 'M09', 'day' => 24, 'calendar' => $calendar], 'year1' => ['year' => -640, 'eraYear' => 641, 'era' => 'bh', 'month' => 5, 'monthCode' => 'M05', 'day' => 18, 'calendar' => $calendar]];
foreach ($cases as $name => $result) {
$inCal = \Temporal\Spec\PlainDate::from($result);
$afterWithDay = $inCal->with(['day' => 1]);
TemporalHelpers::assertPlainDate($afterWithDay, $inCal->year, $inCal->month, $inCal->monthCode, 1, "{$name} after setting day", $inCal->era, $inCal->eraYear);
$afterWithMonth = $afterWithDay->with(['month' => 1]);
TemporalHelpers::assertPlainDate($afterWithMonth, $inCal->year, 1, 'M01', 1, "{$name} after setting month", $inCal->era, $inCal->eraYear);
$afterWithYear = $afterWithMonth->with(['year' => 1700]);
TemporalHelpers::assertPlainDate($afterWithYear, 1700, 1, 'M01', 1, "{$name} after setting year", 'ah', 1700);
}
