<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainDate/prototype/with/basic-coptic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$calendar = 'coptic';
$cases = ['year2000' => ['era' => 'am', 'eraYear' => 1716, 'year' => 1716, 'month' => 4, 'monthCode' => 'M04', 'day' => 22, 'calendar' => $calendar], 'year1' => ['era' => 'am', 'eraYear' => -283, 'year' => -283, 'month' => 5, 'monthCode' => 'M05', 'day' => 8, 'calendar' => $calendar]];
foreach ($cases as $name => $result) {
$inCal = \Temporal\Spec\PlainDate::from($result);
$afterWithDay = $inCal->with(['day' => 1]);
TemporalHelpers::assertPlainDate($afterWithDay, $inCal->year, $inCal->month, $inCal->monthCode, 1, "{$name} after setting day", $inCal->era, $inCal->eraYear);
$afterWithMonth = $afterWithDay->with(['month' => 1]);
TemporalHelpers::assertPlainDate($afterWithMonth, $inCal->year, 1, 'M01', 1, "{$name} after setting month", $inCal->era, $inCal->eraYear);
$afterWithYear = $afterWithMonth->with(['year' => 1917]);
TemporalHelpers::assertPlainDate($afterWithYear, 1917, 1, 'M01', 1, "{$name} after setting year", $inCal->era, 1917);
}
