<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainDate/prototype/with/leap-months-hebrew.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$calendar = 'hebrew';
$options = ['overflow' => 'reject'];
$leapMonth = \Temporal\Spec\PlainDate::from(['year' => 5784, 'monthCode' => 'M05L', 'day' => 1, 'calendar' => $calendar], $options);
TemporalHelpers::assertPlainDate($leapMonth->with(['year' => 5782], $options), 5782, 6, 'M05L', 1, 'month not constrained when moving to another leap year', 'am', 5782);
TemporalHelpers::assertPlainDate($leapMonth->with(['year' => 5783]), 5783, 6, 'M06', 1, 'month constrained when moving to a common year', 'am', 5783);
Assert::throws(\InvalidArgumentException::class, function () use (&$leapMonth, &$options) { $leapMonth->with(['year' => 5783], $options); }, 'reject when moving to a common year');
