<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainDate/prototype/with/mutually-exclusive-fields-coptic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$options = ['overflow' => 'reject'];
$instance = \Temporal\Spec\PlainDate::from(['year' => 1742, 'monthCode' => 'M12', 'day' => 15, 'calendar' => 'coptic'], $options);
TemporalHelpers::assertPlainDate($instance, 1742, 12, 'M12', 15, 'check that all fields are as expected', 'am', 1742);
TemporalHelpers::assertPlainDate($instance->with(['era' => 'am', 'eraYear' => 1740], $options), 1740, 12, 'M12', 15, 'era and eraYear together exclude year', 'am', 1740);
TemporalHelpers::assertPlainDate($instance->with(['year' => 1735], $options), 1735, 12, 'M12', 15, 'year excludes era and eraYear', 'am', 1735);
TemporalHelpers::assertPlainDate($instance->with(['month' => 5], $options), 1742, 5, 'M05', 15, 'month excludes monthCode', 'am', 1742);
TemporalHelpers::assertPlainDate($instance->with(['monthCode' => 'M05'], $options), 1742, 5, 'M05', 15, 'monthCode excludes month', 'am', 1742);
Assert::throws(\TypeError::class, function () use (&$instance) { return $instance->with(['eraYear' => 1741]); }, 'eraYear excludes year and era, and cannot be provided without era');
Assert::throws(\TypeError::class, function () use (&$instance) { return $instance->with(['era' => 'am']); }, 'era excludes year and eraYear, and cannot be provided without eraYear');
