<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainDate/prototype/with/mutually-exclusive-fields-persian.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$options = ['overflow' => 'reject'];
$instance = \Temporal\Spec\PlainDate::from(['year' => 1404, 'monthCode' => 'M12', 'day' => 15, 'calendar' => 'persian'], $options);
TemporalHelpers::assertPlainDate($instance, 1404, 12, 'M12', 15, 'check that all fields are as expected', 'ap', 1404);
TemporalHelpers::assertPlainDate($instance->with(['era' => 'ap', 'eraYear' => 1400], $options), 1400, 12, 'M12', 15, 'era and eraYear together exclude year', 'ap', 1400);
TemporalHelpers::assertPlainDate($instance->with(['year' => 1402], $options), 1402, 12, 'M12', 15, 'year excludes era and eraYear', 'ap', 1402);
TemporalHelpers::assertPlainDate($instance->with(['month' => 5], $options), 1404, 5, 'M05', 15, 'month excludes monthCode', 'ap', 1404);
TemporalHelpers::assertPlainDate($instance->with(['monthCode' => 'M05'], $options), 1404, 5, 'M05', 15, 'monthCode excludes month', 'ap', 1404);
Assert::throws(\TypeError::class, fn() => $instance->with(['eraYear' => 1403]), 'eraYear excludes year and era, and cannot be provided without era');
Assert::throws(\TypeError::class, fn() => $instance->with(['era' => 'ap']), 'era excludes year and eraYear, and cannot be provided without eraYear');
