<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainDate/prototype/with/mutually-exclusive-fields-buddhist.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$options = ['overflow' => 'reject'];
$instance = \Temporal\Spec\PlainDate::from(['year' => 2566, 'monthCode' => 'M12', 'day' => 15, 'calendar' => 'buddhist'], $options);
TemporalHelpers::assertPlainDate($instance, 2566, 12, 'M12', 15, 'check that all fields are as expected', 'be', 2566);
TemporalHelpers::assertPlainDate($instance->with(['era' => 'be', 'eraYear' => 2560], $options), 2560, 12, 'M12', 15, 'era and eraYear together exclude year', 'be', 2560);
TemporalHelpers::assertPlainDate($instance->with(['year' => 2559], $options), 2559, 12, 'M12', 15, 'year excludes era and eraYear', 'be', 2559);
TemporalHelpers::assertPlainDate($instance->with(['month' => 5], $options), 2566, 5, 'M05', 15, 'month excludes monthCode', 'be', 2566);
TemporalHelpers::assertPlainDate($instance->with(['monthCode' => 'M05'], $options), 2566, 5, 'M05', 15, 'monthCode excludes month', 'be', 2566);
Assert::throws(\TypeError::class, fn() => $instance->with(['eraYear' => 2560]), 'eraYear excludes year and era, and cannot be provided without era');
Assert::throws(\TypeError::class, fn() => $instance->with(['era' => 'be']), 'era excludes year and eraYear, and cannot be provided without eraYear');
