<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/prototype/until/argument-string-time-separators.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$tests = [['1970-01-01T00:00Z', 'uppercase T'], ['1970-01-01t00:00Z', 'lowercase T'], ['1970-01-01 00:00Z', 'space between date and time']];
$instance = new \Temporal\Instant(0);
foreach ($tests as [$arg, $description]) {
$result = $instance->until($arg);
TemporalHelpers::assertDuration($result, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "variant time separators ({$description})");
}
