<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/prototype/until/smallestunit-plurals-accepted.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;

$earlier = new \Temporal\Instant(1_000_000_000_987_654_321);
$later = new \Temporal\Instant(1_086_403_661_988_655_322);
$validUnits = ['hour', 'minute', 'second', 'millisecond', 'microsecond', 'nanosecond'];
Assert::incomplete('TemporalHelpers.checkPluralUnitsAccepted() is not yet implemented');
