<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/toString/calendarname-always.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$date = new \Temporal\Spec\PlainDateTime(1976, 11, 18, 15, 23, 0, 0, 0, 0);
$result = $date->toString(['calendarName' => 'always']);
Assert::sameValue($result, '1976-11-18T15:23:00[u-ca=iso8601]', "built-in ISO calendar for calendarName = always");
