<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/toString/fractionalseconddigits-nan.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$datetime = new \Temporal\Spec\PlainDateTime(2000, 5, 2, 12, 34, 56, 987, 650, 0);
Assert::throws(\InvalidArgumentException::class, function () use (&$datetime) { return $datetime->toString(['fractionalSecondDigits' => NAN]); }, '');
