<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/toString/fractionalseconddigits-auto.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$tests = [[new \Temporal\Spec\PlainDateTime(1976, 2, 4, 5, 3, 1), '1976-02-04T05:03:01'], [new \Temporal\Spec\PlainDateTime(1976, 11, 18, 15, 23), '1976-11-18T15:23:00'], [new \Temporal\Spec\PlainDateTime(1976, 11, 18, 15, 23, 30), '1976-11-18T15:23:30'], [new \Temporal\Spec\PlainDateTime(1976, 11, 18, 15, 23, 30, 123, 400), '1976-11-18T15:23:30.1234']];
foreach ($tests as $__entry__) {
[$datetime, $expected] = array_pad($__entry__, 2, null);
Assert::sameValue($datetime->toString(), $expected, 'default is to emit seconds and drop trailing zeroes');
Assert::sameValue($datetime->toString(['fractionalSecondDigits' => 'auto']), $expected, 'auto is the default');
}
