<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/toString/rounding-edge-of-range.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$start = new \Temporal\Spec\PlainDateTime(-271_821, 4, 19, 0, 0, 0, 1);
Assert::throws(\InvalidArgumentException::class, function () use (&$start) { return $start->toString(['smallestUnit' => 'second']); }, 'Rounding down can go out of range');
$end = new \Temporal\Spec\PlainDateTime(275_760, 9, 13, 23, 59, 59, 999);
Assert::throws(\InvalidArgumentException::class, function () use (&$end) { return $end->toString(['smallestUnit' => 'second', 'roundingMode' => 'halfExpand']); }, 'Rounding up can go out of range');
