<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/toString/roundingmode-halfFloor.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$datetime = new \Temporal\Spec\PlainDateTime(2000, 5, 2, 12, 34, 56, 123, 987, 500);
$result1 = $datetime->toString(['smallestUnit' => 'microsecond', 'roundingMode' => 'halfFloor']);
Assert::sameValue($result1, '2000-05-02T12:34:56.123987', 'roundingMode is halfFloor (with 6 digits from smallestUnit)');
$result2 = $datetime->toString(['fractionalSecondDigits' => 6, 'roundingMode' => 'halfFloor']);
Assert::sameValue($result2, '2000-05-02T12:34:56.123987', 'roundingMode is halfFloor (with 6 digits from fractionalSecondDigits)');
$result3 = $datetime->toString(['smallestUnit' => 'millisecond', 'roundingMode' => 'halfFloor']);
Assert::sameValue($result3, '2000-05-02T12:34:56.124', 'roundingMode is halfFloor (with 3 digits from smallestUnit)');
$result4 = $datetime->toString(['fractionalSecondDigits' => 3, 'roundingMode' => 'halfFloor']);
Assert::sameValue($result4, '2000-05-02T12:34:56.124', 'roundingMode is halfFloor (with 3 digits from fractionalSecondDigits)');
$result5 = $datetime->toString(['smallestUnit' => 'second', 'roundingMode' => 'halfFloor']);
Assert::sameValue($result5, '2000-05-02T12:34:56', 'roundingMode is halfFloor (with 0 digits from smallestUnit)');
$result6 = $datetime->toString(['fractionalSecondDigits' => 0, 'roundingMode' => 'halfFloor']);
Assert::sameValue($result6, '2000-05-02T12:34:56', 'roundingMode is halfFloor (with 0 digits from fractionalSecondDigits)');
$result7 = $datetime->toString(['smallestUnit' => 'minute', 'roundingMode' => 'halfFloor']);
Assert::sameValue($result7, '2000-05-02T12:35', 'roundingMode is halfFloor (round to minute)');
