<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/toString/rounding-direction.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instance = new \Temporal\Spec\PlainDateTime(-99, 12, 15, 12, 0, 0, 500);
Assert::sameValue($instance->toString(['smallestUnit' => 'second', 'roundingMode' => 'floor']), '-000099-12-15T12:00:00', 'Rounding down is towards the Big Bang, not the epoch or 1 BCE');
Assert::sameValue($instance->toString(['smallestUnit' => 'second', 'roundingMode' => 'trunc']), '-000099-12-15T12:00:00', 'Rounding down is towards the Big Bang, not the epoch or 1 BCE (roundingMode trunc)');
Assert::sameValue($instance->toString(['smallestUnit' => 'second', 'roundingMode' => 'ceil']), '-000099-12-15T12:00:01', 'Rounding up is away from the Big Bang, not the epoch or 1 BCE (roundingMode ceil)');
Assert::sameValue($instance->toString(['smallestUnit' => 'second', 'roundingMode' => 'halfExpand']), '-000099-12-15T12:00:01', 'Rounding up is away from the Big Bang, not the epoch or 1 BCE (roundingMode halfExpand)');
