<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/toString/rounding-cross-midnight.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$plainDateTime = new \Temporal\PlainDateTime(1999, 12, 31, 23, 59, 59, 999, 999, 999);
foreach (['ceil', 'halfExpand'] as $roundingMode) {
Assert::sameValue($plainDateTime->toString(['fractionalSecondDigits' => 8, 'roundingMode' => $roundingMode]), '2000-01-01T00:00:00.00000000', '');
}
