<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/toString/smallestunit-fractionalseconddigits.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$datetime = new \Temporal\Spec\PlainDateTime(1976, 11, 18, 12, 34, 56, 789, 999, 999);
$tests = [['minute', '1976-11-18T12:34'], ['second', '1976-11-18T12:34:56'], ['millisecond', '1976-11-18T12:34:56.789'], ['microsecond', '1976-11-18T12:34:56.789999'], ['nanosecond', '1976-11-18T12:34:56.789999999']];
foreach ($tests as $__entry__) {
[$smallestUnit, $expected] = array_pad($__entry__, 2, null);
$string = $datetime->toString(['smallestUnit' => $smallestUnit, 'fractionalSecondDigits' => 5]);
Assert::sameValue($string, $expected, "smallestUnit: \"{$smallestUnit}\" overrides fractionalSecondDigits");
}
Assert::throws(\InvalidArgumentException::class, fn() => $datetime->toString(['smallestUnit' => 'hour', 'fractionalSecondDigits' => 5]), 'hour is an invalid smallestUnit but still overrides fractionalSecondDigits');
