<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/inLeapYear/basic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
Assert::sameValue(new \Temporal\Spec\ZonedDateTime(217_178_610_123_456_789, 'UTC')->inLeapYear, true, 'leap year');
Assert::sameValue(new \Temporal\Spec\ZonedDateTime(248_714_610_123_456_789, 'UTC')->inLeapYear, false, 'non-leap year');
Assert::sameValue(new \Temporal\Spec\PlainDateTime(1995, 8, 23, 5, 30, 13)->toZonedDateTime('UTC')->inLeapYear, false, '');
Assert::sameValue(new \Temporal\Spec\PlainDateTime(1996, 8, 23, 5, 30, 13)->toZonedDateTime('UTC')->inLeapYear, true, '');
Assert::sameValue(new \Temporal\Spec\PlainDateTime(1997, 8, 23, 5, 30, 13)->toZonedDateTime('UTC')->inLeapYear, false, '');
Assert::sameValue(new \Temporal\Spec\PlainDateTime(1998, 8, 23, 5, 30, 13)->toZonedDateTime('UTC')->inLeapYear, false, '');
Assert::sameValue(new \Temporal\Spec\PlainDateTime(1999, 8, 23, 5, 30, 13)->toZonedDateTime('UTC')->inLeapYear, false, '');
Assert::sameValue(new \Temporal\Spec\PlainDateTime(2000, 8, 23, 5, 30, 13)->toZonedDateTime('UTC')->inLeapYear, true, '');
Assert::sameValue(new \Temporal\Spec\PlainDateTime(2001, 8, 23, 5, 30, 13)->toZonedDateTime('UTC')->inLeapYear, false, '');
Assert::sameValue(new \Temporal\Spec\PlainDateTime(2002, 8, 23, 5, 30, 13)->toZonedDateTime('UTC')->inLeapYear, false, '');
Assert::sameValue(new \Temporal\Spec\PlainDateTime(2003, 8, 23, 5, 30, 13)->toZonedDateTime('UTC')->inLeapYear, false, '');
Assert::sameValue(new \Temporal\Spec\PlainDateTime(2004, 8, 23, 5, 30, 13)->toZonedDateTime('UTC')->inLeapYear, true, '');
Assert::sameValue(new \Temporal\Spec\PlainDateTime(2005, 8, 23, 5, 30, 13)->toZonedDateTime('UTC')->inLeapYear, false, '');
