<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/round/negative-time.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instance = new \Temporal\ZonedDateTime(-1_000_000_000_000_000_000, 'UTC');
$roundedDown = -1_000_000_800_000_000_000;
$roundedUp = -999_997_200_000_000_000;
Assert::sameValue($instance->round(['smallestUnit' => 'hour', 'roundingIncrement' => 1, 'roundingMode' => 'halfCeil'])->epochNanoseconds, $roundedDown, 'Rounding with halfCeil rounds to the closest hour');
Assert::sameValue($instance->round(['smallestUnit' => 'hour', 'roundingIncrement' => 1, 'roundingMode' => 'halfFloor'])->epochNanoseconds, $roundedDown, 'Rounding with halfFloor rounds to the closest hour');
Assert::sameValue($instance->round(['smallestUnit' => 'hour', 'roundingIncrement' => 1, 'roundingMode' => 'halfExpand'])->epochNanoseconds, $roundedDown, 'Rounding with halfExpand rounds to the closest hour');
Assert::sameValue($instance->round(['smallestUnit' => 'hour', 'roundingIncrement' => 1, 'roundingMode' => 'halfTrunc'])->epochNanoseconds, $roundedDown, 'Rounding with halfTrunc rounds to the closest hour');
Assert::sameValue($instance->round(['smallestUnit' => 'hour', 'roundingIncrement' => 1, 'roundingMode' => 'halfEven'])->epochNanoseconds, $roundedDown, 'Rounding with halfEven rounds to the closest hour');
Assert::sameValue($instance->round(['smallestUnit' => 'hour', 'roundingIncrement' => 1, 'roundingMode' => 'ceil'])->epochNanoseconds, $roundedUp, 'Rounding with ceil rounds to the next hour');
Assert::sameValue($instance->round(['smallestUnit' => 'hour', 'roundingIncrement' => 1, 'roundingMode' => 'floor'])->epochNanoseconds, $roundedDown, 'Rounding with floor rounds to the closest hour');
Assert::sameValue($instance->round(['smallestUnit' => 'hour', 'roundingIncrement' => 1, 'roundingMode' => 'expand'])->epochNanoseconds, $roundedUp, 'Rounding with expand rounds to the next hour');
Assert::sameValue($instance->round(['smallestUnit' => 'hour', 'roundingIncrement' => 1, 'roundingMode' => 'trunc'])->epochNanoseconds, $roundedDown, 'Rounding with trunc rounds to the closest hour');
