<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/round/rounding-is-noop.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instance = new \Temporal\ZonedDateTime(0, 'UTC');
$noopRoundingOperations = [[['smallestUnit' => 'nanoseconds'], 'smallestUnit ns'], [['smallestUnit' => 'nanoseconds', 'roundingIncrement' => 1], 'round to 1 ns']];
foreach ($noopRoundingOperations as $__entry__) {
[$options, $descr] = array_pad($__entry__, 2, null);
$result = $instance->round($options);
Assert::notSameValue($result, $instance, 'rounding result should be a new object');
Assert::sameValue($result->epochNanoseconds, $instance->epochNanoseconds, 'instant should be unchanged');
}
