<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/round/smallestunit-wrong-type.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$datetime = new \Temporal\ZonedDateTime(1_000_000_000_123_987_500, 'UTC');
TemporalHelpers::checkStringOptionWrongType('smallestUnit', 'microsecond', fn($smallestUnit) => $datetime->round(['smallestUnit' => $smallestUnit]), fn($result, $descr) => Assert::sameValue($result->epochNanoseconds, 1_000_000_000_123_988_000, $descr));
