<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/round/throws-without-smallestunit.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$zdt = new \Temporal\Spec\ZonedDateTime(217_175_010_123_456_789, '+01:00');
Assert::throws(\InvalidArgumentException::class, fn() => $zdt->round(new \stdClass()), '');
Assert::throws(\InvalidArgumentException::class, fn() => $zdt->round(['roundingIncrement' => 1, 'roundingMode' => 'ceil']), '');
