<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/toJSON/basic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$tests = [[new \Temporal\Spec\PlainYearMonth(1972, 1), '1972-01'], [new \Temporal\Spec\PlainYearMonth(1972, 12), '1972-12']];
$options = null;
foreach ($tests as $__entry__) {
[$yearMonth, $expected] = array_pad($__entry__, 2, null);
Assert::sameValue($yearMonth->toJSON(), $expected, 'toJSON without argument');
Assert::sameValue($yearMonth->toJSON($options), $expected, 'toJSON with argument');
}
