<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/Instant/prototype/toLocaleString/default-includes-time-not-time-zone-name.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instant = new \Temporal\Spec\Instant(1_735_213_600_321_000_000);
$result = $instant->toLocaleString('en', ['timeZone' => 'UTC']);
Assert::assertTrue(str_contains($result, '2024'), "Instant formatted with no options {$result} should include year");
Assert::assertTrue(str_contains($result, '12') || str_contains($result, 'Dec'), "Instant formatted with no options {$result} should include month");
Assert::assertTrue(str_contains($result, '26'), "Instant formatted with no options {$result} should include day");
Assert::assertTrue(str_contains($result, '11'), "Instant formatted with no options {$result} should include hour");
Assert::assertTrue(str_contains($result, '46'), "Instant formatted with no options {$result} should include minute");
Assert::assertTrue(str_contains($result, '40'), "Instant formatted with no options {$result} should include second");
Assert::assertTrue(!str_contains($result, '321'), "Instant formatted with no options {$result} should not include fractional second digits");
Assert::assertTrue(!str_contains($result, 'UTC') && !str_contains($result, 'Coordinated Universal Time'), "Instant formatted with no options {$result} should not include time zone name");
