<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/Instant/prototype/toLocaleString/era.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instant = new \Temporal\Spec\Instant(0);
$instantResult = $instant->toLocaleString('en', ['era' => 'narrow']);
Assert::incomplete('untranslatable new expression');
