<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/Instant/prototype/toLocaleString/option-timezonename-short.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instant = \Temporal\Spec\Instant::from('1976-11-18T14:23:30Z');
$str = $instant->toLocaleString('en-US', ['timeZone' => 'America/New_York']);
$strWithName = $instant->toLocaleString('en-US', ['timeZone' => 'America/New_York', 'timeZoneName' => 'short']);
Assert::assertTrue(count($str) < count($strWithName), 'expected "' . $str . '" to be shorter than "' . $strWithName . '".');
