<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/epochMilliseconds/basic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$afterEpoch = new \Temporal\Spec\ZonedDateTime(217_175_010_123_456_789, 'UTC');
Assert::sameValue($afterEpoch->epochMilliseconds, 217_175_010_123, 'epochMilliseconds post epoch');
Assert::sameValue((is_int($afterEpoch->epochMilliseconds) || is_float($afterEpoch->epochMilliseconds)), true, 'epochMilliseconds value is a number');
$beforeEpoch = new \Temporal\Spec\ZonedDateTime(-217_175_010_876_543_211, 'UTC');
Assert::sameValue($beforeEpoch->epochMilliseconds, -217_175_010_877, 'epochMilliseconds pre epoch');
Assert::sameValue((is_int($beforeEpoch->epochMilliseconds) || is_float($beforeEpoch->epochMilliseconds)), true, 'epochMilliseconds value is a number');
