<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/prototype/subtract/argument-string.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$date = new \Temporal\PlainDate(2024, 3, 15);
TemporalHelpers::assertPlainDate($date->subtract('P10D'), 2024, 3, 'M03', 5, 'subtract ISO duration string P10D');
TemporalHelpers::assertPlainDate($date->subtract('P1M'), 2024, 2, 'M02', 15, 'subtract ISO duration string P1M');
TemporalHelpers::assertPlainDate($date->subtract('P1Y2M3D'), 2023, 1, 'M01', 12, 'subtract ISO duration string P1Y2M3D');
