<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/prototype/subtract/balance-smaller-units-basic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
use Temporal\Tests\Test262\TemporalHelpers;
$date = new \Temporal\Spec\PlainDate(1976, 11, 18);
TemporalHelpers::assertPlainDate($date->subtract((object) ['hours' => 1]), 1976, 11, 'M11', 18);
TemporalHelpers::assertPlainDate($date->subtract((object) ['minutes' => 1]), 1976, 11, 'M11', 18);
TemporalHelpers::assertPlainDate($date->subtract((object) ['seconds' => 1]), 1976, 11, 'M11', 18);
TemporalHelpers::assertPlainDate($date->subtract((object) ['milliseconds' => 1]), 1976, 11, 'M11', 18);
TemporalHelpers::assertPlainDate($date->subtract((object) ['microseconds' => 1]), 1976, 11, 'M11', 18);
TemporalHelpers::assertPlainDate($date->subtract((object) ['nanoseconds' => 1]), 1976, 11, 'M11', 18);
TemporalHelpers::assertPlainDate($date->subtract((object) ['hours' => 24]), 1976, 11, 'M11', 17);
TemporalHelpers::assertPlainDate($date->subtract((object) ['hours' => 36]), 1976, 11, 'M11', 17);
TemporalHelpers::assertPlainDate($date->subtract((object) ['hours' => 48]), 1976, 11, 'M11', 16);
TemporalHelpers::assertPlainDate($date->subtract((object) ['minutes' => 1440]), 1976, 11, 'M11', 17);
TemporalHelpers::assertPlainDate($date->subtract((object) ['seconds' => 86_400]), 1976, 11, 'M11', 17);
TemporalHelpers::assertPlainDate($date->subtract((object) ['milliseconds' => 86_400_000]), 1976, 11, 'M11', 17);
TemporalHelpers::assertPlainDate($date->subtract((object) ['microseconds' => 86_400_000_000]), 1976, 11, 'M11', 17);
TemporalHelpers::assertPlainDate($date->subtract((object) ['nanoseconds' => 86_400_000_000_000]), 1976, 11, 'M11', 17);
