<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/prototype/subtract/overflow-constrain.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
TemporalHelpers::assertPlainDate(new \Temporal\PlainDate(2021, 3, 31)->subtract(['months' => 1]), 2021, 2, 'M02', 28, 'Mar 31 - 1 month constrained to Feb 28 (non-leap)');
TemporalHelpers::assertPlainDate(new \Temporal\PlainDate(2020, 3, 31)->subtract(['months' => 1]), 2020, 2, 'M02', 29, 'Mar 31 - 1 month constrained to Feb 29 (leap)');
