<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/round/balances-days-up-to-both-years-and-months.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$twoYears = new \Temporal\Spec\Duration(0, 11, 0, 396, 0, 0, 0, 0, 0, 0);
TemporalHelpers::assertDuration($twoYears->round(['largestUnit' => 'years', 'relativeTo' => new \Temporal\Spec\PlainDate(2017, 1, 1)]), 2, 0, 0, 0, 0, 0, 0, 0, 0, 0);
