<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/round/balances-up-to-weeks.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;

$oneMonthOneDay = new \Temporal\Duration(0, 1, 0, 1, 0, 0, 0, 0, 0, 0);
$oneYearOneMonthOneDay = new \Temporal\Duration(1, 1, 0, 1, 0, 0, 0, 0, 0, 0);
$severalWeeksInDays = new \Temporal\Duration(0, 0, 0, 29, 0, 0, 0, 0, 0, 0);
Assert::incomplete('\\Temporal\\PlainDate is not yet implemented');
