<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/round/february-leap-year.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$relativeTo = new \Temporal\PlainDate(1972, 3, 1);
$options = ['largestUnit' => 'years', 'relativeTo' => $relativeTo];
$twoDaysLessThanFourYears = new \Temporal\Duration(3, 11, 0, 27);
TemporalHelpers::assertDuration($twoDaysLessThanFourYears->round($options), 3, 11, 0, 27, 0, 0, 0, 0, 0, 0, 'Two days less than four years starting in February in a leap year shouldn\'t balance up');
$oneDayLessThanFourYears = new \Temporal\Duration(3, 11, 0, 28);
TemporalHelpers::assertDuration($oneDayLessThanFourYears->round($options), 3, 11, 0, 28, 0, 0, 0, 0, 0, 0, 'One day less than four years starting in February in a leap year shouldn\'t balance up');
$fourYears = new \Temporal\Duration(3, 11, 0, 29);
TemporalHelpers::assertDuration($fourYears->round($options), 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Four years starting in February in a leap year should balance up');
