<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/round/half-expand-is-default.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$d = new \Temporal\Duration(5, 5, 5, 5, 5, 5, 5, 5, 5, 5);
$relativeTo = new \Temporal\PlainDate(2020, 1, 1);
TemporalHelpers::assertDuration($d->round(['smallestUnit' => 'years', 'relativeTo' => $relativeTo]), 6, 0, 0, 0, 0, 0, 0, 0, 0, 0);
TemporalHelpers::assertDuration($d->negated()->round(['smallestUnit' => 'years', 'relativeTo' => $relativeTo]), -6, 0, 0, 0, 0, 0, 0, 0, 0, 0);
