<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/round/largestunit-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;

$duration1 = new \Temporal\Duration(0, 0, 0, 0, 1, 120, 1, 123, 456, 789);
Assert::incomplete('Duration::round() is not yet implemented');
