<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/round/largestunit-correct-rebalancing.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$day_duration = 100;
$tests = [['days', ['days' => $day_duration]], ['hours', ['hours' => $day_duration * 24]], ['minutes', ['minutes' => $day_duration * 24 * 60]], ['seconds', ['seconds' => $day_duration * 24 * 60 * 60]], ['milliseconds', ['milliseconds' => $day_duration * 24 * 60 * 60 * 1000]], ['microseconds', ['microseconds' => $day_duration * 24 * 60 * 60 * 1000 * 1000]], ['nanoseconds', ['nanoseconds' => $day_duration * 24 * 60 * 60 * 1000 * 1000 * 1000]]];
foreach ($tests as $__entry__) {
[$unit, $duration_desc] = array_pad($__entry__, 2, null);
TemporalHelpers::assertDuration(\Temporal\Spec\Duration::from($duration_desc)->round(['relativeTo' => '2023-02-21', 'largestUnit' => 'month']), 0, 3, 0, 11, 0, 0, 0, 0, 0, 0, "rounding from {$unit}");
}
