<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/round/relativeto-propertybag-timezone-wrong-type.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instance = new \Temporal\Duration(1);
$primitiveTests = [[null, 'null'], [true, 'boolean'], ['', 'empty string'], [1, 'number that doesn\'t convert to a valid ISO string'], [19_761_118, 'number that would convert to a valid ISO string in other contexts'], [1, 'bigint']];
foreach ($primitiveTests as [$timeZone, $description]) {
Assert::incomplete('untranslatable expression: ConditionalExpression');
}
