<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/round/relativeto-required-for-rounding-durations-with-calendar-units.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
$d = new \Temporal\Spec\Duration(5, 5, 5, 5, 5, 5, 5, 5, 5, 5);
Assert::throws(\RangeException::class, function () use (&$d) { return $d->round((object) ['largestUnit' => 'years']); }, '');
Assert::throws(\RangeException::class, function () use (&$d) { return $d->round((object) ['largestUnit' => 'months']); }, '');
Assert::throws(\RangeException::class, function () use (&$d) { return $d->round((object) ['largestUnit' => 'weeks']); }, '');
Assert::throws(\RangeException::class, function () use (&$d) { return $d->round((object) ['largestUnit' => 'days']); }, '');
Assert::throws(\RangeException::class, function () use (&$d) { return $d->round((object) ['largestUnit' => 'hours']); }, '');
Assert::throws(\RangeException::class, function () use (&$d) { return $d->round((object) ['largestUnit' => 'minutes']); }, '');
Assert::throws(\RangeException::class, function () use (&$d) { return $d->round((object) ['largestUnit' => 'seconds']); }, '');
Assert::throws(\RangeException::class, function () use (&$d) { return $d->round((object) ['largestUnit' => 'milliseconds']); }, '');
Assert::throws(\RangeException::class, function () use (&$d) { return $d->round((object) ['largestUnit' => 'microseconds']); }, '');
Assert::throws(\RangeException::class, function () use (&$d) { return $d->round((object) ['largestUnit' => 'nanoseconds']); }, '');
