<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/round/relativeto-no-fractional-minutes-hours.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instance = new \Temporal\Spec\Duration(1, 0, 0, 0, 24);
$invalidStrings = [['2025-04-03T05:07.123', 'Fractional minutes'], ['2025-04-03T12.5', 'Fractional hours']];
foreach ($invalidStrings as $__entry__) {
[$arg, $description] = array_pad($__entry__, 2, null);
Assert::throws(\InvalidArgumentException::class, function () use (&$instance, &$arg) { return $instance->round(['largestUnit' => 'months', 'relativeTo' => $arg]); }, "{$description} not allowed in time string");
}
