<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/round/relativeto-propertybag-timezone-string.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instance = new \Temporal\Duration(1);
foreach (['UTC', '+01:00'] as $timeZone) {
Assert::incomplete('untranslatable object property');
}
