<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/round/relativeto-propertybag-calendar-wrong-type.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;

$instance = new \Temporal\Duration(1, 0, 0, 0, 24);
Assert::incomplete('untranslatable: Symbol()');
