<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/round/relativeto-propertybag-no-time-units.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$instance = new \Temporal\Duration(1, 0, 0, 0, 24);
$relativeTo = ['year' => 2000, 'month' => 1, 'day' => 1];
Assert::incomplete('Duration::round() is not yet implemented');
