<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/round/roundingincrement-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$duration = new \Temporal\Duration(0, 0, 0, 4, 12, 34, 56, 987, 654, 321);
Assert::incomplete('Duration::round() is not yet implemented');
