<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/round/roundingincrement-out-of-range.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instance = new \Temporal\Spec\Duration(1);
$options = (object) ['smallestUnit' => 'years', 'relativeTo' => new \Temporal\Spec\PlainDate(2000, 1, 1)];
Assert::throws(\InvalidArgumentException::class, function () use (&$instance, &$options) { return $instance->round((object) array_merge((array) $options, ['roundingIncrement' => -INF])); }, '');
Assert::throws(\InvalidArgumentException::class, function () use (&$instance, &$options) { return $instance->round((object) array_merge((array) $options, ['roundingIncrement' => -1])); }, '');
Assert::throws(\InvalidArgumentException::class, function () use (&$instance, &$options) { return $instance->round((object) array_merge((array) $options, ['roundingIncrement' => 0])); }, '');
Assert::throws(\InvalidArgumentException::class, function () use (&$instance, &$options) { return $instance->round((object) array_merge((array) $options, ['roundingIncrement' => 1_000_000_000 + 1])); }, '');
Assert::throws(\InvalidArgumentException::class, function () use (&$instance, &$options) { return $instance->round((object) array_merge((array) $options, ['roundingIncrement' => INF])); }, '');
