<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/round/rounding-increments.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$d = new \Temporal\Duration(5, 5, 5, 5, 5, 5, 5, 5, 5, 5);
$relativeTo = new \Temporal\PlainDate(2020, 1, 1);
TemporalHelpers::assertDuration($d->round(['smallestUnit' => 'hours', 'roundingIncrement' => 3, 'relativeTo' => $relativeTo]), 5, 6, 0, 10, 6, 0, 0, 0, 0, 0);
TemporalHelpers::assertDuration($d->round(['smallestUnit' => 'minutes', 'roundingIncrement' => 30, 'relativeTo' => $relativeTo]), 5, 6, 0, 10, 5, 0, 0, 0, 0, 0);
TemporalHelpers::assertDuration($d->round(['smallestUnit' => 'seconds', 'roundingIncrement' => 15, 'relativeTo' => $relativeTo]), 5, 6, 0, 10, 5, 5, 0, 0, 0, 0);
TemporalHelpers::assertDuration($d->round(['smallestUnit' => 'milliseconds', 'roundingIncrement' => 10, 'relativeTo' => $relativeTo]), 5, 6, 0, 10, 5, 5, 5, 10, 0, 0);
TemporalHelpers::assertDuration($d->round(['smallestUnit' => 'microseconds', 'roundingIncrement' => 10, 'relativeTo' => $relativeTo]), 5, 6, 0, 10, 5, 5, 5, 5, 10, 0);
TemporalHelpers::assertDuration($d->round(['smallestUnit' => 'nanoseconds', 'roundingIncrement' => 10, 'relativeTo' => $relativeTo]), 5, 6, 0, 10, 5, 5, 5, 5, 5, 10);
