<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/round/singular-units.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$d = new \Temporal\Spec\Duration(5, 5, 5, 5, 5, 5, 5, 5, 5, 5);
$relativeTo = new \Temporal\Spec\PlainDate(2020, 1, 1);
TemporalHelpers::assertDurationsEqual($d->round(['largestUnit' => 'year', 'relativeTo' => $relativeTo]), $d->round(['largestUnit' => 'years', 'relativeTo' => $relativeTo]));
TemporalHelpers::assertDurationsEqual($d->round(['smallestUnit' => 'year', 'relativeTo' => $relativeTo]), $d->round(['smallestUnit' => 'years', 'relativeTo' => $relativeTo]));
TemporalHelpers::assertDurationsEqual($d->round(['largestUnit' => 'month', 'relativeTo' => $relativeTo]), $d->round(['largestUnit' => 'months', 'relativeTo' => $relativeTo]));
TemporalHelpers::assertDurationsEqual($d->round(['smallestUnit' => 'month', 'relativeTo' => $relativeTo]), $d->round(['smallestUnit' => 'months', 'relativeTo' => $relativeTo]));
TemporalHelpers::assertDurationsEqual($d->round(['largestUnit' => 'day', 'relativeTo' => $relativeTo]), $d->round(['largestUnit' => 'days', 'relativeTo' => $relativeTo]));
TemporalHelpers::assertDurationsEqual($d->round(['smallestUnit' => 'day', 'relativeTo' => $relativeTo]), $d->round(['smallestUnit' => 'days', 'relativeTo' => $relativeTo]));
TemporalHelpers::assertDurationsEqual($d->round(['largestUnit' => 'hour', 'relativeTo' => $relativeTo]), $d->round(['largestUnit' => 'hours', 'relativeTo' => $relativeTo]));
TemporalHelpers::assertDurationsEqual($d->round(['smallestUnit' => 'hour', 'relativeTo' => $relativeTo]), $d->round(['smallestUnit' => 'hours', 'relativeTo' => $relativeTo]));
TemporalHelpers::assertDurationsEqual($d->round(['largestUnit' => 'minute', 'relativeTo' => $relativeTo]), $d->round(['largestUnit' => 'minutes', 'relativeTo' => $relativeTo]));
TemporalHelpers::assertDurationsEqual($d->round(['smallestUnit' => 'minute', 'relativeTo' => $relativeTo]), $d->round(['smallestUnit' => 'minutes', 'relativeTo' => $relativeTo]));
TemporalHelpers::assertDurationsEqual($d->round(['largestUnit' => 'second', 'relativeTo' => $relativeTo]), $d->round(['largestUnit' => 'seconds', 'relativeTo' => $relativeTo]));
TemporalHelpers::assertDurationsEqual($d->round(['smallestUnit' => 'second', 'relativeTo' => $relativeTo]), $d->round(['smallestUnit' => 'seconds', 'relativeTo' => $relativeTo]));
TemporalHelpers::assertDurationsEqual($d->round(['largestUnit' => 'millisecond', 'relativeTo' => $relativeTo]), $d->round(['largestUnit' => 'milliseconds', 'relativeTo' => $relativeTo]));
TemporalHelpers::assertDurationsEqual($d->round(['smallestUnit' => 'millisecond', 'relativeTo' => $relativeTo]), $d->round(['smallestUnit' => 'milliseconds', 'relativeTo' => $relativeTo]));
TemporalHelpers::assertDurationsEqual($d->round(['largestUnit' => 'microsecond', 'relativeTo' => $relativeTo]), $d->round(['largestUnit' => 'microseconds', 'relativeTo' => $relativeTo]));
TemporalHelpers::assertDurationsEqual($d->round(['smallestUnit' => 'microsecond', 'relativeTo' => $relativeTo]), $d->round(['smallestUnit' => 'microseconds', 'relativeTo' => $relativeTo]));
TemporalHelpers::assertDurationsEqual($d->round(['largestUnit' => 'nanosecond', 'relativeTo' => $relativeTo]), $d->round(['largestUnit' => 'nanoseconds', 'relativeTo' => $relativeTo]));
TemporalHelpers::assertDurationsEqual($d->round(['smallestUnit' => 'nanosecond', 'relativeTo' => $relativeTo]), $d->round(['smallestUnit' => 'nanoseconds', 'relativeTo' => $relativeTo]));
