<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/round/throws-on-wrong-offset-for-zoned-date-time-relative-to.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$d = new \Temporal\Spec\Duration(5, 5, 5, 5, 5, 5, 5, 5, 5, 5);
Assert::throws(\InvalidArgumentException::class, fn() => $d->round(['smallestUnit' => 'seconds', 'relativeTo' => '1971-01-01T00:00+02:00[-00:44:30]']), '');
