<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/round/total-duration-nanoseconds-too-large-with-zoned-datetime.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;

$maxMs = 9_007_199_254_740_990_976;
$maxUs = 9.007_199_254_740_991e+21;
$maxNs = 9.007_199_254_740_991e+24;
$durations = [
    \Temporal\Duration::from(['seconds' => 9_007_199_254_740_991]),
    \Temporal\Duration::from(['milliseconds' => $maxMs]),
    \Temporal\Duration::from(['microseconds' => $maxUs]),
    \Temporal\Duration::from(['nanoseconds' => $maxNs]),
    \Temporal\Duration::from(['seconds' => -9_007_199_254_740_991]),
    \Temporal\Duration::from(['milliseconds' => -$maxMs]),
    \Temporal\Duration::from(['microseconds' => -$maxUs]),
    \Temporal\Duration::from(['nanoseconds' => -$maxNs]),
];
Assert::incomplete('\\Temporal\\ZonedDateTime is not yet implemented');
