<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/microsecond/basic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instance = new \Temporal\Spec\ZonedDateTime(3_721_001_001_001, 'UTC');
Assert::sameValue($instance->microsecond, 1, '');
