<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/prototype/round/accepts-plural-units.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;

$inst = new \Temporal\Instant(1_000_000_000_123_456_789);
foreach (['hour', 'minute', 'second', 'millisecond', 'microsecond', 'nanosecond'] as $smallestUnit) {
    Assert::incomplete('Duration::round() is not yet implemented');
}
