<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/prototype/round/allow-increments-that-divide-evenly-into-solar-days.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$inst = \Temporal\Spec\Instant::from('1976-11-18T14:23:30.123456789Z');
Assert::assertTrue($inst->round(['smallestUnit' => 'second', 'roundingIncrement' => 864]) instanceof \Temporal\Spec\Instant, '');
