<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainDate/from/calc-epoch-year-hebrew.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$daysPerMonth = ['Cheshvan' => [29, 30, 30, 29, 29, 30, 30, 29, 29, 30, 29], 'Kislev' => [30, 30, 30, 29, 30, 30, 30, 30, 29, 30, 30]];
for ($year = 0; $year < count($daysPerMonth['Cheshvan']); ++$year) {
$endOfCheshvan = \Temporal\Spec\PlainDate::from(['calendar' => 'hebrew', 'year' => $year, 'monthCode' => 'M02', 'day' => 30]);
Assert::sameValue($endOfCheshvan->day, $daysPerMonth['Cheshvan'][$year], '');
$endOfKislev = \Temporal\Spec\PlainDate::from(['calendar' => 'hebrew', 'year' => $year, 'monthCode' => 'M03', 'day' => 30]);
Assert::sameValue($endOfKislev->day, $daysPerMonth['Kislev'][$year], '');
}
