<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainDate/from/calendar-not-supporting-eras.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$result = \Temporal\Spec\PlainDate::from(['era' => 'foobar', 'eraYear' => 1, 'year' => 1970, 'monthCode' => 'M01', 'day' => 1, 'calendar' => 'iso8601']);
TemporalHelpers::assertPlainDate($result, 1970, 1, 'M01', 1, 'era and eraYear are ignored for calendar not using eras (iso8601)');
Assert::throws(\TypeError::class, fn() => \Temporal\Spec\PlainDate::from(['era' => 'foobar', 'eraYear' => 1, 'monthCode' => 'M01', 'day' => 1, 'calendar' => 'iso8601']), 'era and eraYear cannot replace year for calendar not using eras (iso8601)');
$resultChinese = \Temporal\Spec\PlainDate::from(['era' => 'foobar', 'eraYear' => 1, 'year' => 2025, 'monthCode' => 'M01', 'day' => 1, 'calendar' => 'chinese']);
TemporalHelpers::assertPlainDate($resultChinese, 2025, 1, 'M01', 1, 'era and eraYear are ignored for calendar not using eras (Chinese)');
Assert::sameValue($resultChinese->calendarId, 'chinese', '');
Assert::throws(\TypeError::class, fn() => \Temporal\Spec\PlainDate::from(['era' => 'foobar', 'eraYear' => 1, 'monthCode' => 'M01', 'day' => 1, 'calendar' => 'chinese']), 'era and eraYear cannot replace year for calendar not using eras (Chinese)');
