<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainDate/from/era-boundary-islamic-tbla.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$calendar = 'islamic-tbla';
$options = ['overflow' => 'reject'];
$ah0 = \Temporal\Spec\PlainDate::from(['era' => 'ah', 'eraYear' => 0, 'monthCode' => 'M01', 'day' => 1, 'calendar' => $calendar], $options);
TemporalHelpers::assertPlainDate($ah0, 0, 1, 'M01', 1, 'AH 0 resolves to BH 1', 'bh', 1);
$ah1n = \Temporal\Spec\PlainDate::from(['era' => 'ah', 'eraYear' => -1, 'monthCode' => 'M01', 'day' => 1, 'calendar' => $calendar], $options);
TemporalHelpers::assertPlainDate($ah1n, -1, 1, 'M01', 1, 'AH -1 resolves to BH 2', 'bh', 2);
$bh0 = \Temporal\Spec\PlainDate::from(['era' => 'bh', 'eraYear' => 0, 'monthCode' => 'M01', 'day' => 1, 'calendar' => $calendar], $options);
TemporalHelpers::assertPlainDate($bh0, 1, 1, 'M01', 1, 'BH 0 resolves to AH 1', 'ah', 1);
$bh1n = \Temporal\Spec\PlainDate::from(['era' => 'bh', 'eraYear' => -1, 'monthCode' => 'M01', 'day' => 1, 'calendar' => $calendar], $options);
TemporalHelpers::assertPlainDate($bh1n, 2, 1, 'M01', 1, 'BH -1 resolves to AH 2', 'ah', 2);
