<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainMonthDay/prototype/with/options-invalid.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
$instance = new \Temporal\Spec\PlainMonthDay(2, 2);
foreach ([null, true, 'hello', \Temporal\Tests\Test262\JsSymbol::singleton(), 1, 1] as $badOptions) {
Assert::throws(\TypeError::class, function () use (&$instance, &$badOptions) { return $instance->with((object) ['day' => 17], $badOptions); }, '');
}
