<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/prototype/toZonedDateTimeISO/timezone-string.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instance = new \Temporal\Spec\Instant(0);
foreach (['UTC', '+01:30'] as $timeZone) {
$result = $instance->toZonedDateTimeISO($timeZone);
Assert::sameValue($result->timeZoneId, $timeZone, "time zone slot should store string \"{$timeZone}\"");
}
