<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/withPlainTime/argument-zoneddatetime-negative-epochnanoseconds.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$datetime = new \Temporal\ZonedDateTime(-13_849_764_999_999_999, 'UTC');
$instance = new \Temporal\ZonedDateTime(0, 'UTC');
$result = $instance->withPlainTime($datetime);
Assert::sameValue($result->epochNanoseconds, 60_635_000_000_001, '');
