<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/withPlainTime/order-of-operations.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$actual = [];
$expected = ['get plainTimeLike.hour', 'get plainTimeLike.hour.valueOf', 'call plainTimeLike.hour.valueOf', 'get plainTimeLike.microsecond', 'get plainTimeLike.microsecond.valueOf', 'call plainTimeLike.microsecond.valueOf', 'get plainTimeLike.millisecond', 'get plainTimeLike.millisecond.valueOf', 'call plainTimeLike.millisecond.valueOf', 'get plainTimeLike.minute', 'get plainTimeLike.minute.valueOf', 'call plainTimeLike.minute.valueOf', 'get plainTimeLike.nanosecond', 'get plainTimeLike.nanosecond.valueOf', 'call plainTimeLike.nanosecond.valueOf', 'get plainTimeLike.second', 'get plainTimeLike.second.valueOf', 'call plainTimeLike.second.valueOf'];
$instance = new \Temporal\Spec\ZonedDateTime(946_713_600_000_000_000, 'UTC');
$plainTimeLike = TemporalHelpers::propertyBagObserver($actual, (object) ['hour' => 2, 'minute' => 30, 'second' => 0, 'millisecond' => 0, 'microsecond' => 0, 'nanosecond' => 0], 'plainTimeLike');
$instance->withPlainTime($plainTimeLike);
// JS-only (observer call-order check, tracker is empty in PHP): assert.compareArray(actual, expected, "order of operations");
// JS-only (observer tracker reset (no-op in PHP)): actual.splice(0);
\PHPUnit\Framework\Assert::assertTrue(true, 'Script completed without throwing');
