<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/basic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
TemporalHelpers::assertPlainDateTime(new \Temporal\Spec\PlainDateTime(1, 2, 3, 4, 5, 6, 7, 8, 9), 1, 2, 'M02', 3, 4, 5, 6, 7, 8, 9);
TemporalHelpers::assertPlainDateTime(new \Temporal\Spec\PlainDateTime(1, 2, 3, 4, 5, 6, 7, 8), 1, 2, 'M02', 3, 4, 5, 6, 7, 8, 0);
TemporalHelpers::assertPlainDateTime(new \Temporal\Spec\PlainDateTime(1, 2, 3, 4, 5, 6, 7), 1, 2, 'M02', 3, 4, 5, 6, 7, 0, 0);
TemporalHelpers::assertPlainDateTime(new \Temporal\Spec\PlainDateTime(1, 2, 3, 4, 5, 6), 1, 2, 'M02', 3, 4, 5, 6, 0, 0, 0);
TemporalHelpers::assertPlainDateTime(new \Temporal\Spec\PlainDateTime(1, 2, 3, 4, 5), 1, 2, 'M02', 3, 4, 5, 0, 0, 0, 0);
TemporalHelpers::assertPlainDateTime(new \Temporal\Spec\PlainDateTime(1, 2, 3, 4), 1, 2, 'M02', 3, 4, 0, 0, 0, 0, 0);
TemporalHelpers::assertPlainDateTime(new \Temporal\Spec\PlainDateTime(1, 2, 3), 1, 2, 'M02', 3, 0, 0, 0, 0, 0, 0);
TemporalHelpers::assertPlainDateTime(new \Temporal\Spec\PlainDateTime(-25_406, 1, 1), -25_406, 1, 'M01', 1, 0, 0, 0, 0, 0, 0);
TemporalHelpers::assertPlainDateTime(new \Temporal\Spec\PlainDateTime(29_345, 12, 31, 23, 59, 59, 999, 999, 999), 29_345, 12, 'M12', 31, 23, 59, 59, 999, 999, 999);
