<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/add/argument-propertybag-optional-properties.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instance = new \Temporal\ZonedDateTime(0, 'UTC');
$oneProperty = ['hours' => 1];
$allProperties = ['years' => 0, 'months' => 0, 'weeks' => 0, 'days' => 0, 'hours' => 1, 'minutes' => 0, 'seconds' => 0, 'milliseconds' => 0, 'microseconds' => 0, 'nanoseconds' => 0];
$resultWithout = $instance->add($oneProperty);
$resultWith = $instance->add($allProperties);
Assert::assertTrue($resultWithout->equals($resultWith), 'results should be the same with and without optional properties');
