<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/add/argument-string-negative-fractional-units.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instance = new \Temporal\ZonedDateTime(1_000_000_000_000_000_000, 'UTC');
$resultHours = $instance->add('-PT24.567890123H');
Assert::sameValue($resultHours->epochNanoseconds, 999_911_555_595_557_200, 'negative fractional hours');
$resultMinutes = $instance->add('-PT1440.567890123M');
Assert::sameValue($resultMinutes->epochNanoseconds, 999_913_565_926_592_620, 'negative fractional minutes');
