<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/add/argument-not-object.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
$instance = new \Temporal\Spec\ZonedDateTime(1_000_000_000_000_000_000, 'UTC');
Assert::throws(\TypeError::class, function () use (&$instance) { return $instance->add(); }, 'undefined');
Assert::throws(\TypeError::class, function () use (&$instance) { return $instance->add(null); }, 'null');
Assert::throws(\TypeError::class, function () use (&$instance) { return $instance->add(true); }, 'boolean');
Assert::throws(\RangeException::class, function () use (&$instance) { return $instance->add(''); }, 'empty string');
Assert::throws(\TypeError::class, function () use (&$instance) { return $instance->add(\Temporal\Tests\Test262\JsSymbol::singleton()); }, 'Symbol');
Assert::throws(\TypeError::class, function () use (&$instance) { return $instance->add(7); }, 'number');
Assert::incomplete('BigInt literal in TypeError assertion; BigInt vs Number distinction not replicable in PHP');
