<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/add/cross-epoch.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$zdt = new \Temporal\ZonedDateTime(-560_174_321_098_766, 'UTC');
$one = $zdt->subtract(['hours' => 240, 'nanoseconds' => 800]);
$two = $zdt->add(['hours' => 240, 'nanoseconds' => 800]);
$three = $two->subtract(['hours' => 480, 'nanoseconds' => 1600]);
$four = $one->add(['hours' => 480, 'nanoseconds' => 1600]);
TemporalHelpers::assertZonedDateTimesEqual($one, new \Temporal\ZonedDateTime(-1_424_174_321_099_566, 'UTC'));
TemporalHelpers::assertZonedDateTimesEqual($two, new \Temporal\ZonedDateTime(303_825_678_902_034, 'UTC'));
TemporalHelpers::assertZonedDateTimesEqual($three, $one);
TemporalHelpers::assertZonedDateTimesEqual($four, $two);
