<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/add/options-read-before-algorithmic-validation.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
use Temporal\Tests\Test262\TemporalHelpers;
$expected = ['get options.overflow', 'get options.overflow.toString', 'call options.overflow.toString'];
$actual = [];
$options = TemporalHelpers::propertyBagObserver($actual, (object) ['overflow' => 'reject'], 'options');
$instance = new \Temporal\Spec\ZonedDateTime(2_592_000_000_000_000, 'UTC');
Assert::throws(\InvalidArgumentException::class, function () use (&$instance, &$options) { $instance->add(new \Temporal\Spec\Duration(0, 1), $options); }, 'overflow reject exception thrown');
// JS-only (observer call-order check, tracker is empty in PHP): assert.compareArray(actual, expected, "all options should be read first");
// JS-only (observer tracker reset (no-op in PHP)): actual.splice(0);
Assert::throws(\InvalidArgumentException::class, function () use (&$instance, &$options) { $instance->add(new \Temporal\Spec\Duration(0, 0, 0, 0, 0, 0, 9_007_199_254_740_991), $options); }, 'exception thrown when resulting exact time out of range');
// JS-only (observer call-order check, tracker is empty in PHP): assert.compareArray(actual, expected, "all options should be read first");
