<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/until/argument-string-invalid.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
use Temporal\Tests\Test262\TemporalHelpers;
$instance = new \Temporal\Spec\PlainYearMonth(1976, 11);
foreach (TemporalHelpers::isoPlainYearMonthStringsInvalid() as $arg) {
Assert::throws(\InvalidArgumentException::class, function () use (&$instance, &$arg) { return $instance->until($arg); }, "\"{$arg}\" is not a valid PlainYearMonth string");
}
