<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/until/argument-casting.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$nov94 = new \Temporal\PlainYearMonth(1994, 11);
$jun13 = new \Temporal\PlainYearMonth(2013, 6);
$diff = $nov94->until($jun13);
TemporalHelpers::assertDurationsEqual($nov94->until(['year' => 2013, 'month' => 6]), $diff, 'Casts object argument');
TemporalHelpers::assertDurationsEqual($nov94->until('2013-06'), $diff, 'Casts string argument');
