<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/until/argument-string-invalid.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$instance = new \Temporal\PlainYearMonth(1976, 11);
foreach ($TemporalHelpers->ISO->plainYearMonthStringsInvalid() as $arg) {
Assert::throws(\InvalidArgumentException::class, fn() => $instance->until($arg), "\"{$arg}\" is not a valid PlainYearMonth string");
}
