<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/until/order-of-operations.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$expected = ['get other.calendar', 'get other.month', 'get other.month.valueOf', 'call other.month.valueOf', 'get other.monthCode', 'get other.monthCode.toString', 'call other.monthCode.toString', 'get other.year', 'get other.year.valueOf', 'call other.year.valueOf', 'get options.largestUnit', 'get options.largestUnit.toString', 'call options.largestUnit.toString', 'get options.roundingIncrement', 'get options.roundingIncrement.valueOf', 'call options.roundingIncrement.valueOf', 'get options.roundingMode', 'get options.roundingMode.toString', 'call options.roundingMode.toString', 'get options.smallestUnit', 'get options.smallestUnit.toString', 'call options.smallestUnit.toString'];
$actual = [];
$instance = new \Temporal\PlainYearMonth(2000, 5, 'iso8601', 1);
Assert::incomplete('TemporalHelpers.propertyBagObserver() is not yet implemented');
