<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/until/roundingincrement-as-expected.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$earlier = new \Temporal\Spec\PlainYearMonth(2019, 1);
$later = new \Temporal\Spec\PlainYearMonth(2021, 9);
$laterSinceYear = $earlier->until($later, ['smallestUnit' => 'years', 'roundingIncrement' => 4, 'roundingMode' => 'halfExpand']);
TemporalHelpers::assertDuration($laterSinceYear, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'rounds to an increment of years');
$laterSinceMixed = $earlier->until($later, ['smallestUnit' => 'months', 'roundingIncrement' => 5]);
TemporalHelpers::assertDuration($laterSinceMixed, 2, 5, 0, 0, 0, 0, 0, 0, 0, 0, 'rounds to an increment of months mixed with years');
$laterSinceMonth = $earlier->until($later, ['largestUnit' => 'months', 'smallestUnit' => 'months', 'roundingIncrement' => 10]);
TemporalHelpers::assertDuration($laterSinceMonth, 0, 30, 0, 0, 0, 0, 0, 0, 0, 0, 'rounds to an increment of pure months');
