<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/until/roundingincrement-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$earlier = new \Temporal\PlainYearMonth(2000, 5);
$later = new \Temporal\PlainYearMonth(2001, 6);
$explicit = $earlier->until($later, []);
TemporalHelpers::assertDuration($explicit, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'default roundingIncrement is 1');
$implicit = $earlier->until($later, new \stdClass());
TemporalHelpers::assertDuration($implicit, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'default roundingIncrement is 1');
