<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/until/roundingincrement-wrong-type.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$earlier = new \Temporal\Spec\PlainYearMonth(2000, 5);
$later = new \Temporal\Spec\PlainYearMonth(2001, 6);
TemporalHelpers::checkRoundingIncrementOptionWrongType(fn($roundingIncrement) => $earlier->until($later, ['roundingIncrement' => $roundingIncrement]), fn($result, $descr) => TemporalHelpers::assertDuration($result, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, $descr), fn($result, $descr) => TemporalHelpers::assertDuration($result, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, $descr));
