<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/from/argument-duration.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$orig = new \Temporal\Spec\Duration(1, 2, 3, 4, 5, 6, 7, 987, 654, 321);
$result = \Temporal\Spec\Duration::from($orig);
TemporalHelpers::assertDuration($result, 1, 2, 3, 4, 5, 6, 7, 987, 654, 321, 'Duration is copied');
Assert::notSameValue($result, $orig, 'When a Duration is given, the returned value is not the original Duration');
