<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainDateTime/from/islamic-rgsa.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$calendar = 'islamic-rgsa';
Assert::throws(\InvalidArgumentException::class, fn() => \Temporal\Spec\PlainDateTime::from(['year' => 1500, 'month' => 1, 'day' => 1, 'hour' => 12, 'minute' => 34, 'calendar' => $calendar]), 'fallback for calendar ID \'islamic-rgsa\' only supported in Intl.DateTimeFormat constructor, not Temporal');
