<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainMonthDay/prototype/toLocaleString/default-does-not-include-year-time-and-time-zone-name.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$plainMonthDay = new \Temporal\Spec\PlainMonthDay(12, 26);
$result = $plainMonthDay->toLocaleString('en-u-ca-iso8601', ['timeZone' => 'UTC']);
Assert::assertTrue(!str_contains($result, '1972'), "PlainMonthDay formatted with no options {$result} should not include reference year");
Assert::assertTrue(str_contains($result, '12') || str_contains($result, 'Dec'), "PlainMonthDay formatted with no options {$result} should include month");
Assert::assertTrue(str_contains($result, '26'), "PlainMonthDay formatted with no options {$result} should include day");
Assert::assertTrue(!str_contains($result, '00'), "PlainMonthDay formatted with no options {$result} should not include hour, minute, second");
Assert::assertTrue(!str_contains($result, 'UTC') && !str_contains($result, 'Coordinated Universal Time'), "PlainMonthDay formatted with no options {$result} should not include time zone name");
