<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/from/instant-string.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;

$str = '1970-01-01T00:00';
Assert::throws(
    \InvalidArgumentException::class,
    fn() => \Temporal\Instant::from($str),
    'bare date-time string is not an instant',
);
$str = '1970-01-01T00:00[UTC]';
Assert::throws(
    \InvalidArgumentException::class,
    fn() => \Temporal\Instant::from($str),
    'date-time + IANA annotation is not an instant',
);
$str = '1970-01-01T00:00Z';
$result1 = \Temporal\Instant::from($str);
Assert::sameValue($result1->epochNanoseconds, 0, 'date-time + Z preserves exact time');
$str = '1970-01-01T00:00+01:00';
$result2 = \Temporal\Instant::from($str);
Assert::sameValue(
    $result2->epochNanoseconds,
    -3_600_000_000_000,
    'date-time + offset preserves exact time with offset',
);
$str = '1970-01-01T00:00Z[Etc/Ignored]';
$result3 = \Temporal\Instant::from($str);
Assert::sameValue($result3->epochNanoseconds, 0, 'date-time + Z + IANA annotation ignores the IANA annotation');
$str = '1970-01-01T00:00+01:00[Etc/Ignored]';
$result4 = \Temporal\Instant::from($str);
Assert::sameValue(
    $result4->epochNanoseconds,
    -3_600_000_000_000,
    'date-time + offset + IANA annotation ignores the IANA annotation',
);
$str = '1970-01-01T00:00Z[u-ca=hebrew]';
$result6 = \Temporal\Instant::from($str);
Assert::sameValue($result6->epochNanoseconds, 0, 'date-time + Z + Calendar ignores the Calendar');
$str = '1970-01-01T00:00+01:00[u-ca=hebrew]';
$result7 = \Temporal\Instant::from($str);
Assert::sameValue($result7->epochNanoseconds, -3_600_000_000_000, 'date-time + offset + Calendar ignores the Calendar');
$str = '1970-01-01T00:00+01:00[Etc/Ignored][u-ca=hebrew]';
$result8 = \Temporal\Instant::from($str);
Assert::sameValue(
    $result8->epochNanoseconds,
    -3_600_000_000_000,
    'date-time + offset + IANA annotation + Calendar ignores the Calendar and IANA annotation',
);
