<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/from/subclassing-ignored.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
TemporalHelpers::checkSubclassingIgnoredStatic(\Temporal\Instant::class, 'from', ['1976-11-18T14:23:30.123456789Z'], fn($result) => Assert::sameValue($result->epochNanoseconds, 217_175_010_123_456_789, 'epochNanoseconds result'));
