<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/from/argument-propertybag-calendar-iso-string.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
foreach (['2020-01-01', '2020-01-01[u-ca=iso8601]', '2020-01-01T00:00:00.000000000', '2020-01-01T00:00:00.000000000[u-ca=iso8601]', '01-01', '01-01[u-ca=iso8601]', '2020-01', '2020-01[u-ca=iso8601]'] as $calendar) {
$arg = ['year' => 1976, 'monthCode' => 'M11', 'day' => 18, 'calendar' => $calendar];
$result = \Temporal\PlainDateTime::from($arg);
TemporalHelpers::assertPlainDateTime($result, 1976, 11, 'M11', 18, 0, 0, 0, 0, 0, 0, "Calendar created from string \"{$calendar}\"");
Assert::sameValue($result->calendarId, 'iso8601', 'calendar string is iso8601');
}
