<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/from/argument-string-calendar-annotation.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$tests = [['1976-11-18T15:23[u-ca=iso8601]', 'without time zone'], ['1976-11-18T15:23[UTC][u-ca=iso8601]', 'with time zone'], ['1976-11-18T15:23[!u-ca=iso8601]', 'with ! and no time zone'], ['1976-11-18T15:23[UTC][!u-ca=iso8601]', 'with ! and time zone'], ['1976-11-18T15:23[u-ca=iso8601][u-ca=discord]', 'second annotation ignored']];
foreach ($tests as [$arg, $description]) {
$result = \Temporal\PlainDateTime::from($arg);
TemporalHelpers::assertPlainDateTime($result, 1976, 11, 'M11', 18, 15, 23, 0, 0, 0, 0, "calendar annotation ({$description})");
}
