<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/from/infinity-throws-rangeerror.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
use Temporal\Tests\Test262\TemporalHelpers;
$base = (object) ['year' => 2000, 'month' => 5, 'day' => 2, 'hour' => 15, 'minute' => 30, 'second' => 45, 'millisecond' => 987, 'microsecond' => 654, 'nanosecond' => 321];
foreach ([INF, -INF] as $inf) {
foreach (['year', 'month', 'day', 'hour', 'minute', 'second', 'millisecond', 'microsecond', 'nanosecond'] as $prop) {
foreach (['constrain', 'reject'] as $overflow) {
Assert::throws(\InvalidArgumentException::class, function () use (&$base, &$prop, &$inf, &$overflow) { return \Temporal\Spec\PlainDateTime::from((object) JsUndefined::strip(array_merge((array) $base, [$prop => $inf])), (object) JsUndefined::strip(['overflow' => $overflow])); }, "{$prop} property cannot be {$inf} (overflow {$overflow}");
$calls = [];
$obj = TemporalHelpers::toPrimitiveObserver($calls, $inf, $prop);
Assert::throws(\InvalidArgumentException::class, function () use (&$base, &$prop, &$obj, &$overflow) { return \Temporal\Spec\PlainDateTime::from((object) JsUndefined::strip(array_merge((array) $base, [$prop => $obj])), (object) JsUndefined::strip(['overflow' => $overflow])); }, '');
// JS-only (observer call-order check, tracker is empty in PHP): assert.compareArray(calls, [`get ${prop}.valueOf`, `call ${prop}.valueOf`], "it fails after fetching the primitive value");
}
}
}
