<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/from/observable-get-overflow-argument-primitive.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$expected = ['get options.overflow', 'get options.overflow.toString', 'call options.overflow.toString'];
$actual = [];
$options = TemporalHelpers::propertyBagObserver($actual, ['overflow' => 'reject'], 'options');
$result = \Temporal\Spec\PlainDateTime::from('2021-05-17T12:34:56', $options);
// JS-only (observer call-order check, tracker is empty in PHP): assert.compareArray(actual, expected, "Successful call");
TemporalHelpers::assertPlainDateTime($result, 2021, 5, 'M05', 17, 12, 34, 56, 0, 0, 0);
// JS-only (observer tracker reset (no-op in PHP)): actual.splice(0);
Assert::throws(\TypeError::class, function () use (&$options) { return \Temporal\Spec\PlainDateTime::from(7, $options); }, '');
// JS-only (observer call-order check, tracker is empty in PHP): assert.compareArray(actual, [], "Failing call before options is processed");
// JS-only (observer tracker reset (no-op in PHP)): actual.splice(0);
Assert::throws(\InvalidArgumentException::class, function () use (&$options) { return \Temporal\Spec\PlainDateTime::from(['year' => 2021, 'month' => 2, 'day' => 29], $options); }, '');
// JS-only (observer call-order check, tracker is empty in PHP): assert.compareArray(actual, expected, "Failing call after options is processed");
