<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/from/options-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$fields = ['year' => 2000, 'month' => 13, 'day' => 2];
$explicit = \Temporal\PlainDateTime::from($fields);
Assert::sameValue($explicit->month, 12, 'default overflow is constrain');
$implicit = \Temporal\PlainDateTime::from($fields);
Assert::sameValue($implicit->month, 12, 'default overflow is constrain');
$lambda = \Temporal\PlainDateTime::from($fields, function () {  });
Assert::sameValue($lambda->month, 12, 'default overflow is constrain');
