<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/from/parser.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$dateTime = \Temporal\Spec\PlainDateTime::from('2020-01-01T00:00:00+01:00[Custom]');
TemporalHelpers::assertPlainDateTime($dateTime, 2020, 1, 'M01', 1, 0, 0, 0, 0, 0, 0);
