<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/with/options-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$datetime = new \Temporal\Spec\PlainDateTime(2000, 2, 2, 12, 34, 56, 987, 654, 321);
$fields = ['day' => 31];
$explicit = $datetime->with($fields);
Assert::sameValue($explicit->month, 2, 'default overflow is constrain');
Assert::sameValue($explicit->day, 29, 'default overflow is constrain');
$implicit = $datetime->with($fields);
Assert::sameValue($implicit->month, 2, 'default overflow is constrain');
Assert::sameValue($implicit->day, 29, 'default overflow is constrain');
$lambda = $datetime->with($fields, function () {  });
Assert::sameValue($lambda->month, 2, 'default overflow is constrain');
Assert::sameValue($lambda->day, 29, 'default overflow is constrain');
