<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/with/options-invalid.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
$datetime = new \Temporal\Spec\PlainDateTime(1976, 11, 18, 15, 23, 30, 123, 456, 789);
$badOptions = [null, 1, 'hello', true, \Temporal\Tests\Test262\JsSymbol::singleton(), 1];
foreach ($badOptions as $bad) {
if ($bad === null) { continue; }
Assert::throws(\TypeError::class, function () use (&$datetime, &$bad) { return $datetime->with(['day' => 5], $bad); }, "bad options (" . (gettype($bad)) . ")");
}
