<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/with/overflow-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$datetime = new \Temporal\Spec\PlainDateTime(2000, 5, 2, 12);
$explicit = $datetime->with(['minute' => 67], []);
TemporalHelpers::assertPlainDateTime($explicit, 2000, 5, 'M05', 2, 12, 59, 0, 0, 0, 0, 'default overflow is constrain');
$implicit = $datetime->with(['minute' => 67], new \stdClass());
TemporalHelpers::assertPlainDateTime($implicit, 2000, 5, 'M05', 2, 12, 59, 0, 0, 0, 0, 'default overflow is constrain');
$lambda = $datetime->with(['minute' => 67], function () {  });
TemporalHelpers::assertPlainDateTime($lambda, 2000, 5, 'M05', 2, 12, 59, 0, 0, 0, 0, 'default overflow is constrain');
