<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/max.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$cases = [[new \Temporal\Spec\Duration(0, 0, 0, 104_249_991_374, 7, 36, 31, 999, 999, 999), 'max days', 9_007_199_254_740_992], [new \Temporal\Spec\Duration(0, 0, 0, 0, 2_501_999_792_983, 36, 31, 999, 999, 999), 'max hours', 9_007_199_254_740_992], [new \Temporal\Spec\Duration(0, 0, 0, 0, 0, 150_119_987_579_016, 31, 999, 999, 999), 'max minutes', 9_007_199_254_740_992], [new \Temporal\Spec\Duration(0, 0, 0, 0, 0, 0, 9_007_199_254_740_991, 999, 999, 999), 'max seconds', 9_007_199_254_740_992], [new \Temporal\Spec\Duration(0, 0, 0, -104_249_991_374, -7, -36, -31, -999, -999, -999), 'min days', -9_007_199_254_740_992], [new \Temporal\Spec\Duration(0, 0, 0, 0, -2_501_999_792_983, -36, -31, -999, -999, -999), 'min hours', -9_007_199_254_740_992], [new \Temporal\Spec\Duration(0, 0, 0, 0, 0, -150_119_987_579_016, -31, -999, -999, -999), 'min minutes', -9_007_199_254_740_992], [new \Temporal\Spec\Duration(0, 0, 0, 0, 0, 0, -9_007_199_254_740_991, -999, -999, -999), 'min seconds', -9_007_199_254_740_992]];
foreach ($cases as $__entry__) {
[$d, $descr, $expected] = array_pad($__entry__, 3, null);
Assert::sameValue($d->total('seconds'), $expected, $descr);
}
$max = new \Temporal\Spec\Duration(4_294_967_295, 4_294_967_295, 4_294_967_295, 104_249_991_374, 7, 36, 31, 999, 999, 999);
TemporalHelpers::assertDuration($max, 4_294_967_295, 4_294_967_295, 4_294_967_295, 104_249_991_374, 7, 36, 31, 999, 999, 999);
$min = new \Temporal\Spec\Duration(-4_294_967_295, -4_294_967_295, -4_294_967_295, -104_249_991_374, -7, -36, -31, -999, -999, -999);
TemporalHelpers::assertDuration($min, -4_294_967_295, -4_294_967_295, -4_294_967_295, -104_249_991_374, -7, -36, -31, -999, -999, -999);
