<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/toString/balance-negative-time-units.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$datetime = new \Temporal\Spec\ZonedDateTime(1001, '-00:02');
$isoString = $datetime->toString();
Assert::sameValue($isoString, '1969-12-31T23:58:00.000001001-00:02[-00:02]', '');
