<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/toString/calendarname-auto.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$date = new \Temporal\ZonedDateTime(3_661_987_654_321, 'UTC');
$result = $date->toString(['calendarName' => 'auto']);
Assert::sameValue($result, '1970-01-01T01:01:01.987654321+00:00[UTC]', "built-in ISO calendar for calendarName = auto");
