<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/toString/roundingmode-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$datetime = new \Temporal\ZonedDateTime(1_000_000_000_123_987_500, 'UTC');
$explicit1 = $datetime->toString(['smallestUnit' => 'microsecond']);
Assert::sameValue($explicit1, '2001-09-09T01:46:40.123987+00:00[UTC]', 'default roundingMode is trunc');
$implicit1 = $datetime->toString(['smallestUnit' => 'microsecond']);
Assert::sameValue($implicit1, '2001-09-09T01:46:40.123987+00:00[UTC]', 'default roundingMode is trunc');
$explicit2 = $datetime->toString(['smallestUnit' => 'millisecond']);
Assert::sameValue($explicit2, '2001-09-09T01:46:40.123+00:00[UTC]', 'default roundingMode is trunc');
$implicit2 = $datetime->toString(['smallestUnit' => 'millisecond']);
Assert::sameValue($implicit2, '2001-09-09T01:46:40.123+00:00[UTC]', 'default roundingMode is trunc');
$explicit3 = $datetime->toString(['smallestUnit' => 'second']);
Assert::sameValue($explicit3, '2001-09-09T01:46:40+00:00[UTC]', 'default roundingMode is trunc');
$implicit3 = $datetime->toString(['smallestUnit' => 'second']);
Assert::sameValue($implicit3, '2001-09-09T01:46:40+00:00[UTC]', 'default roundingMode is trunc');
