<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/toString/smallestunit-plurals-accepted.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$datetime = new \Temporal\ZonedDateTime(1_000_000_000_123_456_789, 'UTC');
$validUnits = ['minute', 'second', 'millisecond', 'microsecond', 'nanosecond'];
TemporalHelpers::checkPluralUnitsAccepted(fn($smallestUnit) => $datetime->toString(['smallestUnit' => $smallestUnit]), $validUnits);
