<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/toString/precision.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$durationString = 'PT0.084000159S';
$duration = \Temporal\Spec\Duration::from($durationString);
$precisionString = $duration->toString(['smallestUnit' => 'milliseconds']);
Assert::sameValue($durationString, $duration->toString(), '');
Assert::sameValue($precisionString, 'PT0.084S', '');
