<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/since/argument-propertybag-timezone-string.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instance1 = new \Temporal\ZonedDateTime(0, 'UTC');
Assert::assertTrue($instance1->since(['year' => 1970, 'month' => 1, 'day' => 1, 'timeZone' => 'UTC'])->blank, 'Time zone created from string \'UTC\'');
$instance2 = new \Temporal\ZonedDateTime(0, '-01:30');
Assert::assertTrue($instance2->since(['year' => 1969, 'month' => 12, 'day' => 31, 'hour' => 22, 'minute' => 30, 'timeZone' => '-01:30'])->blank, 'Time zone created from string \'-01:30\'');
