<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/since/casts-argument.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$zdt = new \Temporal\Spec\ZonedDateTime(217_175_010_123_456_789, '+01:00');
$zdt2 = new \Temporal\Spec\ZonedDateTime(1_572_342_398_271_986_102, '+01:00');
TemporalHelpers::assertDuration($zdt->since(['year' => 2019, 'month' => 10, 'day' => 29, 'hour' => 10, 'timeZone' => '+01:00']), 0, 0, 0, 0, -376_434, -36, -29, -876, -543, -211);
TemporalHelpers::assertDuration($zdt->since($zdt2), 0, 0, 0, 0, -376_435, -23, -8, -148, -529, -313);
