<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainDateTime/prototype/with/mutually-exclusive-fields-islamic-tbla.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$options = (object) ['overflow' => 'reject'];
$instance = \Temporal\Spec\PlainDateTime::from((object) ['year' => 1447, 'monthCode' => 'M12', 'day' => 15, 'hour' => 12, 'minute' => 34, 'calendar' => 'islamic-tbla'], $options);
TemporalHelpers::assertPlainDateTime($instance, 1447, 12, 'M12', 15, 12, 34, 0, 0, 0, 0, 'check that all fields are as expected', 'ah', 1447);
TemporalHelpers::assertPlainDateTime($instance->with((object) ['era' => 'bh', 'eraYear' => 1], $options), 0, 12, 'M12', 15, 12, 34, 0, 0, 0, 0, 'era and eraYear together exclude year', 'bh', 1);
TemporalHelpers::assertPlainDateTime($instance->with((object) ['year' => -2], $options), -2, 12, 'M12', 15, 12, 34, 0, 0, 0, 0, 'year excludes era and eraYear', 'bh', 3);
TemporalHelpers::assertPlainDateTime($instance->with((object) ['month' => 5], $options), 1447, 5, 'M05', 15, 12, 34, 0, 0, 0, 0, 'month excludes monthCode', 'ah', 1447);
TemporalHelpers::assertPlainDateTime($instance->with((object) ['monthCode' => 'M05'], $options), 1447, 5, 'M05', 15, 12, 34, 0, 0, 0, 0, 'monthCode excludes month', 'ah', 1447);
Assert::throws(\TypeError::class, function () use (&$instance) { return $instance->with((object) ['eraYear' => 1]); }, 'eraYear excludes year and era, and cannot be provided without era');
Assert::throws(\TypeError::class, function () use (&$instance) { return $instance->with((object) ['era' => 'bh']); }, 'era excludes year and eraYear, and cannot be provided without eraYear');
