<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/with/subclassing-ignored.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
TemporalHelpers::checkSubclassingIgnored(\Temporal\PlainYearMonth::class, [2000, 5], 'with', [['month' => 11]], fn($result) => TemporalHelpers::assertPlainYearMonth($result, 2000, 11, 'M11'));
