<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/with/yearmonthlike-invalid.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
$plainYearMonth = new \Temporal\Spec\PlainYearMonth(1, 1);
$tests = [[JsUndefined::singleton()], [null], [true], ['2019-05-17'], ['2019-05-17T12:34'], ['2019-05-17T12:34Z'], ['18:05:42.577'], ['42'], [\Temporal\Tests\Test262\JsSymbol::singleton(), 'symbol'], [42, 'number'], [42, 'bigint'], [\Temporal\Spec\PlainDate::from('2019-05-17'), 'PlainDate'], [\Temporal\Spec\PlainDateTime::from('2019-05-17T12:34'), 'PlainDateTime'], [\Temporal\Spec\PlainMonthDay::from('2019-05-17'), 'PlainMonthDay'], [\Temporal\Spec\PlainTime::from('12:34'), 'PlainTime'], [\Temporal\Spec\PlainYearMonth::from('2019-05-17'), 'PlainYearMonth'], [\Temporal\Spec\ZonedDateTime::from('2019-05-17T12:34Z[UTC]'), 'ZonedDateTime'], [(object) ['year' => 2021, 'calendar' => 'iso8601'], 'calendar'], [(object) ['year' => 2021, 'timeZone' => 'UTC'], 'timeZone'], [(object) [], 'empty object'], [(object) ['months' => 12], 'only plural property']];
Assert::incomplete('BigInt literal in wrong-type for-of data table; Number-vs-BigInt distinction not representable in PHP');
