<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/toPlainDate/limits.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$min = \Temporal\PlainDateTime::from('-271821-04-19T00:00:00.000000001');
TemporalHelpers::assertPlainDate($min->toPlainDate(), -271_821, 4, 'M04', 19, 'min');
$max = \Temporal\PlainDateTime::from('+275760-09-13T23:59:59.999999999');
TemporalHelpers::assertPlainDate($max->toPlainDate(), 275_760, 9, 'M09', 13, 'max');
