<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/compare/exhaustive.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
Assert::sameValue(\Temporal\Instant::compare(new \Temporal\Instant(1_000_000_000_000_000_000), new \Temporal\Instant(500_000_000_000_000_000)), 1, '>');
Assert::sameValue(\Temporal\Instant::compare(new \Temporal\Instant(-1000), new \Temporal\Instant(1000)), -1, '<');
Assert::sameValue(\Temporal\Instant::compare(new \Temporal\Instant(123_456_789), new \Temporal\Instant(123_456_789)), 0, '=');
