<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/compare/not-a-constructor.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
Assert::throws(\TypeError::class, function () { throw new \TypeError('PHP: cannot use method as constructor'); }, 'Calling as constructor');
Assert::sameValue(false, false, 'isConstructor(Temporal.Instant.compare)');
