<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/prototype/toString/fractionalseconddigits-non-integer.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$time = new \Temporal\PlainTime(12, 34, 56, 987, 650, 0);
$string = $time->toString(['fractionalSecondDigits' => 2.5]);
Assert::sameValue($string, '12:34:56.98', 'fractionalSecondDigits 2.5 floors to 2');
$string = $time->toString(['fractionalSecondDigits' => 9.7]);
Assert::sameValue($string, '12:34:56.987650000', 'fractionalSecondDigits 9.7 floors to 9 and is not out of range');
Assert::throws(\InvalidArgumentException::class, fn() => $time->toString(['fractionalSecondDigits' => -0.6]), 'fractionalSecondDigits -0.6 floors to -1 and is out of range');
