<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/prototype/toString/fractionalseconddigits-auto.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$tests = [[new \Temporal\PlainTime(5, 3, 1), '05:03:01'], [new \Temporal\PlainTime(15, 23), '15:23:00'], [new \Temporal\PlainTime(15, 23, 30), '15:23:30'], [new \Temporal\PlainTime(15, 23, 30, 123, 400), '15:23:30.1234']];
foreach ($tests as [$time, $expected]) {
Assert::sameValue($time->toString(), $expected, 'default is to emit seconds and drop trailing zeroes');
Assert::sameValue($time->toString(['fractionalSecondDigits' => 'auto']), $expected, 'auto is the default');
}
