<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/prototype/toString/options-object.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instance = new \Temporal\PlainTime();
$result1 = $instance->toString(new \stdClass());
Assert::sameValue($result1, '00:00:00', 'options may be an empty plain object');
$result2 = $instance->toString(function () {  });
Assert::sameValue($result2, '00:00:00', 'options may be a function object');
