<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/prototype/toString/roundingmode-ceil.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$time = new \Temporal\Spec\PlainTime(12, 34, 56, 123, 987, 500);
$result1 = $time->toString(['smallestUnit' => 'microsecond', 'roundingMode' => 'ceil']);
Assert::sameValue($result1, '12:34:56.123988', 'roundingMode is ceil (with 6 digits from smallestUnit)');
$result2 = $time->toString(['fractionalSecondDigits' => 6, 'roundingMode' => 'ceil']);
Assert::sameValue($result2, '12:34:56.123988', 'roundingMode is ceil (with 6 digits from fractionalSecondDigits)');
$result3 = $time->toString(['smallestUnit' => 'millisecond', 'roundingMode' => 'ceil']);
Assert::sameValue($result3, '12:34:56.124', 'roundingMode is ceil (with 3 digits from smallestUnit)');
$result4 = $time->toString(['fractionalSecondDigits' => 3, 'roundingMode' => 'ceil']);
Assert::sameValue($result4, '12:34:56.124', 'roundingMode is ceil (with 3 digits from fractionalSecondDigits)');
$result5 = $time->toString(['smallestUnit' => 'second', 'roundingMode' => 'ceil']);
Assert::sameValue($result5, '12:34:57', 'roundingMode is ceil (with 0 digits from smallestUnit)');
$result6 = $time->toString(['fractionalSecondDigits' => 0, 'roundingMode' => 'ceil']);
Assert::sameValue($result6, '12:34:57', 'roundingMode is ceil (with 0 digits from fractionalSecondDigits)');
$result7 = $time->toString(['smallestUnit' => 'minute', 'roundingMode' => 'ceil']);
Assert::sameValue($result7, '12:35', 'roundingMode is ceil (round to minute)');
