<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainDate/prototype/toLocaleString/default-does-not-include-time-and-time-zone-name.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
$plainDate = new \Temporal\Spec\PlainDate(2024, 12, 26);
$result = $plainDate->toLocaleString('en', (object) ['timeZone' => 'UTC']);
Assert::assertTrue(\Temporal\Tests\Test262\Js::includes($result, '2024'), "PlainDate formatted with no options {$result} should include year");
Assert::assertTrue(\Temporal\Tests\Test262\Js::includes($result, '12') || \Temporal\Tests\Test262\Js::includes($result, 'Dec'), "PlainDate formatted with no options {$result} should include month");
Assert::assertTrue(\Temporal\Tests\Test262\Js::includes($result, '26'), "PlainDate formatted with no options {$result} should include day");
Assert::assertTrue(!\Temporal\Tests\Test262\Js::includes($result, '00'), "PlainDate formatted with no options {$result} should not include hour, minute, second");
Assert::assertTrue(!\Temporal\Tests\Test262\Js::includes($result, 'UTC') && !\Temporal\Tests\Test262\Js::includes($result, 'Coordinated Universal Time'), "PlainDate formatted with no options {$result} should not include time zone name");
