<?php

declare(strict_types=1);

// Source: tests/Test262/data/Now/timeZoneId/return-value.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
Assert::sameValue(is_string(\Temporal\Spec\Now::timeZoneId()), true, 'Temporal.Now.timeZoneId() returns a string');
