<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/prototype/monthsInYear/basic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
Assert::sameValue(new \Temporal\PlainDate(1976, 11, 18)->monthsInYear, 12, '');
Assert::sameValue(new \Temporal\PlainDate(1234, 7, 15)->monthsInYear, 12, '');
Assert::sameValue(\Temporal\PlainDate::from('2019-03-18')->monthsInYear, 12, '');
Assert::sameValue(\Temporal\PlainDate::from('2020-06-30')->monthsInYear, 12, '');
