<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/prototype/toString/basic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;

$afterEpoch = new \Temporal\Instant(217_175_010_123_456_789);
Assert::sameValue($afterEpoch->toString(), '1976-11-18T14:23:30.123456789Z', 'basic toString() after epoch');
$beforeEpoch = new \Temporal\Instant(-217_175_010_876_543_211);
Assert::sameValue($beforeEpoch->toString(), '1963-02-13T09:36:29.123456789Z', 'basic toString() before epoch');
