<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/prototype/toString/fractionalseconddigits-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$tests = [[new \Temporal\Spec\Instant(192_258_181_000_000_000), '1976-02-04T05:03:01Z'], [new \Temporal\Spec\Instant(0), '1970-01-01T00:00:00Z'], [new \Temporal\Spec\Instant(30_000_000_000), '1970-01-01T00:00:30Z'], [new \Temporal\Spec\Instant(30_123_400_000), '1970-01-01T00:00:30.1234Z']];
foreach ($tests as $__entry__) {
[$instant, $expected] = array_pad($__entry__, 2, null);
$explicit = $instant->toString([]);
Assert::sameValue($explicit, $expected, 'default fractionalSecondDigits is auto (property present but undefined)');
$implicit = $instant->toString(new \stdClass());
Assert::sameValue($implicit, $expected, 'default fractionalSecondDigits is auto (property not present)');
$lambda = $instant->toString(function () {  });
Assert::sameValue($lambda, $expected, 'default fractionalSecondDigits is auto (property not present, function object)');
}
