<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/prototype/toString/fractionalseconddigits-out-of-range.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
$instant = new \Temporal\Spec\Instant(1_000_000_000_987_650_000);
Assert::throws(\RangeException::class, function () use (&$instant) { return $instant->toString((object) JsUndefined::strip(['fractionalSecondDigits' => -INF])); }, '−∞ is out of range for fractionalSecondDigits');
Assert::throws(\RangeException::class, function () use (&$instant) { return $instant->toString((object) JsUndefined::strip(['fractionalSecondDigits' => -1])); }, '−1 is out of range for fractionalSecondDigits');
Assert::throws(\RangeException::class, function () use (&$instant) { return $instant->toString((object) ['fractionalSecondDigits' => 10]); }, '10 is out of range for fractionalSecondDigits');
Assert::throws(\RangeException::class, function () use (&$instant) { return $instant->toString((object) JsUndefined::strip(['fractionalSecondDigits' => INF])); }, '∞ is out of range for fractionalSecondDigits');
