<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/prototype/toString/get-timezone-throws.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
$instance = new \Temporal\Spec\Instant(0);
$options = new class { public function __get(string $name): mixed { throw new \Temporal\Tests\Test262\Test262Error(); } };
Assert::throws(\Temporal\Tests\Test262\Test262Error::class, function () use (&$instance, &$options) { return $instance->toString($options); }, '');
