<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/prototype/toString/roundingmode-expand.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instant = new \Temporal\Instant(1_000_000_000_123_987_500);
$result1 = $instant->toString(['smallestUnit' => 'microsecond', 'roundingMode' => 'expand']);
Assert::sameValue($result1, '2001-09-09T01:46:40.123988Z', 'roundingMode is expand (with 6 digits from smallestUnit)');
$result2 = $instant->toString(['fractionalSecondDigits' => 6, 'roundingMode' => 'expand']);
Assert::sameValue($result2, '2001-09-09T01:46:40.123988Z', 'roundingMode is expand (with 6 digits from fractionalSecondDigits)');
$result3 = $instant->toString(['smallestUnit' => 'millisecond', 'roundingMode' => 'expand']);
Assert::sameValue($result3, '2001-09-09T01:46:40.124Z', 'roundingMode is expand (with 3 digits from smallestUnit)');
$result4 = $instant->toString(['fractionalSecondDigits' => 3, 'roundingMode' => 'expand']);
Assert::sameValue($result4, '2001-09-09T01:46:40.124Z', 'roundingMode is expand (with 3 digits from fractionalSecondDigits)');
$result5 = $instant->toString(['smallestUnit' => 'second', 'roundingMode' => 'expand']);
Assert::sameValue($result5, '2001-09-09T01:46:41Z', 'roundingMode is expand (with 0 digits from smallestUnit)');
$result6 = $instant->toString(['fractionalSecondDigits' => 0, 'roundingMode' => 'expand']);
Assert::sameValue($result6, '2001-09-09T01:46:41Z', 'roundingMode is expand (with 0 digits from fractionalSecondDigits)');
$result7 = $instant->toString(['smallestUnit' => 'minute', 'roundingMode' => 'expand']);
Assert::sameValue($result7, '2001-09-09T01:47Z', 'roundingMode is expand (round to minute)');
