<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainYearMonth/from/calendarresolvefields-error-ordering-japanese.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
Assert::throws(\TypeError::class, fn() => \Temporal\Spec\PlainYearMonth::from(['calendar' => 'japanese', 'monthCode' => 'M05', 'month' => 12]), 'Missing year throws TypeError before month/monthCode conflict throws RangeError');
Assert::throws(\TypeError::class, fn() => \Temporal\Spec\PlainYearMonth::from(['calendar' => 'japanese', 'year' => 2020]), 'Missing month/monthCode throws TypeError');
Assert::throws(\TypeError::class, fn() => \Temporal\Spec\PlainYearMonth::from(['calendar' => 'japanese', 'monthCode' => 'M05', 'month' => 12]), 'undefined year throws TypeError before month/monthCode conflict throws RangeError');
Assert::throws(\TypeError::class, fn() => \Temporal\Spec\PlainYearMonth::from(['calendar' => 'japanese', 'year' => 2020]), 'undefined month throws TypeError');
Assert::throws(\TypeError::class, fn() => \Temporal\Spec\PlainYearMonth::from(['calendar' => 'japanese', 'year' => 2020]), 'undefined monthCode throws TypeError when month is missing');
Assert::throws(\InvalidArgumentException::class, fn() => \Temporal\Spec\PlainYearMonth::from(['calendar' => 'japanese', 'year' => 2020, 'monthCode' => 'M05', 'month' => 12]), 'month/monthCode conflict throws RangeError when all types are valid');
Assert::throws(\InvalidArgumentException::class, fn() => \Temporal\Spec\PlainYearMonth::from(['calendar' => 'japanese', 'year' => 2020, 'month' => 13], ['overflow' => 'reject']), 'Out-of-range month throws RangeError when all types are valid');
