<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainYearMonth/from/canonicalize-calendar.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
foreach (['2024-06-08[u-ca=islamicc]', ['year' => 1445, 'month' => 12, 'calendar' => 'islamicc']] as $arg) {
$result = \Temporal\Spec\PlainYearMonth::from($arg);
Assert::sameValue($result->calendarId, 'islamic-civil', 'calendar ID is canonicalized');
}
