<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainYearMonth/from/invalid-month-codes-hebrew.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$calendar = 'hebrew';
Assert::throws(\InvalidArgumentException::class, function () use ($calendar) { \Temporal\Spec\PlainYearMonth::from(['year' => 5779, 'monthCode' => 'M13', 'calendar' => $calendar]); }, 'M13 should not be a valid month code');
Assert::throws(\InvalidArgumentException::class, function () use ($calendar) { \Temporal\Spec\PlainYearMonth::from(['year' => 5781, 'monthCode' => 'M13', 'calendar' => $calendar]); }, 'M13 should not be a valid month code');
for ($i = 1; $i <= 12; $i++) {
if ($i === 5) {
Assert::incomplete('untranslatable statement: ContinueStatement');
}
}
