<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainYearMonth/prototype/since/canonicalize-calendar.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instance = new \Temporal\Spec\PlainYearMonth(2024, 6, 'islamic-civil', 8);
foreach (['2024-06-08[u-ca=islamicc]', ['year' => 1445, 'month' => 12, 'calendar' => 'islamicc']] as $arg) {
$result = $instance->since($arg);
Assert::assertTrue($result->blank, 'calendar ID is canonicalized');
}
