<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainYearMonth/prototype/with/basic-indian.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$calendar = 'indian';
$cases = ['year2000' => ['year' => 1921, 'eraYear' => 1921, 'era' => 'shaka', 'month' => 10, 'monthCode' => 'M10', 'calendar' => $calendar], 'year1' => ['year' => -78, 'eraYear' => -78, 'era' => 'shaka', 'month' => 10, 'monthCode' => 'M10', 'calendar' => $calendar]];
foreach ($cases as $name => $result) {
$inCal = \Temporal\Spec\PlainYearMonth::from($result);
$afterWithMonth = $inCal->with(['month' => 1]);
TemporalHelpers::assertPlainYearMonth($afterWithMonth, $inCal->year, 1, 'M01', "{$name} after setting month", $inCal->era, $inCal->eraYear, null);
$afterWithYear = $afterWithMonth->with(['year' => 5860]);
TemporalHelpers::assertPlainYearMonth($afterWithYear, 5860, 1, 'M01', "{$name} after setting year", $inCal->era, 5860, null);
}
