<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainYearMonth/prototype/with/minimum-valid-year-month.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$apr2000 = new \Temporal\Spec\PlainYearMonth(2000, 4, 'gregory');
TemporalHelpers::assertPlainYearMonth($apr2000->with(['year' => -271_821]), -271_821, 4, 'M04', '', 'bce', 271_822);
