<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainYearMonth/prototype/with/mutually-exclusive-fields-japanese.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$options = (object) ['overflow' => 'reject'];
$lastDayOfShowa = \Temporal\Spec\PlainYearMonth::from((object) ['era' => 'showa', 'eraYear' => 64, 'year' => 1989, 'month' => 1, 'monthCode' => 'M01', 'calendar' => 'japanese'], $options);
TemporalHelpers::assertPlainYearMonth($lastDayOfShowa, 1989, 1, 'M01', 'check expected fields', 'showa', 64);
TemporalHelpers::assertPlainYearMonth($lastDayOfShowa->with((object) ['month' => 2], $options), 1989, 2, 'M02', 'month excludes monthCode, era, and eraYear', 'heisei', 1);
TemporalHelpers::assertPlainYearMonth($lastDayOfShowa->with((object) ['monthCode' => 'M03'], $options), 1989, 3, 'M03', 'monthCode excludes month, era, and eraYear', 'heisei', 1);
TemporalHelpers::assertPlainYearMonth($lastDayOfShowa->with((object) ['year' => 1988], $options), 1988, 1, 'M01', 'year excludes era and eraYear (within same era)', 'showa', 63);
TemporalHelpers::assertPlainYearMonth($lastDayOfShowa->with((object) ['year' => 1990], $options), 1990, 1, 'M01', 'year excludes era and eraYear (in a different era)', 'heisei', 2);
Assert::throws(\TypeError::class, function () use (&$lastDayOfShowa) { return $lastDayOfShowa->with((object) ['eraYear' => 1]); }, 'eraYear excludes year and era, and cannot be provided without era');
Assert::throws(\TypeError::class, function () use (&$lastDayOfShowa) { return $lastDayOfShowa->with((object) ['era' => 'heisei']); }, 'era excludes year and eraYear, and cannot be provided without eraYear');
