<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainYearMonth/prototype/with/mutually-exclusive-fields-islamic-tbla.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$options = ['overflow' => 'reject'];
$instance = \Temporal\Spec\PlainYearMonth::from(['year' => 1447, 'monthCode' => 'M12', 'calendar' => 'islamic-tbla'], $options);
TemporalHelpers::assertPlainYearMonth($instance, 1447, 12, 'M12', 'check that all fields are as expected', 'ah', 1447, null);
TemporalHelpers::assertPlainYearMonth($instance->with(['era' => 'bh', 'eraYear' => 1], $options), 0, 12, 'M12', 'era and eraYear together exclude year', 'bh', 1, null);
TemporalHelpers::assertPlainYearMonth($instance->with(['year' => -2], $options), -2, 12, 'M12', 'year excludes era and eraYear', 'bh', 3, null);
TemporalHelpers::assertPlainYearMonth($instance->with(['month' => 5], $options), 1447, 5, 'M05', 'month excludes monthCode', 'ah', 1447, null);
TemporalHelpers::assertPlainYearMonth($instance->with(['monthCode' => 'M05'], $options), 1447, 5, 'M05', 'monthCode excludes month', 'ah', 1447, null);
Assert::throws(\TypeError::class, function () use (&$instance) { return $instance->with(['eraYear' => 1]); }, 'eraYear excludes year and era, and cannot be provided without era');
Assert::throws(\TypeError::class, function () use (&$instance) { return $instance->with(['era' => 'bh']); }, 'era excludes year and eraYear, and cannot be provided without eraYear');
