<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/until/roundingincrement-wrong-type.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$earlier = new \Temporal\PlainDateTime(2000, 5, 2, 12, 34, 56, 987, 654, 321);
$later = new \Temporal\PlainDateTime(2001, 6, 3, 13, 35, 57, 988, 655, 322);
TemporalHelpers::checkRoundingIncrementOptionWrongType(fn($roundingIncrement) => $earlier->until($later, ['roundingIncrement' => $roundingIncrement]), fn($result, $descr) => TemporalHelpers::assertDuration($result, 0, 0, 0, 397, 1, 1, 1, 1, 1, 1, $descr), fn($result, $descr) => TemporalHelpers::assertDuration($result, 0, 0, 0, 397, 1, 1, 1, 1, 1, 0, $descr));
