<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/until/roundingmode-half-boundary.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$yearEarlier1 = new \Temporal\Spec\PlainDateTime(2019, 1, 1, 0, 0, 0, 0, 0, 0);
$yearLater = new \Temporal\Spec\PlainDateTime(2020, 7, 2, 0, 0, 0, 0, 0, 0);
Assert::sameValue($yearEarlier1->until($yearLater)->total(['unit' => 'years', 'relativeTo' => $yearEarlier1]), 1.5, '1.5-year duration is on a 0.5 boundary');
foreach (['trunc', 'floor', 'halfTrunc', 'halfFloor'] as $mode) {
TemporalHelpers::assertDuration($yearEarlier1->until($yearLater, ['smallestUnit' => 'years', 'roundingMode' => $mode]), 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, "1.5 years with {$mode} rounds down to 1");
}
foreach (['ceil', 'expand', 'halfExpand', 'halfCeil', 'halfEven'] as $mode) {
TemporalHelpers::assertDuration($yearEarlier1->until($yearLater, ['smallestUnit' => 'years', 'roundingMode' => $mode]), 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, "1.5 years with {$mode} rounds up to 2");
}
$yearEarlier2 = new \Temporal\Spec\PlainDateTime(2018, 1, 1, 0, 0, 0, 0, 0, 0);
Assert::sameValue($yearEarlier2->until($yearLater)->total(['unit' => 'years', 'relativeTo' => $yearEarlier2]), 2.5, '2.5-year duration is on a 0.5 boundary');
foreach (['trunc', 'floor', 'halfTrunc', 'halfFloor', 'halfEven'] as $mode) {
TemporalHelpers::assertDuration($yearEarlier2->until($yearLater, ['smallestUnit' => 'years', 'roundingMode' => $mode]), 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, "2.5 years with {$mode} rounds down to 2");
}
foreach (['ceil', 'expand', 'halfExpand', 'halfCeil'] as $mode) {
TemporalHelpers::assertDuration($yearEarlier2->until($yearLater, ['smallestUnit' => 'years', 'roundingMode' => $mode]), 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, "2.5 years with {$mode} rounds up to 3");
}
$monthEarlier1 = new \Temporal\Spec\PlainDateTime(2019, 1, 1, 0, 0, 0, 0, 0, 0);
$monthLater = new \Temporal\Spec\PlainDateTime(2019, 2, 15, 0, 0, 0, 0, 0, 0);
Assert::sameValue($monthEarlier1->until($monthLater)->total(['unit' => 'months', 'relativeTo' => $monthEarlier1]), 1.5, '1.5-month duration is on a 0.5 boundary');
foreach (['trunc', 'floor', 'halfTrunc', 'halfFloor'] as $mode) {
TemporalHelpers::assertDuration($monthEarlier1->until($monthLater, ['smallestUnit' => 'months', 'roundingMode' => $mode]), 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, "1.5 months with {$mode} rounds down to 1");
}
foreach (['ceil', 'expand', 'halfExpand', 'halfCeil', 'halfEven'] as $mode) {
TemporalHelpers::assertDuration($monthEarlier1->until($monthLater, ['smallestUnit' => 'months', 'roundingMode' => $mode]), 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, "1.5 months with {$mode} rounds up to 2");
}
$monthEarlier2 = new \Temporal\Spec\PlainDateTime(2018, 12, 1, 0, 0, 0, 0, 0, 0);
Assert::sameValue($monthEarlier2->until($monthLater)->total(['unit' => 'months', 'relativeTo' => $monthEarlier2]), 2.5, '2.5-month duration is on a 0.5 boundary');
foreach (['trunc', 'floor', 'halfTrunc', 'halfFloor', 'halfEven'] as $mode) {
TemporalHelpers::assertDuration($monthEarlier2->until($monthLater, ['smallestUnit' => 'months', 'roundingMode' => $mode]), 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, "2.5 months with {$mode} rounds down to 2");
}
foreach (['ceil', 'expand', 'halfExpand', 'halfCeil'] as $mode) {
TemporalHelpers::assertDuration($monthEarlier2->until($monthLater, ['smallestUnit' => 'months', 'roundingMode' => $mode]), 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, "2.5 months with {$mode} rounds up to 3");
}
$weekStart = new \Temporal\Spec\PlainDateTime(2019, 1, 1, 0, 0, 0, 0, 0, 0);
$weekLater1 = new \Temporal\Spec\PlainDateTime(2019, 1, 11, 12, 0, 0, 0, 0, 0);
$weekLater2 = new \Temporal\Spec\PlainDateTime(2019, 1, 18, 12, 0, 0, 0, 0, 0);
Assert::sameValue($weekStart->until($weekLater1)->total(['unit' => 'weeks', 'relativeTo' => $weekStart]), 1.5, '1.5-week duration is on a 0.5 boundary');
foreach (['trunc', 'floor', 'halfTrunc', 'halfFloor'] as $mode) {
TemporalHelpers::assertDuration($weekStart->until($weekLater1, ['smallestUnit' => 'weeks', 'roundingMode' => $mode]), 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "1.5 weeks with {$mode} rounds down to 1");
}
foreach (['ceil', 'expand', 'halfExpand', 'halfCeil', 'halfEven'] as $mode) {
TemporalHelpers::assertDuration($weekStart->until($weekLater1, ['smallestUnit' => 'weeks', 'roundingMode' => $mode]), 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, "1.5 weeks with {$mode} rounds up to 2");
}
Assert::sameValue($weekStart->until($weekLater2)->total(['unit' => 'weeks', 'relativeTo' => $weekStart]), 2.5, '2.5-week duration is on a 0.5 boundary');
foreach (['trunc', 'floor', 'halfTrunc', 'halfFloor', 'halfEven'] as $mode) {
TemporalHelpers::assertDuration($weekStart->until($weekLater2, ['smallestUnit' => 'weeks', 'roundingMode' => $mode]), 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, "2.5 weeks with {$mode} rounds down to 2");
}
foreach (['ceil', 'expand', 'halfExpand', 'halfCeil'] as $mode) {
TemporalHelpers::assertDuration($weekStart->until($weekLater2, ['smallestUnit' => 'weeks', 'roundingMode' => $mode]), 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, "2.5 weeks with {$mode} rounds up to 3");
}
$dayStart = new \Temporal\Spec\PlainDateTime(2019, 1, 1, 0, 0, 0, 0, 0, 0);
$dayLater1 = new \Temporal\Spec\PlainDateTime(2019, 1, 2, 12, 0, 0, 0, 0, 0);
$dayLater2 = new \Temporal\Spec\PlainDateTime(2019, 1, 3, 12, 0, 0, 0, 0, 0);
Assert::sameValue($dayStart->until($dayLater1)->total(['unit' => 'days', 'relativeTo' => $dayStart]), 1.5, '1.5-day duration is on a 0.5 boundary');
foreach (['trunc', 'floor', 'halfTrunc', 'halfFloor'] as $mode) {
TemporalHelpers::assertDuration($dayStart->until($dayLater1, ['smallestUnit' => 'days', 'roundingMode' => $mode]), 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, "1.5 days with {$mode} rounds down to 1");
}
foreach (['ceil', 'expand', 'halfExpand', 'halfCeil', 'halfEven'] as $mode) {
TemporalHelpers::assertDuration($dayStart->until($dayLater1, ['smallestUnit' => 'days', 'roundingMode' => $mode]), 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, "1.5 days with {$mode} rounds up to 2");
}
Assert::sameValue($dayStart->until($dayLater2)->total(['unit' => 'days', 'relativeTo' => $dayStart]), 2.5, '2.5-day duration is on a 0.5 boundary');
foreach (['trunc', 'floor', 'halfTrunc', 'halfFloor', 'halfEven'] as $mode) {
TemporalHelpers::assertDuration($dayStart->until($dayLater2, ['smallestUnit' => 'days', 'roundingMode' => $mode]), 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, "2.5 days with {$mode} rounds down to 2");
}
foreach (['ceil', 'expand', 'halfExpand', 'halfCeil'] as $mode) {
TemporalHelpers::assertDuration($dayStart->until($dayLater2, ['smallestUnit' => 'days', 'roundingMode' => $mode]), 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, "2.5 days with {$mode} rounds up to 3");
}
$hourStart = new \Temporal\Spec\PlainDateTime(2019, 1, 1, 0, 0, 0, 0, 0, 0);
$hourLater1 = new \Temporal\Spec\PlainDateTime(2019, 1, 1, 1, 30, 0, 0, 0, 0);
$hourLater2 = new \Temporal\Spec\PlainDateTime(2019, 1, 1, 2, 30, 0, 0, 0, 0);
Assert::sameValue($hourStart->until($hourLater1)->total(['unit' => 'hours', 'relativeTo' => $hourStart]), 1.5, '1.5-hour duration is on a 0.5 boundary');
foreach (['trunc', 'floor', 'halfTrunc', 'halfFloor'] as $mode) {
TemporalHelpers::assertDuration($hourStart->until($hourLater1, ['smallestUnit' => 'hours', 'roundingMode' => $mode]), 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, "1.5 hours with {$mode} rounds down to 1");
}
foreach (['ceil', 'expand', 'halfExpand', 'halfCeil', 'halfEven'] as $mode) {
TemporalHelpers::assertDuration($hourStart->until($hourLater1, ['smallestUnit' => 'hours', 'roundingMode' => $mode]), 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, "1.5 hours with {$mode} rounds up to 2");
}
Assert::sameValue($hourStart->until($hourLater2)->total(['unit' => 'hours', 'relativeTo' => $hourStart]), 2.5, '2.5-hour duration is on a 0.5 boundary');
foreach (['trunc', 'floor', 'halfTrunc', 'halfFloor', 'halfEven'] as $mode) {
TemporalHelpers::assertDuration($hourStart->until($hourLater2, ['smallestUnit' => 'hours', 'roundingMode' => $mode]), 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, "2.5 hours with {$mode} rounds down to 2");
}
foreach (['ceil', 'expand', 'halfExpand', 'halfCeil'] as $mode) {
TemporalHelpers::assertDuration($hourStart->until($hourLater2, ['smallestUnit' => 'hours', 'roundingMode' => $mode]), 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, "2.5 hours with {$mode} rounds up to 3");
}
$minStart = new \Temporal\Spec\PlainDateTime(2019, 1, 1, 0, 0, 0, 0, 0, 0);
$minLater1 = new \Temporal\Spec\PlainDateTime(2019, 1, 1, 0, 1, 30, 0, 0, 0);
$minLater2 = new \Temporal\Spec\PlainDateTime(2019, 1, 1, 0, 2, 30, 0, 0, 0);
Assert::sameValue($minStart->until($minLater1)->total(['unit' => 'minutes', 'relativeTo' => $minStart]), 1.5, '1.5-minute duration is on a 0.5 boundary');
foreach (['trunc', 'floor', 'halfTrunc', 'halfFloor'] as $mode) {
TemporalHelpers::assertDuration($minStart->until($minLater1, ['smallestUnit' => 'minutes', 'roundingMode' => $mode]), 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, "1.5 minutes with {$mode} rounds down to 1");
}
foreach (['ceil', 'expand', 'halfExpand', 'halfCeil', 'halfEven'] as $mode) {
TemporalHelpers::assertDuration($minStart->until($minLater1, ['smallestUnit' => 'minutes', 'roundingMode' => $mode]), 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, "1.5 minutes with {$mode} rounds up to 2");
}
Assert::sameValue($minStart->until($minLater2)->total(['unit' => 'minutes', 'relativeTo' => $minStart]), 2.5, '2.5-minute duration is on a 0.5 boundary');
foreach (['trunc', 'floor', 'halfTrunc', 'halfFloor', 'halfEven'] as $mode) {
TemporalHelpers::assertDuration($minStart->until($minLater2, ['smallestUnit' => 'minutes', 'roundingMode' => $mode]), 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, "2.5 minutes with {$mode} rounds down to 2");
}
foreach (['ceil', 'expand', 'halfExpand', 'halfCeil'] as $mode) {
TemporalHelpers::assertDuration($minStart->until($minLater2, ['smallestUnit' => 'minutes', 'roundingMode' => $mode]), 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, "2.5 minutes with {$mode} rounds up to 3");
}
$secStart = new \Temporal\Spec\PlainDateTime(2019, 1, 1, 0, 0, 0, 0, 0, 0);
$secLater1 = new \Temporal\Spec\PlainDateTime(2019, 1, 1, 0, 0, 1, 500, 0, 0);
$secLater2 = new \Temporal\Spec\PlainDateTime(2019, 1, 1, 0, 0, 2, 500, 0, 0);
Assert::sameValue($secStart->until($secLater1)->total(['unit' => 'seconds', 'relativeTo' => $secStart]), 1.5, '1.5-second duration is on a 0.5 boundary');
foreach (['trunc', 'floor', 'halfTrunc', 'halfFloor'] as $mode) {
TemporalHelpers::assertDuration($secStart->until($secLater1, ['smallestUnit' => 'seconds', 'roundingMode' => $mode]), 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, "1.5 seconds with {$mode} rounds down to 1");
}
foreach (['ceil', 'expand', 'halfExpand', 'halfCeil', 'halfEven'] as $mode) {
TemporalHelpers::assertDuration($secStart->until($secLater1, ['smallestUnit' => 'seconds', 'roundingMode' => $mode]), 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, "1.5 seconds with {$mode} rounds up to 2");
}
Assert::sameValue($secStart->until($secLater2)->total(['unit' => 'seconds', 'relativeTo' => $secStart]), 2.5, '2.5-second duration is on a 0.5 boundary');
foreach (['trunc', 'floor', 'halfTrunc', 'halfFloor', 'halfEven'] as $mode) {
TemporalHelpers::assertDuration($secStart->until($secLater2, ['smallestUnit' => 'seconds', 'roundingMode' => $mode]), 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, "2.5 seconds with {$mode} rounds down to 2");
}
foreach (['ceil', 'expand', 'halfExpand', 'halfCeil'] as $mode) {
TemporalHelpers::assertDuration($secStart->until($secLater2, ['smallestUnit' => 'seconds', 'roundingMode' => $mode]), 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, "2.5 seconds with {$mode} rounds up to 3");
}
$msStart = new \Temporal\Spec\PlainDateTime(2019, 1, 1, 0, 0, 0, 0, 0, 0);
$msLater1 = new \Temporal\Spec\PlainDateTime(2019, 1, 1, 0, 0, 0, 1, 500, 0);
$msLater2 = new \Temporal\Spec\PlainDateTime(2019, 1, 1, 0, 0, 0, 2, 500, 0);
Assert::sameValue($msStart->until($msLater1)->total(['unit' => 'milliseconds', 'relativeTo' => $msStart]), 1.5, '1.5-millisecond duration is on a 0.5 boundary');
foreach (['trunc', 'floor', 'halfTrunc', 'halfFloor'] as $mode) {
TemporalHelpers::assertDuration($msStart->until($msLater1, ['smallestUnit' => 'milliseconds', 'roundingMode' => $mode]), 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, "1.5 milliseconds with {$mode} rounds down to 1");
}
foreach (['ceil', 'expand', 'halfExpand', 'halfCeil', 'halfEven'] as $mode) {
TemporalHelpers::assertDuration($msStart->until($msLater1, ['smallestUnit' => 'milliseconds', 'roundingMode' => $mode]), 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, "1.5 milliseconds with {$mode} rounds up to 2");
}
Assert::sameValue($msStart->until($msLater2)->total(['unit' => 'milliseconds', 'relativeTo' => $msStart]), 2.5, '2.5-millisecond duration is on a 0.5 boundary');
foreach (['trunc', 'floor', 'halfTrunc', 'halfFloor', 'halfEven'] as $mode) {
TemporalHelpers::assertDuration($msStart->until($msLater2, ['smallestUnit' => 'milliseconds', 'roundingMode' => $mode]), 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, "2.5 milliseconds with {$mode} rounds down to 2");
}
foreach (['ceil', 'expand', 'halfExpand', 'halfCeil'] as $mode) {
TemporalHelpers::assertDuration($msStart->until($msLater2, ['smallestUnit' => 'milliseconds', 'roundingMode' => $mode]), 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, "2.5 milliseconds with {$mode} rounds up to 3");
}
$usStart = new \Temporal\Spec\PlainDateTime(2019, 1, 1, 0, 0, 0, 0, 0, 0);
$usLater1 = new \Temporal\Spec\PlainDateTime(2019, 1, 1, 0, 0, 0, 0, 1, 500);
$usLater2 = new \Temporal\Spec\PlainDateTime(2019, 1, 1, 0, 0, 0, 0, 2, 500);
Assert::sameValue($usStart->until($usLater1)->total(['unit' => 'microseconds', 'relativeTo' => $usStart]), 1.5, '1.5-microsecond duration is on a 0.5 boundary');
foreach (['trunc', 'floor', 'halfTrunc', 'halfFloor'] as $mode) {
TemporalHelpers::assertDuration($usStart->until($usLater1, ['smallestUnit' => 'microseconds', 'roundingMode' => $mode]), 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, "1.5 microseconds with {$mode} rounds down to 1");
}
foreach (['ceil', 'expand', 'halfExpand', 'halfCeil', 'halfEven'] as $mode) {
TemporalHelpers::assertDuration($usStart->until($usLater1, ['smallestUnit' => 'microseconds', 'roundingMode' => $mode]), 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, "1.5 microseconds with {$mode} rounds up to 2");
}
Assert::sameValue($usStart->until($usLater2)->total(['unit' => 'microseconds', 'relativeTo' => $usStart]), 2.5, '2.5-microsecond duration is on a 0.5 boundary');
foreach (['trunc', 'floor', 'halfTrunc', 'halfFloor', 'halfEven'] as $mode) {
TemporalHelpers::assertDuration($usStart->until($usLater2, ['smallestUnit' => 'microseconds', 'roundingMode' => $mode]), 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, "2.5 microseconds with {$mode} rounds down to 2");
}
foreach (['ceil', 'expand', 'halfExpand', 'halfCeil'] as $mode) {
TemporalHelpers::assertDuration($usStart->until($usLater2, ['smallestUnit' => 'microseconds', 'roundingMode' => $mode]), 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, "2.5 microseconds with {$mode} rounds up to 3");
}
