<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/add/precision-exact-mathematical-values.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;

$duration1 = \Temporal\Duration::from(['microseconds' => 9_007_199_254_740_991 + 1, 'nanoseconds' => 0]);
$duration2 = \Temporal\Duration::from(['microseconds' => 1, 'nanoseconds' => 1000]);
TemporalHelpers::assertDuration(
    $duration1->add($duration2),
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    9_007_199_254_740_994,
    0,
    'duration1.add(duration2)',
);
