<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/from/argument-string-too-many-decimals.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$invalidStrings = ['1970-01-01T00:00:00.1234567891Z[UTC]', '1970-01-01T00:00:00.1234567890Z[UTC]', '1970-01-01T00+00:00:00.0000000000Z[UTC]'];
foreach ($invalidStrings as $arg) {
Assert::incomplete('\\\\Temporal\\\\ZonedDateTime::from() is not yet implemented');
}
