<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/from/argument-propertybag-calendar-string.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$calendar = 'iso8601';
$timeZone = 'UTC';
$arg = ['year' => 1970, 'monthCode' => 'M01', 'day' => 1, 'timeZone' => $timeZone, 'calendar' => $calendar];
$result = \Temporal\ZonedDateTime::from($arg);
Assert::sameValue($result->calendarId, 'iso8601', "Calendar created from string \"{$calendar}\"");
Assert::sameValue($result->calendarId, 'iso8601', 'calendar string is iso8601');
