<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/from/bad-disambiguation.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
foreach (['', 'EARLIER', 'balance'] as $disambiguation) {
Assert::throws(\InvalidArgumentException::class, fn() => \Temporal\Spec\ZonedDateTime::from('2020-11-01T04:00[-08:00]', ['disambiguation' => $disambiguation]), '');
}
