<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/from/disambiguation-wrong-type.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$datetime = new \Temporal\ZonedDateTime(1_000_000_000_987_654_321, 'UTC');
Assert::incomplete('\\Temporal\\ZonedDateTime::from() is not yet implemented');
