<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/from/infinity-throws-rangeerror.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$base = ['year' => 2000, 'month' => 5, 'day' => 2, 'hour' => 15, 'minute' => 30, 'second' => 45, 'millisecond' => 987, 'microsecond' => 654, 'nanosecond' => 321, 'timeZone' => 'UTC'];
foreach ([INF, -INF] as $inf) {
foreach (['year', 'month', 'day', 'hour', 'minute', 'second', 'millisecond', 'microsecond', 'nanosecond'] as $prop) {
foreach (['constrain', 'reject'] as $overflow) {
Assert::throws(\InvalidArgumentException::class, fn() => \Temporal\ZonedDateTime::from(array_merge($base, [$prop => $inf]), ['overflow' => $overflow]), "{$prop} property cannot be {$inf} (overflow {$overflow}");
$calls = [];
Assert::incomplete('TemporalHelpers.toPrimitiveObserver() is not yet implemented');
}
}
}
