<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/from/leap-second.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$arg = '2016-12-31T23:59:60+00:00[UTC]';
Assert::incomplete('\\Temporal\\ZonedDateTime::from() is not yet implemented');
