<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/from/month-code-wrong-type.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
$monthCodeValues = [5, 5, false, \Temporal\Tests\Test262\JsSymbol::singleton(), null, JsUndefined::strip(['toString' => fn() => 5])];
$year = 2026;
foreach ($monthCodeValues as $monthCode) {
if ($monthCode === null) { continue; }
Assert::throws(\TypeError::class, function () use (&$year, &$monthCode) { return \Temporal\Spec\ZonedDateTime::from(JsUndefined::strip(['year' => $year, 'monthCode' => $monthCode, 'day' => 1, 'hour' => 12, 'minute' => 34, 'timeZone' => 'UTC'])); }, (false ? 'Symbol should be rejected as month code' : "month code {$monthCode} should be rejected"));
}
