<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/from/overflow-wrong-type.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
use Temporal\Tests\Test262\TemporalHelpers;
$validValues = [new \Temporal\Spec\ZonedDateTime(1_000_000_000_987_654_321, 'UTC'), '2001-09-09T01:46:40.987654321+00:00[UTC]'];
foreach ($validValues as $value) {
TemporalHelpers::checkStringOptionWrongType('overflow', 'constrain', function ($overflow) use (&$value) { return \Temporal\Spec\ZonedDateTime::from($value, JsUndefined::strip(['overflow' => $overflow])); }, fn($result, $descr) => Assert::sameValue($result->epochNanoseconds, 1_000_000_000_987_654_321, $descr));
}
$propertyBag = ['year' => 2001, 'month' => 9, 'day' => 9, 'hour' => 1, 'minute' => 46, 'second' => 40, 'timeZone' => 'UTC'];
Assert::throws(\RangeException::class, function () use (&$propertyBag) { return \Temporal\Spec\ZonedDateTime::from($propertyBag, ['overflow' => null]); }, 'null');
Assert::throws(\RangeException::class, function () use (&$propertyBag) { return \Temporal\Spec\ZonedDateTime::from($propertyBag, ['overflow' => true]); }, 'true');
Assert::throws(\RangeException::class, function () use (&$propertyBag) { return \Temporal\Spec\ZonedDateTime::from($propertyBag, ['overflow' => false]); }, 'false');
Assert::throws(\TypeError::class, function () use (&$propertyBag) { return \Temporal\Spec\ZonedDateTime::from($propertyBag, JsUndefined::strip(['overflow' => \Temporal\Tests\Test262\JsSymbol::singleton()])); }, 'symbol');
Assert::throws(\RangeException::class, function () use (&$propertyBag) { return \Temporal\Spec\ZonedDateTime::from($propertyBag, ['overflow' => 2]); }, 'bigint');
Assert::throws(\RangeException::class, function () use (&$propertyBag) { return \Temporal\Spec\ZonedDateTime::from($propertyBag, ['overflow' => 2]); }, 'number');
Assert::throws(\RangeException::class, function () use (&$propertyBag) { return \Temporal\Spec\ZonedDateTime::from($propertyBag, JsUndefined::strip(['overflow' => []])); }, 'plain object');
$expected = ['get overflow.toString', 'call overflow.toString'];
$actual = [];
$observer = TemporalHelpers::toPrimitiveObserver($actual, 'constrain', 'overflow');
$result = \Temporal\Spec\ZonedDateTime::from($propertyBag, JsUndefined::strip(['overflow' => $observer]));
Assert::sameValue($result->epochNanoseconds, 1_000_000_000_000_000_000, 'object with toString');
// JS-only (observer call-order check, tracker is empty in PHP): assert.compareArray(actual, expected, "order of operations");
