<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/fromEpochMilliseconds/limits.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$limit = 8_640_000_000_000_000;
Assert::throws(\InvalidArgumentException::class, function () use (&$limit) { return \Temporal\Spec\Instant::fromEpochMilliseconds(-$limit - 1); }, '');
Assert::throws(\InvalidArgumentException::class, function () use (&$limit) { return \Temporal\Spec\Instant::fromEpochMilliseconds($limit + 1); }, '');
TemporalHelpers::assertInstantsEqual(\Temporal\Spec\Instant::fromEpochMilliseconds(-$limit), \Temporal\Spec\Instant::from('-271821-04-20T00:00:00Z'));
TemporalHelpers::assertInstantsEqual(\Temporal\Spec\Instant::fromEpochMilliseconds($limit), \Temporal\Spec\Instant::from('+275760-09-13T00:00:00Z'));
