<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainMonthDay/prototype/toString/calendarname-critical.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$monthday = new \Temporal\PlainMonthDay(5, 2);
$result = $monthday->toString(['calendarName' => 'critical']);
Assert::sameValue($result, '1972-05-02[!u-ca=iso8601]', "built-in ISO calendar for calendarName = critical");
