<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainMonthDay/prototype/toPlainDate/order-of-operations.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$expected = ['get fields.year', 'get fields.year.valueOf', 'call fields.year.valueOf'];
$actual = [];
$fields = TemporalHelpers::propertyBagObserver($actual, ['year' => 1.7, 'month' => 1.7, 'monthCode' => 'M01', 'day' => 1.7, 'calendar' => 'iso8601'], 'fields', ['calendar']);
$pmd = new \Temporal\Spec\PlainMonthDay(5, 2);
$pmd->toPlainDate($fields);
// JS-only (observer call-order check, tracker is empty in PHP): assert.compareArray(actual, expected, "order of operations");
\PHPUnit\Framework\Assert::assertTrue(true, 'Script completed without throwing');
