<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainMonthDay/prototype/equals/argument-string.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$instance = new \Temporal\PlainMonthDay(10, 1);
foreach ($TemporalHelpers->ISO->plainMonthDayStringsValid() as $arg) {
$result = $instance->equals($arg);
Assert::sameValue($result, true, "\"{$arg}\" is a valid PlainMonthDay string");
}
