<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/prototype/since/largestunit.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$thePast = new \Temporal\Instant(1_234_567_890_123_456_789);
$theFuture = new \Temporal\Instant(2_345_678_901_234_567_890);
Assert::incomplete('Duration::since() is not yet implemented');
