<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/prototype/since/largestunit-wrong-type.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$earlier = new \Temporal\Spec\Instant(1_000_000_000_000_000_000);
$later = new \Temporal\Spec\Instant(1_000_090_061_987_654_321);
TemporalHelpers::checkStringOptionWrongType('largestUnit', 'hour', fn($largestUnit) => $later->since($earlier, ['largestUnit' => $largestUnit]), fn($result, $descr) => TemporalHelpers::assertDuration($result, 0, 0, 0, 0, 25, 1, 1, 987, 654, 321, $descr));
