<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/prototype/since/largestunit-smallestunit-mismatch.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$earlier = new \Temporal\Instant(1_000_000_000_000_000_000);
$later = new \Temporal\Instant(1_000_090_061_987_654_321);
$units = ['hours', 'minutes', 'seconds', 'milliseconds', 'microseconds', 'nanoseconds'];
for ($largestIdx = 1; $largestIdx < count($units); $largestIdx++) {
for ($smallestIdx = 0; $smallestIdx < $largestIdx; $smallestIdx++) {
$largestUnit = $units[$largestIdx];
$smallestUnit = $units[$smallestIdx];
Assert::throws(\InvalidArgumentException::class, fn() => $later->since($earlier, ['largestUnit' => $largestUnit, 'smallestUnit' => $smallestUnit]), '');
}
}
