<?php

declare(strict_types=1);

// Source: tests/Test262/data/Instant/prototype/since/year-zero.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$invalidStrings = ['-000000-03-30T00:45Z', '-000000-03-30T01:45+01:00', '-000000-03-30T01:45:00+00:00[UTC]'];
$instance = new \Temporal\Spec\Instant(0);
foreach ($invalidStrings as $arg) {
Assert::throws(\InvalidArgumentException::class, function () use (&$instance, &$arg) { return $instance->since($arg); }, 'reject minus zero as extended year');
}
