<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainDate/prototype/toString/calendarname-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$tests = [[[], '2000-05-02', 'built-in ISO'], [['gregory'], '2000-05-02[u-ca=gregory]', 'built-in Gregorian']];
foreach ($tests as $__entry__) {
[$args, $expected, $description] = array_pad($__entry__, 3, null);
$date = new \Temporal\Spec\PlainDate(2000, 5, 2, ...$args);
$result = $date->toString([]);
Assert::sameValue($result, $expected, "default calendarName option is auto with {$description} calendar");
}
