<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/toPlainDateTime/balance-negative-time-units.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$datetime = new \Temporal\ZonedDateTime(1001, '-00:02');
$pdt = $datetime->toPlainDateTime();
TemporalHelpers::assertPlainDateTime($pdt, 1969, 12, 'M12', 31, 23, 58, 0, 0, 1, 1);
