<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/toPlainDateTime/basic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$zdtEpoch = new \Temporal\ZonedDateTime(0, 'UTC');
TemporalHelpers::assertPlainDateTime($zdtEpoch->toPlainDateTime(), 1970, 1, 'M01', 1, 0, 0, 0, 0, 0, 0, 'epoch result');
Assert::incomplete('\\Temporal\\ZonedDateTime::from() is not yet implemented');
