<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/ZonedDateTime/prototype/until/argument-propertybag-timezone-string-datetime.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$expectedTimeZone = 'America/Vancouver';
$instance = new \Temporal\Spec\ZonedDateTime(0, $expectedTimeZone);
$timeZone = '2021-08-19T17:30[America/Vancouver]';
$instance->until(['year' => 2020, 'month' => 5, 'day' => 2, 'timeZone' => $timeZone]);
$timeZone = '2021-08-19T17:30Z[America/Vancouver]';
$instance->until(['year' => 2020, 'month' => 5, 'day' => 2, 'timeZone' => $timeZone]);
$timeZone = '2021-08-19T17:30-07:00[America/Vancouver]';
$instance->until(['year' => 2020, 'month' => 5, 'day' => 2, 'timeZone' => $timeZone]);
\PHPUnit\Framework\Assert::assertTrue(true, 'Script completed without throwing');
