<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/ZonedDateTime/prototype/until/chinese-calendar-dates.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$calendar = 'chinese';
$durationCases = ['days' => ['duration' => ['days' => 280], 'result' => ['year' => 2000, 'month' => 10, 'monthCode' => 'M10', 'day' => 16], 'startDate' => ['year' => 2000, 'month' => 1, 'day' => 1]], 'weeks' => ['duration' => ['weeks' => 40], 'result' => ['year' => 2000, 'month' => 10, 'monthCode' => 'M10', 'day' => 16], 'startDate' => ['year' => 2000, 'month' => 1, 'day' => 1]], 'months' => ['duration' => ['months' => 6], 'result' => ['year' => 2001, 'month' => 6, 'monthCode' => 'M05', 'day' => 1], 'startDate' => ['year' => 2000, 'month' => 12, 'day' => 1]], 'years' => ['duration' => ['years' => 3, 'months' => 6, 'days' => 17], 'result' => ['year' => 2001, 'month' => 6, 'monthCode' => 'M05', 'day' => 18], 'startDate' => ['year' => 1997, 'monthCode' => 'M12', 'day' => 1]]];
foreach ($durationCases as $unit => $__unknown__) {
$duration = \Temporal\Spec\Duration::from($duration);
$start = \Temporal\Spec\ZonedDateTime::from(array_merge($startDate, ['timeZone' => 'UTC', 'calendar' => $calendar]));
$end = $start->add($duration);
$diff = $start->until($end, ['largestUnit' => $unit]);
TemporalHelpers::assertDurationsEqual($diff, $duration, "{$unit}");
}
