<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/ZonedDateTime/prototype/until/era-boundary-islamic-tbla.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$calendar = 'islamic-tbla';
$options = ['overflow' => 'reject'];
$bh5 = \Temporal\Spec\ZonedDateTime::from(['era' => 'bh', 'eraYear' => 5, 'monthCode' => 'M06', 'day' => 15, 'hour' => 12, 'minute' => 34, 'timeZone' => 'UTC', 'calendar' => $calendar], $options);
$bh2 = \Temporal\Spec\ZonedDateTime::from(['era' => 'bh', 'eraYear' => 2, 'monthCode' => 'M12', 'day' => 1, 'hour' => 12, 'minute' => 34, 'timeZone' => 'UTC', 'calendar' => $calendar], $options);
$bh1 = \Temporal\Spec\ZonedDateTime::from(['era' => 'bh', 'eraYear' => 1, 'monthCode' => 'M06', 'day' => 15, 'hour' => 12, 'minute' => 34, 'timeZone' => 'UTC', 'calendar' => $calendar], $options);
$ah1 = \Temporal\Spec\ZonedDateTime::from(['era' => 'ah', 'eraYear' => 1, 'monthCode' => 'M06', 'day' => 15, 'hour' => 12, 'minute' => 34, 'timeZone' => 'UTC', 'calendar' => $calendar], $options);
$ah2 = \Temporal\Spec\ZonedDateTime::from(['era' => 'ah', 'eraYear' => 2, 'monthCode' => 'M01', 'day' => 1, 'hour' => 12, 'minute' => 34, 'timeZone' => 'UTC', 'calendar' => $calendar], $options);
$ah5 = \Temporal\Spec\ZonedDateTime::from(['era' => 'ah', 'eraYear' => 5, 'monthCode' => 'M06', 'day' => 15, 'hour' => 12, 'minute' => 34, 'timeZone' => 'UTC', 'calendar' => $calendar], $options);
$tests = [[$bh5, $ah5, [9, 0, 0, 0, '9y  from 5 BH to 5 AH (no year 0)'], [0, 108, 0, 0, '108mo  from 5 BH to 5 AH (no year 0)']], [$ah5, $bh5, [-9, 0, 0, 0, '-9y backwards  from 5 BH to 5 AH (no year 0)'], [0, -108, 0, 0, '-108mo backwards  from 5 BH to 5 AH (no year 0)']], [$bh1, $ah1, [1, 0, 0, 0, '1y from 1 BH to 1 AH'], [0, 12, 0, 0, '12mo from 1 BH to 1 AH']], [$ah1, $bh1, [-1, 0, 0, 0, '-1y backwards from 1 BH to 1 AH'], [0, -12, 0, 0, '-12mo backwards from 1 BH to 1 AH']], [$bh2, $ah2, [2, 1, 0, 0, '2y 1mo from 2 BH Dec to 2 AH Jan'], [0, 25, 0, 0, '25mo from 2 BH Dec to 2 AH Jan']], [$ah2, $bh2, [-2, -1, 0, 0, '-2y -1mo backwards from 2 BH Dec to 2 AH Jan'], [0, -25, 0, 0, '-25mo backwards from 2 BH Dec to 2 AH Jan']]];
foreach ($tests as $__entry__) {
[$one, $two, $yearsTest, $monthsTest] = array_pad($__entry__, 4, null);
[$years, $months, $weeks, $days, $descr] = array_pad($yearsTest, 5, null);
$result = $one->until($two, ['largestUnit' => 'years']);
TemporalHelpers::assertDuration($result, $years, $months, $weeks, $days, 0, 0, 0, 0, 0, 0, $descr);
[$years, $months, $weeks, $days, $descr] = $monthsTest;
$result = $one->until($two, ['largestUnit' => 'months']);
TemporalHelpers::assertDuration($result, $years, $months, $weeks, $days, 0, 0, 0, 0, 0, 0, $descr);
$oneISO = $one->withCalendar('iso8601');
$twoISO = $two->withCalendar('iso8601');
$resultWeeks = $one->until($two, ['largestUnit' => 'weeks']);
$resultWeeksISO = $oneISO->until($twoISO, ['largestUnit' => 'weeks']);
TemporalHelpers::assertDurationsEqual($resultWeeks, $resultWeeksISO, "{$one->year}-{$one->monthCode}-{$one->day} : {$two->year}-{$two->monthCode}-{$two->day} largestUnit weeks");
$resultDays = $one->until($two);
$resultDaysISO = $oneISO->until($twoISO);
TemporalHelpers::assertDurationsEqual($resultDays, $resultDaysISO, "{$one->year}-{$one->monthCode}-{$one->day} : {$two->year}-{$two->monthCode}-{$two->day} largestUnit days");
}
