<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/equals/argument-cast.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$nov94 = \Temporal\Spec\PlainYearMonth::from('1994-11');
Assert::sameValue($nov94->equals(['year' => 2013, 'month' => 6]), false, 'object');
Assert::sameValue($nov94->equals(['year' => 1994, 'month' => 11]), true, 'object');
Assert::sameValue($nov94->equals('2013-06'), false, 'string');
Assert::sameValue($nov94->equals('1994-11'), true, 'string');
Assert::throws(\TypeError::class, fn() => $nov94->equals(['year' => 2013]), 'missing property');
