<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/from/argument-propertybag-calendar-case-insensitive.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$arg = ['year' => 2019, 'monthCode' => 'M06', 'calendar' => 'IsO8601'];
$result = \Temporal\Spec\PlainYearMonth::from($arg);
TemporalHelpers::assertPlainYearMonth($result, 2019, 6, 'M06', 'Calendar is case-insensitive');
$arg['calendar'] = 'İSO8601';
Assert::throws(\InvalidArgumentException::class, function () use (&$arg) { return \Temporal\Spec\PlainYearMonth::from($arg); }, 'calendar ID is capital dotted I is not lowercased');
