<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/from/argument-string-invalid.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
use Temporal\Tests\Test262\TemporalHelpers;
foreach (TemporalHelpers::isoPlainYearMonthStringsInvalid() as $input) {
Assert::throws(\RangeException::class, function () use (&$input) { return \Temporal\Spec\PlainYearMonth::from($input, (object) ['overflow' => 'reject']); }, '');
Assert::throws(\RangeException::class, function () use (&$input) { return \Temporal\Spec\PlainYearMonth::from($input, (object) ['overflow' => 'constrain']); }, '');
}
