<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/from/argument-propertybag-calendar-leap-second.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$calendar = '2016-12-31T23:59:60';
$arg = ['year' => 2019, 'monthCode' => 'M06', 'calendar' => $calendar];
$result = \Temporal\Spec\PlainYearMonth::from($arg);
TemporalHelpers::assertPlainYearMonth($result, 2019, 6, 'M06', 'leap second is a valid ISO string for calendar');
