<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/from/infinity-throws-rangeerror.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$base = ['year' => 2000, 'month' => 5];
foreach ([INF, -INF] as $inf) {
foreach (['year', 'month'] as $prop) {
foreach (['constrain', 'reject'] as $overflow) {
Assert::throws(\InvalidArgumentException::class, function () use (&$base, &$prop, &$inf, &$overflow) { return \Temporal\Spec\PlainYearMonth::from(array_merge($base, [$prop => $inf]), ['overflow' => $overflow]); }, "{$prop} property cannot be {$inf} (overflow {$overflow}");
$calls = [];
Assert::incomplete('TemporalHelpers.toPrimitiveObserver() is not yet implemented');
}
}
}
