<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/from/overflow-wrong-type.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$validValues = [new \Temporal\PlainYearMonth(2000, 5), ['year' => 2000, 'month' => 5], '2000-05'];
foreach ($validValues as $value) {
TemporalHelpers::checkStringOptionWrongType('overflow', 'constrain', fn($overflow) => \Temporal\PlainYearMonth::from($value, ['overflow' => $overflow]), fn($result, $descr) => TemporalHelpers::assertPlainYearMonth($result, 2000, 5, 'M05', $descr));
}
