<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/from/year-zero.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$invalidStrings = ['-000000-06', '-000000-06-24', '-000000-06-24T15:43:27', '-000000-06-24T15:43:27+01:00', '-000000-06-24T15:43:27+00:00[UTC]'];
foreach ($invalidStrings as $arg) {
Assert::throws(\InvalidArgumentException::class, fn() => \Temporal\Spec\PlainYearMonth::from($arg), 'reject minus zero as extended year');
}
