<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/getTimeZoneTransition/wrong-type.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
$zdt = new \Temporal\Spec\ZonedDateTime(0, 'UTC');
$badValues = [false, 42, 55, \Temporal\Tests\Test262\JsSymbol::singleton(), null];
Assert::incomplete('BigInt literal in wrong-type for-of data table; Number-vs-BigInt distinction not representable in PHP');
