<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/ZonedDateTime/prototype/add/constrain-day-ethioaa.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$calendar = 'ethioaa';
$options = ['overflow' => 'reject'];
$common1230 = \Temporal\Spec\ZonedDateTime::from(['year' => 7514, 'monthCode' => 'M12', 'day' => 30, 'hour' => 12, 'minute' => 34, 'timeZone' => 'UTC', 'calendar' => $calendar], $options);
$leap0130 = \Temporal\Spec\ZonedDateTime::from(['year' => 7515, 'monthCode' => 'M01', 'day' => 30, 'hour' => 12, 'minute' => 34, 'timeZone' => 'UTC', 'calendar' => $calendar], $options);
$leap1230 = \Temporal\Spec\ZonedDateTime::from(['year' => 7515, 'monthCode' => 'M12', 'day' => 30, 'hour' => 12, 'minute' => 34, 'timeZone' => 'UTC', 'calendar' => $calendar], $options);
$common0130 = \Temporal\Spec\ZonedDateTime::from(['year' => 7516, 'monthCode' => 'M01', 'day' => 30, 'hour' => 12, 'minute' => 34, 'timeZone' => 'UTC', 'calendar' => $calendar], $options);
$months1 = new \Temporal\Spec\Duration(0, 1);
$months1n = new \Temporal\Spec\Duration(0, -1);
TemporalHelpers::assertPlainDateTime($common1230->add($months1)->toPlainDateTime(), 7514, 13, 'M13', 5, 12, 34, 0, 0, 0, 0, 'Adding 1 month to last day of Nahase constrains to day 5 of common-year epagomenal month', 'aa', 7514);
Assert::throws(\InvalidArgumentException::class, function () use (&$common1230, &$months1, &$options) { $common1230->add($months1, $options); }, 'Adding 1 month to last day of Nahase rejects in common year');
TemporalHelpers::assertPlainDateTime($leap1230->add($months1)->toPlainDateTime(), 7515, 13, 'M13', 6, 12, 34, 0, 0, 0, 0, 'Adding 1 month to last day of Nahase constrains to day 6 of leap-year epagomenal month', 'aa', 7515);
Assert::throws(\InvalidArgumentException::class, function () use (&$leap1230, &$months1, &$options) { $leap1230->add($months1, $options); }, 'Adding 1 month to last day of Nahase rejects in leap year');
TemporalHelpers::assertPlainDateTime($leap0130->add($months1n)->toPlainDateTime(), 7514, 13, 'M13', 5, 12, 34, 0, 0, 0, 0, 'Subtracting 1 month from last day of Maskaram constrains to day 5 of common-year epagomenal month', 'aa', 7514);
Assert::throws(\InvalidArgumentException::class, function () use (&$leap0130, &$months1n, &$options) { $leap0130->add($months1n, $options); }, 'Subtracting 1 month from last day of Maskaram rejects in common year');
TemporalHelpers::assertPlainDateTime($common0130->add($months1n)->toPlainDateTime(), 7515, 13, 'M13', 6, 12, 34, 0, 0, 0, 0, 'Subtracting 1 month from last day of Maskaram constrains to day 6 of leap-year epagomenal month', 'aa', 7515);
Assert::throws(\InvalidArgumentException::class, function () use (&$common0130, &$months1n, &$options) { $common0130->add($months1n, $options); }, 'Subtracting 1 month from last day of Maskaram rejects in leap year');
