<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/toString/calendarname-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$yearmonth = new \Temporal\PlainYearMonth(2000, 5);
$result = $yearmonth->toString([]);
Assert::sameValue($result, '2000-05', "default calendarName option is auto with built-in ISO calendar");
