<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/toString/calendarname-critical.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$yearmonth = new \Temporal\Spec\PlainYearMonth(2000, 5);
$result = $yearmonth->toString(['calendarName' => 'critical']);
Assert::sameValue($result, '2000-05-01[!u-ca=iso8601]', "built-in ISO calendar for calendarName = critical");
