<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainYearMonth/prototype/toString/order-of-operations.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
use Temporal\Tests\Test262\TemporalHelpers;
$expected = ['get options.calendarName', 'get options.calendarName.toString', 'call options.calendarName.toString'];
$actual = [];
$instance = new \Temporal\Spec\PlainYearMonth(2000, 5);
$options = TemporalHelpers::propertyBagObserver($actual, (object) ['calendarName' => 'auto'], 'options');
$instance->toString($options);
// JS-only (observer call-order check, tracker is empty in PHP): assert.compareArray(actual, expected, "order of operations");
\PHPUnit\Framework\Assert::assertTrue(true, 'Script completed without throwing');
