<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/round/roundingmode-halfexpand-is-default.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$dt = new \Temporal\PlainDateTime(1976, 11, 18, 14, 23, 30, 123, 456, 789);
$units = ['day' => [1976, 11, 'M11', 19, 0, 0, 0, 0, 0, 0], 'hour' => [1976, 11, 'M11', 18, 14, 0, 0, 0, 0, 0], 'minute' => [1976, 11, 'M11', 18, 14, 24, 0, 0, 0, 0], 'second' => [1976, 11, 'M11', 18, 14, 23, 30, 0, 0, 0], 'millisecond' => [1976, 11, 'M11', 18, 14, 23, 30, 123, 0, 0], 'microsecond' => [1976, 11, 'M11', 18, 14, 23, 30, 123, 457, 0], 'nanosecond' => [1976, 11, 'M11', 18, 14, 23, 30, 123, 456, 789]];
$expected = [1976, 11, 'M11', 18, 0, 0, 0, 0, 0, 0];
foreach ($units as $unit => $expected) {
TemporalHelpers::assertPlainDateTime($dt->round(['smallestUnit' => $unit]), ...[...$expected, "halfExpand is the default (smallest unit = {$unit}, rounding mode absent)"]);
}
