<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/prototype/round/roundingmode-halfEven.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$instance = new \Temporal\Spec\PlainDateTime(1976, 11, 18, 14, 23, 30, 123, 987, 500);
$expected = [['day', [1976, 11, 'M11', 19]], ['hour', [1976, 11, 'M11', 18, 14]], ['minute', [1976, 11, 'M11', 18, 14, 24]], ['second', [1976, 11, 'M11', 18, 14, 23, 30]], ['millisecond', [1976, 11, 'M11', 18, 14, 23, 30, 124]], ['microsecond', [1976, 11, 'M11', 18, 14, 23, 30, 123, 988]], ['nanosecond', [1976, 11, 'M11', 18, 14, 23, 30, 123, 987, 500]]];
$roundingMode = 'halfEven';
foreach ($expected as $__entry__) {
[$smallestUnit, $expected] = array_pad($__entry__, 2, null);
[$y, $mon, $mc, $d, $h, $min, $s, $ms, $µs, $ns] = array_pad($expected, 10, null);
$h = $h ?? 0;
$min = $min ?? 0;
$s = $s ?? 0;
$ms = $ms ?? 0;
$µs = $µs ?? 0;
$ns = $ns ?? 0;
TemporalHelpers::assertPlainDateTime($instance->round(['smallestUnit' => $smallestUnit, 'roundingMode' => $roundingMode]), $y, $mon, $mc, $d, $h, $min, $s, $ms, $µs, $ns, "rounds to {$smallestUnit} (roundingMode = {$roundingMode})");
}
