<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainDateTime/prototype/since/leap-year-japanese.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$calendar = 'japanese';
$options = ['overflow' => 'reject'];
$date19600216 = \Temporal\Spec\PlainDateTime::from(['year' => 1960, 'monthCode' => 'M02', 'day' => 16, 'hour' => 12, 'minute' => 34, 'calendar' => $calendar], $options);
$date20190101 = \Temporal\Spec\PlainDateTime::from(['year' => 2019, 'monthCode' => 'M01', 'day' => 1, 'hour' => 12, 'minute' => 34, 'calendar' => $calendar], $options);
$date20190201 = \Temporal\Spec\PlainDateTime::from(['year' => 2019, 'monthCode' => 'M02', 'day' => 1, 'hour' => 12, 'minute' => 34, 'calendar' => $calendar], $options);
$date20190301 = \Temporal\Spec\PlainDateTime::from(['year' => 2019, 'monthCode' => 'M03', 'day' => 1, 'hour' => 12, 'minute' => 34, 'calendar' => $calendar], $options);
$date20190601 = \Temporal\Spec\PlainDateTime::from(['year' => 2019, 'monthCode' => 'M06', 'day' => 1, 'hour' => 12, 'minute' => 34, 'calendar' => $calendar], $options);
$date20200101 = \Temporal\Spec\PlainDateTime::from(['year' => 2020, 'monthCode' => 'M01', 'day' => 1, 'hour' => 12, 'minute' => 34, 'calendar' => $calendar], $options);
$date20200201 = \Temporal\Spec\PlainDateTime::from(['year' => 2020, 'monthCode' => 'M02', 'day' => 1, 'hour' => 12, 'minute' => 34, 'calendar' => $calendar], $options);
$date20200301 = \Temporal\Spec\PlainDateTime::from(['year' => 2020, 'monthCode' => 'M03', 'day' => 1, 'hour' => 12, 'minute' => 34, 'calendar' => $calendar], $options);
$date20200315 = \Temporal\Spec\PlainDateTime::from(['year' => 2020, 'monthCode' => 'M03', 'day' => 15, 'hour' => 12, 'minute' => 34, 'calendar' => $calendar], $options);
$date20200601 = \Temporal\Spec\PlainDateTime::from(['year' => 2020, 'monthCode' => 'M06', 'day' => 1, 'hour' => 12, 'minute' => 34, 'calendar' => $calendar], $options);
$date20210101 = \Temporal\Spec\PlainDateTime::from(['year' => 2021, 'monthCode' => 'M01', 'day' => 1, 'hour' => 12, 'minute' => 34, 'calendar' => $calendar], $options);
$date20210107 = \Temporal\Spec\PlainDateTime::from(['year' => 2021, 'monthCode' => 'M01', 'day' => 7, 'hour' => 12, 'minute' => 34, 'calendar' => $calendar], $options);
$date20210201 = \Temporal\Spec\PlainDateTime::from(['year' => 2021, 'monthCode' => 'M02', 'day' => 1, 'hour' => 12, 'minute' => 34, 'calendar' => $calendar], $options);
$date20210228 = \Temporal\Spec\PlainDateTime::from(['year' => 2021, 'monthCode' => 'M02', 'day' => 28, 'hour' => 12, 'minute' => 34, 'calendar' => $calendar], $options);
$date20210307 = \Temporal\Spec\PlainDateTime::from(['year' => 2021, 'monthCode' => 'M03', 'day' => 7, 'hour' => 12, 'minute' => 34, 'calendar' => $calendar], $options);
$date20210315 = \Temporal\Spec\PlainDateTime::from(['year' => 2021, 'monthCode' => 'M03', 'day' => 15, 'hour' => 12, 'minute' => 34, 'calendar' => $calendar], $options);
$date20210601 = \Temporal\Spec\PlainDateTime::from(['year' => 2021, 'monthCode' => 'M06', 'day' => 1, 'hour' => 12, 'minute' => 34, 'calendar' => $calendar], $options);
$date20220228 = \Temporal\Spec\PlainDateTime::from(['year' => 2022, 'monthCode' => 'M02', 'day' => 28, 'hour' => 12, 'minute' => 34, 'calendar' => $calendar], $options);
$tests = [[$date20210107, $date20210307, '2 months in same year across Feb 28', ['years', 0, -2, 0, 0], ['months', 0, -2, 0, 0]], [$date19600216, $date20210315, '61 years, 27 days in common year', ['years', -61, 0, 0, -27]], [$date19600216, $date20200315, '60 years, 28 days in leap year', ['years', -60, 0, 0, -28]], [$date20210315, $date19600216, 'negative 61 years, 28 days in common year', ['years', 61, 0, 0, 28]], [$date20200315, $date19600216, 'negative 60 years, 28 days in leap year', ['years', 60, 0, 0, 28]], [$date20210307, $date20210107, 'negative 2 month in same year across Feb 28', ['years', 0, 2, 0, 0], ['months', 0, 2, 0, 0]], [$date20200201, $date20210201, 'year including leap day', ['weeks', 0, 0, -52, -2]], [$date20210228, $date20220228, 'year not including leap day', ['weeks', 0, 0, -52, -1]], [$date20190101, $date20200101, 'length of year from January 2019', ['days', 0, 0, 0, -365]], [$date20200101, $date20210101, 'length of year from January 2020', ['days', 0, 0, 0, -366]], [$date20190601, $date20200601, 'length of year from June 2019', ['days', 0, 0, 0, -366]], [$date20200601, $date20210601, 'length of year from June 2020', ['days', 0, 0, 0, -365]], [$date20190201, $date20190301, 'length of Feb 2019', ['days', 0, 0, 0, -28]], [$date20200201, $date20200301, 'length of Feb 2020', ['days', 0, 0, 0, -29]]];
foreach ($tests as $__entry_units__) {
[$one, $two, $descr] = array_pad($__entry_units__, 3, null);
$units = array_slice($__entry_units__, 3);
foreach ($units as $__entry__) {
[$largestUnit, $years, $months, $weeks, $days] = array_pad($__entry__, 5, null);
TemporalHelpers::assertDuration($one->since($two, ['largestUnit' => $largestUnit]), $years, $months, $weeks, $days, 0, 0, 0, 0, 0, 0, $descr);
}
}
