<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/compare/argument-string-limits.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instance = new \Temporal\Spec\PlainDateTime(1976, 11, 18);
$validStrings = ['-271821-04-19T00:00:00.000000001', '-271821-04-20', '+275760-09-13', '+275760-09-13T23:59:59.999999999'];
foreach ($validStrings as $arg) {
\Temporal\Spec\PlainDateTime::compare($arg, $instance);
\Temporal\Spec\PlainDateTime::compare($instance, $arg);
}
$invalidStrings = ['-271821-04-19', '-271821-04-19T00:00', '+275760-09-14', '+275760-09-14T00:00'];
foreach ($invalidStrings as $arg) {
Assert::throws(\InvalidArgumentException::class, function () use (&$arg, &$instance) { return \Temporal\Spec\PlainDateTime::compare($arg, $instance); }, "\"{$arg}\" is outside the representable range of PlainDateTime (first argument)");
Assert::throws(\InvalidArgumentException::class, function () use (&$instance, &$arg) { return \Temporal\Spec\PlainDateTime::compare($instance, $arg); }, "\"{$arg}\" is outside the representable range of PlainDateTime (second argument)");
}
