<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDateTime/compare/use-internal-slots.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
$CustomError = function () {
};
// JS-only (getter-only Temporal subclass; getters never fire in PHP, aliased to PlainDateTime): class AvoidGettersDateTime extends Temporal.PlainDateTime { get year() { throw new CustomError(); } get month() { throw new CustomError(); } get day() { throw …
$one = new \Temporal\Spec\PlainDateTime(2000, 5, 2, 12, 34, 56, 987, 654, 321);
$two = new \Temporal\Spec\PlainDateTime(2006, 3, 25, 6, 54, 32, 123, 456, 789);
Assert::sameValue(\Temporal\Spec\PlainDateTime::compare($one, $two), -1, '');
