<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/prototype/weekOfYear/basic.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$zdt = new \Temporal\PlainDateTime(1976, 11, 18, 15, 23, 30, 123, 456, 789)->toZonedDateTime('UTC');
Assert::sameValue($zdt->weekOfYear, 47, 'check week of year information');
for ($i = 29; $i <= 31; ++$i) {
$zdt = new \Temporal\PlainDateTime(1975, 12, $i, 15, 23, 30, 123, 456, 789)->toZonedDateTime('UTC');
Assert::sameValue($zdt->weekOfYear, 1, "{$zdt} should be in week 1");
}
for ($i = 1; $i <= 4; ++$i) {
$zdt = new \Temporal\PlainDateTime(1976, 1, $i, 15, 23, 30, 123, 456, 789)->toZonedDateTime('UTC');
Assert::sameValue($zdt->weekOfYear, 1, "{$zdt} should be in week 1");
}
for ($i = 5; $i <= 11; ++$i) {
$zdt = new \Temporal\PlainDateTime(1976, 1, $i, 15, 23, 30, 123, 456, 789)->toZonedDateTime('UTC');
Assert::sameValue($zdt->weekOfYear, 2, "{$zdt} should be in week 2");
}
for ($i = 20; $i <= 26; ++$i) {
$zdt = new \Temporal\PlainDateTime(1976, 12, $i, 15, 23, 30, 123, 456, 789)->toZonedDateTime('UTC');
Assert::sameValue($zdt->weekOfYear, 52, "{$zdt} should be in week 52");
}
for ($i = 27; $i <= 31; ++$i) {
$zdt = new \Temporal\PlainDateTime(1976, 12, $i, 15, 23, 30, 123, 456, 789)->toZonedDateTime('UTC');
Assert::sameValue($zdt->weekOfYear, 53, "{$zdt} should be in week 53");
}
for ($i = 1; $i <= 2; ++$i) {
$zdt = new \Temporal\PlainDateTime(1977, 1, $i, 15, 23, 30, 123, 456, 789)->toZonedDateTime('UTC');
Assert::sameValue($zdt->weekOfYear, 53, "{$zdt} should be in week 53");
}
