<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainDateTime/prototype/until/canonicalize-calendar.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instance = new \Temporal\Spec\PlainDateTime(2024, 7, 2, 12, 34, 0, 0, 0, 0, 'islamic-civil');
foreach (['2024-07-02T12:34[u-ca=islamicc]', ['year' => 1445, 'month' => 12, 'day' => 25, 'hour' => 12, 'minute' => 34, 'calendar' => 'islamicc']] as $arg) {
$result = $instance->until($arg);
Assert::assertTrue($result->blank, 'calendar ID is canonicalized');
}
