<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/PlainDateTime/prototype/until/wrapping-at-end-of-month-islamic-tbla.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$calendar = 'islamic-tbla';
$end = \Temporal\Spec\PlainDateTime::from(['year' => 1970, 'monthCode' => 'M02', 'day' => 29, 'hour' => 12, 'minute' => 34, 'calendar' => $calendar]);
foreach (['years', 'months'] as $largestUnit) {
TemporalHelpers::assertDuration(\Temporal\Spec\PlainDateTime::from(['year' => 1970, 'monthCode' => 'M01', 'day' => 29, 'hour' => 12, 'minute' => 34, 'calendar' => $calendar])->until($end, ['largestUnit' => $largestUnit]), 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, "Muharram 29th to Safar 29th is one month ({$largestUnit})");
TemporalHelpers::assertDuration(\Temporal\Spec\PlainDateTime::from(['year' => 1970, 'monthCode' => 'M01', 'day' => 30, 'hour' => 12, 'minute' => 34, 'calendar' => $calendar])->until($end, ['largestUnit' => $largestUnit]), 0, 0, 0, 29, 0, 0, 0, 0, 0, 0, "Muharram 30th to Safar 29th is 29 days, not one month ({$largestUnit})");
}
$end = \Temporal\Spec\PlainDateTime::from(['year' => 1970, 'monthCode' => 'M04', 'day' => 29, 'hour' => 12, 'minute' => 34, 'calendar' => $calendar]);
foreach (['years', 'months'] as $largestUnit) {
TemporalHelpers::assertDuration(\Temporal\Spec\PlainDateTime::from(['year' => 1970, 'monthCode' => 'M01', 'day' => 29, 'hour' => 12, 'minute' => 34, 'calendar' => $calendar])->until($end, ['largestUnit' => $largestUnit]), 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, "Muharram 29th to Thani 29th is 3 months ({$largestUnit})");
TemporalHelpers::assertDuration(\Temporal\Spec\PlainDateTime::from(['year' => 1970, 'monthCode' => 'M01', 'day' => 30, 'hour' => 12, 'minute' => 34, 'calendar' => $calendar])->until($end, ['largestUnit' => $largestUnit]), 0, 2, 0, 29, 0, 0, 0, 0, 0, 0, "Muharram 30th to Thani 29th is 2 months 29 days, not 3 months ({$largestUnit})");
}
$end = \Temporal\Spec\PlainDateTime::from(['year' => 1973, 'monthCode' => 'M02', 'day' => 29, 'hour' => 12, 'minute' => 34, 'calendar' => $calendar]);
TemporalHelpers::assertDuration(\Temporal\Spec\PlainDateTime::from(['year' => 1970, 'monthCode' => 'M11', 'day' => 29, 'hour' => 12, 'minute' => 34, 'calendar' => $calendar])->until($end, ['largestUnit' => 'months']), 0, 27, 0, 0, 0, 0, 0, 0, 0, 0, 'Qadah 29th 1970 to Safar 29th 1973 is 27 months');
TemporalHelpers::assertDuration(\Temporal\Spec\PlainDateTime::from(['year' => 1970, 'monthCode' => 'M11', 'day' => 29, 'hour' => 12, 'minute' => 34, 'calendar' => $calendar])->until($end, ['largestUnit' => 'years']), 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 'Qadah 29th 1970 to Safar 29th 1973 is 2 years, 3 months');
TemporalHelpers::assertDuration(\Temporal\Spec\PlainDateTime::from(['year' => 1970, 'monthCode' => 'M11', 'day' => 30, 'hour' => 12, 'minute' => 34, 'calendar' => $calendar])->until($end, ['largestUnit' => 'months']), 0, 26, 0, 29, 0, 0, 0, 0, 0, 0, 'Qadah 30th 1970 to Safar 29th 1973 is 26 months, 29 days, not 27 months');
TemporalHelpers::assertDuration(\Temporal\Spec\PlainDateTime::from(['year' => 1970, 'monthCode' => 'M11', 'day' => 30, 'hour' => 12, 'minute' => 34, 'calendar' => $calendar])->until($end, ['largestUnit' => 'years']), 2, 2, 0, 29, 0, 0, 0, 0, 0, 0, 'Qadah 30th 1970 to Safar 29th 1973 is 2 years, 2 months, 29 days, not 2 years 3 months');
