<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/compare/argument-propertybag-calendar-string.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$calendar = 'iso8601';
$arg = ['year' => 1976, 'monthCode' => 'M11', 'day' => 18, 'calendar' => $calendar];
$result1 = \Temporal\Spec\PlainDate::compare($arg, new \Temporal\Spec\PlainDate(1976, 11, 18));
Assert::sameValue($result1, 0, "Calendar created from string \"" . json_encode($arg) . "\" (first argument)");
$result2 = \Temporal\Spec\PlainDate::compare(new \Temporal\Spec\PlainDate(1976, 11, 18), $arg);
Assert::sameValue($result2, 0, "Calendar created from string \"" . json_encode($arg) . "\" (second argument)");
