<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/from/argument-zoneddatetime.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$calendar = 'iso8601';
$zdt = new \Temporal\Spec\ZonedDateTime(1_000_000_000_987_654_321, 'UTC', $calendar);
$result = \Temporal\Spec\PlainDate::from($zdt);
TemporalHelpers::assertPlainDate($result, 2001, 9, 'M09', 9, 'ZonedDateTime is converted');
Assert::sameValue($result->calendarId, $calendar, 'Calendar is copied');
