<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/from/argument-number.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$numbers = [1, 19_761_118, -19_761_118, 1_234_567_890];
foreach ($numbers as $arg) {
Assert::throws(\TypeError::class, fn() => \Temporal\Spec\PlainDate::from($arg), 'Numbers cannot be used in place of an ISO string for PlainDate');
}
