<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/from/argument-string-calendar-invalid-iso-string.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$invalidStrings = [['', 'empty string'], ['1997-12-04[u-ca=notacal]', 'Unknown calendar'], ['1997-12-04[u-ca=11111111]', 'compact ISO date used as calendar name'], ['1997-12-04[u-ca=1111-11-11]', 'extended ISO date used as calendar name']];
foreach ($invalidStrings as [$arg, $description]) {
Assert::throws(\InvalidArgumentException::class, fn() => \Temporal\PlainDate::from($arg), "{$description} is not a valid calendar ID");
}
