<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainDate/from/negative-month-or-day.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
Assert::throws(\InvalidArgumentException::class, fn() => \Temporal\Spec\PlainDate::from(['year' => 2000, 'day' => 1, 'month' => -1]), '');
Assert::throws(\InvalidArgumentException::class, fn() => \Temporal\Spec\PlainDate::from(['year' => 2000, 'month' => 1, 'day' => -1]), '');
