<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/total/balances-days-up-to-both-years-and-months.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$twoYears = new \Temporal\Duration(0, 11, 0, 396, 0, 0, 0, 0, 0, 0);
Assert::sameValue($twoYears->total(['unit' => 'years', 'relativeTo' => new \Temporal\PlainDate(2017, 1, 1)]), 2, '');
$twoYearsNegative = new \Temporal\Duration(0, -11, 0, -396, 0, 0, 0, 0, 0, 0);
Assert::sameValue($twoYearsNegative->total(['unit' => 'years', 'relativeTo' => new \Temporal\PlainDate(2017, 1, 1)]), -2, '');
