<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/total/relativeto-must-have-required-properties.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$d = new \Temporal\Spec\Duration(0, 0, 0, 0, 0, 0, 0, 2, 31, 0);
Assert::throws(\TypeError::class, function () use (&$d) { return $d->total((object) ['unit' => 'months', 'relativeTo' => (object) []]); }, '');
Assert::throws(\TypeError::class, function () use (&$d) { return $d->total((object) ['unit' => 'months', 'relativeTo' => (object) ['years' => 2020, 'month' => 1, 'day' => 1]]); }, '');
