<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/total/relativeto-zoneddatetime-negative-epochnanoseconds.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$relativeTo = new \Temporal\ZonedDateTime(-13_849_764_999_999_999, 'UTC');
$duration = new \Temporal\Duration(0, 0, 0, 1);
$result = $duration->total(['relativeTo' => $relativeTo, 'unit' => 'days']);
Assert::sameValue($result, 1, '');
