<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/total/relativeto-number.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instance = new \Temporal\Spec\Duration(1, 0, 0, 0, 24);
$numbers = [1, 20_191_101, -20_191_101, 1_234_567_890];
foreach ($numbers as $relativeTo) {
Assert::throws(\TypeError::class, function () use (&$instance, &$relativeTo) { return $instance->total(['unit' => 'days', 'relativeTo' => $relativeTo]); }, "A number ({$relativeTo}) is not a valid ISO string for relativeTo");
}
