<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/total/relativeto-zoneddatetime-large-time-component-out-of-range.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
$relativeTo = new \Temporal\Spec\ZonedDateTime(0, 'UTC');
foreach ([-9_007_199_254_740_991, 9_007_199_254_740_991] as $seconds) {
$d = new \Temporal\Spec\Duration(0, 0, 0, 0, 0, 0, $seconds);
Assert::throws(\RangeException::class, function () use (&$d, &$relativeTo) { return $d->total(JsUndefined::strip(['unit' => 'year', 'relativeTo' => $relativeTo])); }, '');
Assert::throws(\RangeException::class, function () use (&$d, &$relativeTo) { return $d->total(JsUndefined::strip(['unit' => 'month', 'relativeTo' => $relativeTo])); }, '');
Assert::throws(\RangeException::class, function () use (&$d, &$relativeTo) { return $d->total(JsUndefined::strip(['unit' => 'week', 'relativeTo' => $relativeTo])); }, '');
}
