<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/total/throws-if-date-time-invalid-with-plaindate-relative.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$duration = new \Temporal\Duration(0, 0, 0, 0, 0, 0, 0, 0, 0, 1);
Assert::incomplete('\\Temporal\\PlainDate is not yet implemented');
