<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/total/throws-if-target-nanoseconds-outside-valid-limits.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
$duration = new \Temporal\Spec\Duration(0, 0, 0, 0, 0, 0, 0, 0, 0, 1);
$relativeTo = \Temporal\Spec\ZonedDateTime::fromInstantParts(8640000000000, 0, 'UTC');
$totalOf = (object) JsUndefined::strip(['unit' => 'nanoseconds', 'relativeTo' => $relativeTo]);
Assert::throws(\InvalidArgumentException::class, function () use (&$duration, &$totalOf) { return $duration->total($totalOf); }, '');
