<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/total/unit-disallowed-units-string.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$instance = new \Temporal\Duration(0, 0, 0, 4, 5, 6, 7, 987, 654, 321);
$invalidUnits = ['era', 'eras'];
foreach ($invalidUnits as $unit) {
Assert::throws(\InvalidArgumentException::class, fn() => $instance->total(['unit' => $unit]), "{ unit: \"{$unit}\" } should not be allowed as an argument to total");
Assert::throws(\InvalidArgumentException::class, fn() => $instance->total($unit), "\"{$unit}\" should not be allowed as an argument to total");
}
