<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/ZonedDateTime/from/argument-propertybag-subminute-offset.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$zdt = \Temporal\Spec\ZonedDateTime::from(['year' => 1971, 'month' => 1, 'day' => 1, 'hour' => 12, 'timeZone' => 'Africa/Monrovia']);
Assert::sameValue($zdt->offset, '-00:44:30', '');
