<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/ZonedDateTime/from/calendar-invalid-era-with-era-year.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$calendarsWithEras = ['buddhist', 'coptic', 'ethioaa', 'ethiopic', 'gregory', 'hebrew', 'indian', 'islamic-civil', 'islamic-tbla', 'islamic-umalqura', 'japanese', 'persian', 'roc'];
foreach ($calendarsWithEras as $calendar) {
Assert::throws(\InvalidArgumentException::class, fn() => \Temporal\Spec\ZonedDateTime::from(['month' => 1, 'day' => 1, 'hour' => 12, 'minute' => 34, 'timeZone' => 'UTC', 'era' => 'xyz', 'eraYear' => 2025, 'calendar' => $calendar]), "xyz is not a valid era in calendar {$calendar}");
}
