<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/ZonedDateTime/from/do-not-canonicalize-iana-identifiers.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$calcutta = \Temporal\Spec\ZonedDateTime::from('2020-01-01T00:00:00+05:30[Asia/Calcutta]');
$kolkata = \Temporal\Spec\ZonedDateTime::from('2020-01-01T00:00:00+05:30[Asia/Kolkata]');
Assert::sameValue($calcutta->toString(), '2020-01-01T00:00:00+05:30[Asia/Calcutta]', '');
Assert::sameValue($calcutta->toJSON(), '2020-01-01T00:00:00+05:30[Asia/Calcutta]', '');
Assert::sameValue($calcutta->timeZoneId, 'Asia/Calcutta', '');
Assert::sameValue($kolkata->toString(), '2020-01-01T00:00:00+05:30[Asia/Kolkata]', '');
Assert::sameValue($kolkata->toJSON(), '2020-01-01T00:00:00+05:30[Asia/Kolkata]', '');
Assert::sameValue($kolkata->timeZoneId, 'Asia/Kolkata', '');
