<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/ZonedDateTime/from/era-japanese.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$calendar = 'japanese';
$reiwa = \Temporal\Spec\ZonedDateTime::from(['era' => 'reiwa', 'eraYear' => 2, 'month' => 1, 'day' => 1, 'hour' => 12, 'minute' => 34, 'timeZone' => 'UTC', 'calendar' => $calendar]);
$heisei = \Temporal\Spec\ZonedDateTime::from(['era' => 'heisei', 'eraYear' => 2, 'month' => 1, 'day' => 1, 'hour' => 12, 'minute' => 34, 'timeZone' => 'UTC', 'calendar' => $calendar]);
$showa = \Temporal\Spec\ZonedDateTime::from(['era' => 'showa', 'eraYear' => 2, 'month' => 1, 'day' => 1, 'hour' => 12, 'minute' => 34, 'timeZone' => 'UTC', 'calendar' => $calendar]);
$taisho = \Temporal\Spec\ZonedDateTime::from(['era' => 'taisho', 'eraYear' => 2, 'month' => 1, 'day' => 1, 'hour' => 12, 'minute' => 34, 'timeZone' => 'UTC', 'calendar' => $calendar]);
$meiji = \Temporal\Spec\ZonedDateTime::from(['era' => 'meiji', 'eraYear' => 6, 'month' => 1, 'day' => 1, 'hour' => 12, 'minute' => 34, 'timeZone' => 'UTC', 'calendar' => $calendar]);
$ce = \Temporal\Spec\ZonedDateTime::from(['era' => 'ce', 'eraYear' => 1000, 'month' => 1, 'day' => 1, 'hour' => 12, 'minute' => 34, 'timeZone' => 'UTC', 'calendar' => $calendar]);
$bce = \Temporal\Spec\ZonedDateTime::from(['era' => 'bce', 'eraYear' => 1, 'month' => 1, 'day' => 1, 'hour' => 12, 'minute' => 34, 'timeZone' => 'UTC', 'calendar' => $calendar]);
TemporalHelpers::assertPlainDateTime($reiwa->toPlainDateTime(), 2020, 1, 'M01', 1, 12, 34, 0, 0, 0, 0, "{$reiwa}", 'reiwa', 2);
TemporalHelpers::assertPlainDateTime($heisei->toPlainDateTime(), 1990, 1, 'M01', 1, 12, 34, 0, 0, 0, 0, "{$heisei}", 'heisei', 2);
TemporalHelpers::assertPlainDateTime($showa->toPlainDateTime(), 1927, 1, 'M01', 1, 12, 34, 0, 0, 0, 0, "{$showa}", 'showa', 2);
TemporalHelpers::assertPlainDateTime($taisho->toPlainDateTime(), 1913, 1, 'M01', 1, 12, 34, 0, 0, 0, 0, "{$taisho}", 'taisho', 2);
TemporalHelpers::assertPlainDateTime($meiji->toPlainDateTime(), 1873, 1, 'M01', 1, 12, 34, 0, 0, 0, 0, "{$meiji}", 'meiji', 6);
TemporalHelpers::assertPlainDateTime($ce->toPlainDateTime(), 1000, 1, 'M01', 1, 12, 34, 0, 0, 0, 0, "{$ce} (CE)", 'ce', 1000);
TemporalHelpers::assertPlainDateTime($bce->toPlainDateTime(), 0, 1, 'M01', 1, 12, 34, 0, 0, 0, 0, "{$bce} (BCE)", 'bce', 1);
