<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/ZonedDateTime/from/leap-year-hebrew.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$calendar = 'hebrew';
$options = ['overflow' => 'reject'];
$leapYear = 5784;
$monthLengths5784 = [null, ['M01', 30], ['M02', 29], ['M03', 29], ['M04', 29], ['M05', 30], ['M05L', 30], ['M06', 29], ['M07', 30], ['M08', 29], ['M09', 30], ['M10', 29], ['M11', 30], ['M12', 29]];
for ($month = 1; $month < 14; $month++) {
[$monthCode, $day] = array_pad($monthLengths5784[$month], 2, null);
$startOfMonth = \Temporal\Spec\ZonedDateTime::from(['year' => $leapYear, 'month' => $month, 'day' => 1, 'hour' => 12, 'minute' => 34, 'timeZone' => 'UTC', 'calendar' => $calendar], $options);
TemporalHelpers::assertPlainDateTime($startOfMonth->toPlainDateTime(), $leapYear, $month, $monthCode, 1, 12, 34, 0, 0, 0, 0, "Start of month {$monthCode} in leap year", 'am', $leapYear);
$endOfMonth = \Temporal\Spec\ZonedDateTime::from(['year' => $leapYear, 'month' => $month, 'day' => $day, 'hour' => 12, 'minute' => 34, 'timeZone' => 'UTC', 'calendar' => $calendar], $options);
TemporalHelpers::assertPlainDateTime($endOfMonth->toPlainDateTime(), $leapYear, $month, $monthCode, $day, 12, 34, 0, 0, 0, 0, "End of month {$monthCode} in leap year", 'am', $leapYear);
}
