<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/ZonedDateTime/from/options-undefined.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$overflowFields = ['year' => 2000, 'month' => 13, 'day' => 2, 'timeZone' => 'UTC'];
$overflowExplicit = \Temporal\Spec\ZonedDateTime::from($overflowFields);
Assert::sameValue($overflowExplicit->month, 12, 'default overflow is constrain');
$overflowPropertyImplicit = \Temporal\Spec\ZonedDateTime::from($overflowFields, new \stdClass());
Assert::sameValue($overflowPropertyImplicit->month, 12, 'default overflow is constrain');
$overflowImplicit = \Temporal\Spec\ZonedDateTime::from($overflowFields);
Assert::sameValue($overflowImplicit->month, 12, 'default overflow is constrain');
$timeZone = 'America/Vancouver';
$disambiguationEarlierFields = ['timeZone' => $timeZone, 'year' => 2000, 'month' => 10, 'day' => 29, 'hour' => 1, 'minute' => 34, 'second' => 56, 'millisecond' => 987, 'microsecond' => 654, 'nanosecond' => 321];
$disambiguationLaterFields = ['timeZone' => $timeZone, 'year' => 2000, 'month' => 4, 'day' => 2, 'hour' => 2, 'minute' => 34, 'second' => 56, 'millisecond' => 987, 'microsecond' => 654, 'nanosecond' => 321];
foreach ([[$disambiguationEarlierFields, 972_808_496_987_654_321], [$disambiguationLaterFields, 954_671_696_987_654_321]] as $__entry__) {
[$fields, $expected] = array_pad($__entry__, 2, null);
$explicit = \Temporal\Spec\ZonedDateTime::from($fields);
Assert::sameValue($explicit->epochNanoseconds, $expected, 'default disambiguation is compatible');
$propertyImplicit = \Temporal\Spec\ZonedDateTime::from($fields, new \stdClass());
Assert::sameValue($propertyImplicit->epochNanoseconds, $expected, 'default disambiguation is compatible');
$implicit = \Temporal\Spec\ZonedDateTime::from($fields);
Assert::sameValue($implicit->epochNanoseconds, $expected, 'default disambiguation is compatible');
}
$offsetFields = ['year' => 2000, 'month' => 5, 'day' => 2, 'offset' => '+23:59', 'timeZone' => 'UTC'];
Assert::throws(\InvalidArgumentException::class, function () use (&$offsetFields) { return \Temporal\Spec\ZonedDateTime::from($offsetFields); }, 'default offset is reject');
Assert::throws(\InvalidArgumentException::class, function () use (&$offsetFields) { return \Temporal\Spec\ZonedDateTime::from($offsetFields, new \stdClass()); }, 'default offset is reject');
Assert::throws(\InvalidArgumentException::class, function () use (&$offsetFields) { return \Temporal\Spec\ZonedDateTime::from($offsetFields); }, 'default offset is reject');
