<?php

declare(strict_types=1);

// Source: tests/Test262/data/intl402/ZonedDateTime/prototype/daysInMonth/basic-islamic-tbla.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$calendar = 'islamic-tbla';
$options = ['overflow' => 'reject'];
$leapYear = 1390;
$commonYear = 1391;
$leapYearDaysInMonth = [30, 29, 30, 29, 30, 29, 30, 29, 30, 29, 30, 30];
$commonYearDaysInMonth = [30, 29, 30, 29, 30, 29, 30, 29, 30, 29, 30, 29];
$daysInMonth = new \stdClass();
$__unknown__ = $leapYearDaysInMonth;
$__unknown__ = $commonYearDaysInMonth;
foreach ([$leapYear, $commonYear] as $year) {
for ($month = 1; $month < 13; $month++) {
$date = \Temporal\Spec\ZonedDateTime::from(['year' => $year, 'month' => $month, 'day' => 1, 'calendar' => $calendar, 'hour' => 12, 'minute' => 34, 'timeZone' => 'UTC']);
Assert::sameValue($date->daysInMonth, $daysInMonth[$year][$month - 1], "{$date}");
}
}
