<?php

declare(strict_types=1);

// Source: tests/Test262/data/ZonedDateTime/timezone-string.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
foreach (['UTC', '+01:30'] as $timeZone) {
$result = new \Temporal\ZonedDateTime(0, $timeZone);
Assert::sameValue($result->timeZoneId, $timeZone, "time zone ID should be \"{$timeZone}\"");
}
