<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainTime/prototype/subtract/argument-string-negative-fractional-units.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$instance = new \Temporal\Spec\PlainTime();
$resultHours = $instance->subtract('-PT24.567890123H');
TemporalHelpers::assertPlainTime($resultHours, 0, 34, 4, 404, 442, 800, 'negative fractional hours');
$resultMinutes = $instance->subtract('-PT1440.567890123M');
TemporalHelpers::assertPlainTime($resultMinutes, 0, 0, 34, 73, 407, 380, 'negative fractional minutes');
