<?php

declare(strict_types=1);

// Source: tests/Test262/data/Duration/prototype/toJSON/options.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
$called = 0;
$options = null;
$d = new \Temporal\Spec\Duration(1, 2);
Assert::sameValue($d->toJSON($options), 'P1Y2M', '');
Assert::sameValue($called, 0, '');
