<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainMonthDay/from/argument-propertybag-calendar-leap-second.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$calendar = '2016-12-31T23:59:60';
$arg = ['monthCode' => 'M11', 'day' => 18, 'calendar' => $calendar];
$result = \Temporal\PlainMonthDay::from($arg);
TemporalHelpers::assertPlainMonthDay($result, 'M11', 18, 'leap second is a valid ISO string for calendar');
