<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainMonthDay/from/iso-year-used-only-for-overflow.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
$outOfRangeCommonYear = -999_999;
$outOfRangeLeapYear = -1_000_000;
$result = \Temporal\PlainMonthDay::from(['year' => $outOfRangeCommonYear, 'month' => 1, 'day' => 1]);
TemporalHelpers::assertPlainMonthDay($result, 'M01', 1, 'ISO year is not checked for range');
$commonResult = \Temporal\PlainMonthDay::from(['year' => $outOfRangeCommonYear, 'monthCode' => 'M02', 'day' => 29]);
TemporalHelpers::assertPlainMonthDay($commonResult, 'M02', 28, 'ISO year is used to apply overflow');
Assert::throws(\InvalidArgumentException::class, function () use ($outOfRangeCommonYear) { \Temporal\PlainMonthDay::from(['year' => $outOfRangeCommonYear, 'monthCode' => 'M02', 'day' => 29], ['overflow' => 'reject']); }, 'ISO year is used to apply overflow');
$leapResult = \Temporal\PlainMonthDay::from(['year' => $outOfRangeLeapYear, 'monthCode' => 'M02', 'day' => 29]);
TemporalHelpers::assertPlainMonthDay($leapResult, 'M02', 29, 'ISO year is used to apply overflow');
