<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainMonthDay/from/monthcode-invalid.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
foreach (['m1', 'M1', 'm01'] as $monthCode) {
Assert::throws(\RangeException::class, function () use (&$monthCode) { return \Temporal\Spec\PlainMonthDay::from(JsUndefined::strip(['monthCode' => $monthCode, 'day' => 17])); }, "monthCode '{$monthCode}' is not well-formed (without numeric month)");
Assert::throws(\RangeException::class, function () use (&$monthCode) { return \Temporal\Spec\PlainMonthDay::from(JsUndefined::strip(['month' => 1, 'monthCode' => $monthCode, 'day' => 17])); }, "monthCode '{$monthCode}' is not well-formed (with numeric month)");
}
Assert::throws(\RangeException::class, fn() => \Temporal\Spec\PlainMonthDay::from(['year' => 2021, 'month' => 12, 'monthCode' => 'M11', 'day' => 17]), 'monthCode and month conflict');
foreach (['M00', 'M19', 'M99', 'M13', 'M00L', 'M05L', 'M13L'] as $monthCode) {
Assert::throws(\RangeException::class, function () use (&$monthCode) { return \Temporal\Spec\PlainMonthDay::from(JsUndefined::strip(['monthCode' => $monthCode, 'day' => 17])); }, "monthCode '{$monthCode}' is not valid for ISO 8601 calendar (without numeric month)");
$monthNumber = (float) (\Temporal\Tests\Test262\Js::slice($monthCode, 1, 3)) + ((is_string($monthCode) ? strlen($monthCode) : count($monthCode)) - 3);
Assert::throws(\RangeException::class, function () use (&$monthNumber, &$monthCode) { return \Temporal\Spec\PlainMonthDay::from(JsUndefined::strip(['month' => $monthNumber, 'monthCode' => $monthCode, 'day' => 17])); }, "monthCode '{$monthCode}' is not valid for ISO 8601 calendar (with numeric month)");
$clampedMonthNumber = ($monthNumber < 1 ? 1 : ($monthNumber > 12 ? 12 : $monthNumber));
Assert::throws(\RangeException::class, function () use (&$clampedMonthNumber, &$monthCode) { return \Temporal\Spec\PlainMonthDay::from(JsUndefined::strip(['month' => $clampedMonthNumber, 'monthCode' => $monthCode, 'day' => 17])); }, "monthCode '{$monthCode}' is not valid for ISO 8601 calendar (with clamped numeric month)");
}
Assert::throws(\RangeException::class, fn() => \Temporal\Spec\PlainMonthDay::from(JsUndefined::strip(['day' => 1, 'monthCode' => 'L99M', 'year' => \Temporal\Tests\Test262\JsSymbol::singleton()])), 'Month code syntax is validated before year type is validated');
Assert::throws(\TypeError::class, fn() => \Temporal\Spec\PlainMonthDay::from(JsUndefined::strip(['day' => 1, 'monthCode' => 'M99L', 'year' => \Temporal\Tests\Test262\JsSymbol::singleton()])), 'Month code suitability is validated after year type is validated');
