<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainMonthDay/from/options-wrong-type.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
$badOptions = [null, true, 'some string', \Temporal\Tests\Test262\JsSymbol::singleton(), 1, 2];
foreach ($badOptions as $value) {
if ($value === null) { continue; }
Assert::throws(\TypeError::class, function () use (&$value) { return \Temporal\Spec\PlainMonthDay::from(['monthCode' => 'M12', 'day' => 15], $value); }, "TypeError on wrong options type " . (gettype($value)) . "");
Assert::throws(\TypeError::class, function () use (&$value) { return \Temporal\Spec\PlainMonthDay::from(new \Temporal\Spec\PlainMonthDay(12, 15), $value); }, 'TypeError thrown before cloning PlainMonthDay instance');
Assert::throws(\RangeException::class, function () use (&$value) { return \Temporal\Spec\PlainMonthDay::from('1976-11-18Z', $value); }, 'Invalid string string processed before throwing TypeError');
}
