<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainMonthDay/from/options-invalid.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
$fields = (object) ['month' => 2, 'day' => 31];
$values = [null, true, 'hello', \Temporal\Tests\Test262\JsSymbol::singleton(), 1, 1];
foreach ($values as $badOptions) {
if ($badOptions === null) { continue; }
Assert::throws(\TypeError::class, function () use (&$fields, &$badOptions) { return \Temporal\Spec\PlainMonthDay::from($fields, $badOptions); }, '');
}
