<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainMonthDay/from/order-of-operations.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\JsUndefined;
use Temporal\Tests\Test262\TemporalHelpers;
$expectedOptionsReading = ['get options.overflow', 'get options.overflow.toString', 'call options.overflow.toString'];
$expectedOpsForPrimitiveOptions = ['get fields.calendar', 'get fields.day', 'get fields.day.valueOf', 'call fields.day.valueOf', 'get fields.month', 'get fields.month.valueOf', 'call fields.month.valueOf', 'get fields.monthCode', 'get fields.monthCode.toString', 'call fields.monthCode.toString', 'get fields.year', 'get fields.year.valueOf', 'call fields.year.valueOf'];
$expected = array_merge($expectedOpsForPrimitiveOptions, $expectedOptionsReading);
$actual = [];
$fields = TemporalHelpers::propertyBagObserver($actual, ['year' => 1.7, 'month' => 1.7, 'monthCode' => 'M01', 'day' => 1.7, 'calendar' => 'iso8601'], 'fields', ['calendar']);
$options = TemporalHelpers::propertyBagObserver($actual, ['overflow' => 'constrain', 'extra' => 'property'], 'options');
\Temporal\Spec\PlainMonthDay::from($fields, $options);
// JS-only (observer call-order check, tracker is empty in PHP): assert.compareArray(actual, expected, "order of operations");
// JS-only (observer tracker reset (no-op in PHP)): actual.splice(0);
\Temporal\Spec\PlainMonthDay::from(new \Temporal\Spec\PlainMonthDay(5, 2), $options);
// JS-only (observer call-order check, tracker is empty in PHP): assert.compareArray(actual, expectedOptionsReading, "order of operations when cloning a PlainMonthDay instance");
// JS-only (observer tracker reset (no-op in PHP)): actual.splice(0);
\Temporal\Spec\PlainMonthDay::from('05-02', $options);
// JS-only (observer call-order check, tracker is empty in PHP): assert.compareArray(actual, expectedOptionsReading, "order of operations when parsing a string");
// JS-only (observer tracker reset (no-op in PHP)): actual.splice(0);
// JS-only (JS rejects non-object options via ToObject; PHP accepts null as "absent"): assert.throws(TypeError, () => Temporal.PlainMonthDay.from(fields, null));
// JS-only (observer call-order check, tracker is empty in PHP): assert.compareArray(actual, expectedOpsForPrimitiveOptions, "item fields are read before TypeError is thrown for primitive options");
// JS-only (observer tracker reset (no-op in PHP)): actual.splice(0);
\PHPUnit\Framework\Assert::assertTrue(true, 'Script completed without throwing');
