<?php

declare(strict_types=1);

// Source: tests/Test262/data/PlainMonthDay/from/subclassing-ignored.js
// Generated by tools/transpile-test262.mjs — do not edit manually.
// Re-generate: composer test262:build

use Temporal\Tests\Test262\Assert;
use Temporal\Tests\Test262\TemporalHelpers;
TemporalHelpers::checkSubclassingIgnoredStatic(\Temporal\PlainMonthDay::class, 'from', ['05-02'], fn($result) => TemporalHelpers::assertPlainMonthDay($result, 'M05', 2));
